### ISSUE TITLE
createSelectorHook vs. TypedUseSelectorHook

### ISSUE THREAD

**Issue by lindapaiste** [reduxjs/redux-toolkit#1000]
I'm under the impression that `createSelectorHook` is the preferred method of creating a type-safe `useSelector` hook and that `TypedUseSelectorHook` is the old, outdated method.  Please correct me if I am wrong here.

If I am correct then this section of the docs ["Define Typed Hooks"](https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks) should be updated.

**Comment by markerikson** [comment]
No, `createSelectorHook`'s only purpose is to allow you to provide your own custom Context instance instead of the default `ReactReduxContext`. This is almost never needed, and definitely not needed for the purpose of creating a typed version of `useSelector`:

https://github.com/reduxjs/react-redux/blob/994b390f64f7368df188d977398f12b18f6fcb8c/src/hooks/useSelector.js#L98-L104

```js
/**
 * Hook factory, which creates a `useSelector` hook bound to a given context.
 *
 * @param {React.Context} [context=ReactReduxContext] Context passed to your `<Provider>`.
 * @returns {Function} A `useSelector` hook bound to the specified context.
 */
export function createSelectorHook(context = ReactReduxContext) {
```

**Comment by lindapaiste** [comment]
Thanks for giving me an official answer on this.  I've seen [multiple](https://stackoverflow.com/a/65049635/10431574) [places](https://stackoverflow.com/q/64895977/10431574) on StackOverflow where people were saying that `TypedUseSelectorHook` was deprecated but I didn't see anything in the code saying it was deprecated.

**Comment by markerikson** [comment]
Hah, so that actually _was_ a thing that happend, sorta!

The React-Redux types are maintained in DefinitelyTyped, separate from our repo:

Problem is, someone apparently filed a PR that did indeed mark `TypedUseSelectorHook` as "deprecated", without ever asking us if that was actually the case, and that tweak to the typedefs got merged and auto-released:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46446

I can only assume that they saw the addition of `createSelectorHook` and misunderstood its intended purpose.

When we happened to notice this a few months later, @phryneas had to go file a new PR to revert that change:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50222

and also added me as an owner to the typedefs so I'd get notified on any future PRs.
