### ISSUE TITLE
async thunk and type

### ISSUE THREAD

**Issue by rwanito** [reduxjs/redux-toolkit#1001]
Hi !

I use async thunk to use severals async functions.
 
My thunk is like that : 
```javascript

import { createAsyncThunk } from '@reduxjs/toolkit';
import * as Location from 'expo-location';
import { HandledResponseWithPayload } from '~/ts/types/handled.types';
import type { ThunkType } from '~/ts/types/redux.types';
import { UserLocationPermission } from '~/ts/types/user.types';

export const checkLocationPermission = createAsyncThunk<
  HandledResponseWithPayload<UserLocationPermission>,
  void,
  ThunkType
>(`$thunk/checkLocationPermission`, async () => {
  // Dans l'ordre
  const isServiceActivated = await Location.hasServicesEnabledAsync();
  const foregroundLocation = await Location.getForegroundPermissionsAsync();
  const backgroundLocation = await Location.getBackgroundPermissionsAsync();

  return {
    code: 'fulfilled',
    name: 'notifications:flags.fulfilled',
    message: 'notifications:permissions.location.success',
    data: {
      isServiceActivated,
      foregroundLocation,
      backgroundLocation
    }
  };
});
```

My page, with react-native, needs prop : `checkPermissionLocationAndDispatch: typeof checkLocationPermission;`.
That I connect like that : 
```javascript
const mapStateToProps = (state: RootState): Partial<Props> => ({
  currentTraject: state.currentTraject,
  userSettings: state.user.settings,
  userLocationPermission: state.user.permissions.location.data
});
const mapDispatchToProps = (dispatch: AppDispatch): Partial<Props> => ({
  startTracking: () => dispatch(startCurrentTraject()),
  endTracking: () => dispatch(endCurrentTraject()),
  checkPermissionLocationAndDispatch: () => dispatch(checkLocationPermission()),
  fakeAddPoints: (arg: LocationObject) => dispatch(addPoints([arg]))
});

export const ConnectedHome = connect(mapStateToProps, mapDispatchToProps)(Home);
```
And when I use `checkPermissionLocationAndDispatch`, vscode tells me that this function doesn't have `.then`.
```javascript
checkPermissionLocationAndDispatch().then(console.log);
Property 'then' does not exist on type 'AsyncThunkAction<HandledResponseWithPayload<UserLocationPermission>, void, ThunkType>'.ts(2339)
```

Have I the good way to connect async thunk in my react-native page ?

Thanks a lot for your work !

**Comment by markerikson** [comment]
Typically that error occurs because you're using a plain version of the `Dispatch` type that does not recognize thunks as a thing that can be dispatched, and therefore also does not understand that thunks can return promises.

I do see that you're using `AppDispatch` as the type in your `mapDispatch` function. To be honest, I don't know how well `connect` passes that type through to the underlying props.

My best recommendation here would be to stop using `connect`, and switch to using the React-Redux hooks API instead. It's easier to use with TS, and we have specific suggestions on how to set that up correctly:

https://redux-toolkit.js.org/tutorials/typescript
