### ISSUE TITLE
Disabling immer autofreeze

### ISSUE THREAD

**Issue by suyashdeshpande** [reduxjs/redux-toolkit#1008]
Hey,

[comment](https://github.com/reduxjs/redux-toolkit/issues/242#issuecomment-549067653).
I don't have a direct dependency on immer and hence if I want to import setAutoFreeze from immer I need to have it in my package.json (as per standards). If I add immer in package.json, will they share the same instance?

**Comment by markerikson** [comment]
As long as it's a compatible semver version with what RTK depends on so that they get deduplicated, yes.

You can sorta get away with not explicitly listing Immer as a dependency but importing it anyway, given how JS package managers normally hoist packages into `node_modules`, but to be most correct it's best to list anything you want to import directly as a specific dependency.
