### ISSUE TITLE
Usage of RTK Query with function call for handling api calls

### ISSUE THREAD

**Issue by DevTGhosh** [reduxjs/redux-toolkit#1125]
With aws amplify all the graphql api calls are handled by a function call that handles all of the url and parameters.  
The api call for add todo graphql mutation will be done like this
e.g 
`await API.graphql(graphqlOperation(mutation.addTodo, {input: {body:”Get milk”})`

Is there a way for me to use rtk query to just call a function without adding base URLs and endpoints and still make use of stuff like optimistic updates and caching?

**Comment by markerikson** [comment]
Yep, see the `queryFn` option:

https://deploy-preview-1016--redux-starter-kit-docs.netlify.app/rtk-query/usage/customizing-queries#customizing-queries-with-queryfn

It may also be possible to set up a "base query" implementation that actually defers to the other SDK for the actual work.  We had a user show us a custom query implementation based on some Expo APIs:

```js
import { createApi } from "@reduxjs/toolkit/query/react";
import * as Contacts from "expo-contacts";

export const contacts = createApi({
  reducerPath: "contacts",
  baseQuery: async (params) => {
    const { fn, args = [] } = params;
    return await Contacts[fn](...args);
  },
  endpoints: (builder) => ({
    contacts: builder.query({
      query: ({ fields = null, pageSize = 0 } = {}) => ({
        fn: "getContactsAsync",
        args: [
          {
            fields,
            pageSize,
          },
        ],
      }),
    }),
  }),
});
```

**Comment by cjsilva-umich** [comment]
@DevTGhosh Did you ever get this working? If so, could you please post back here how to accomplish this? I'm struggling and could really use some examples to get my createApi slice communicating with AWS using API/graphqlOperation.

**Comment by phryneas** [comment]
@cjsilva-umich please provide a complete code example with types - for example a TypeScript playground - that shows what you are struggling with.

**Comment by cjsilva-umich** [comment]
Sure, would appreciate the help. This all stemmed from me wanting to be able to mock the API with msw. I found [this SO answer](https://stackoverflow.com/a/70313785/6581190) where you suggest doing this as opposed to using jest mocking. Our project uses AWS and graphql, so I have to use the "API" and the accompanying "graphql" functions that they provide with "aws-amplify" to make my graphql calls. I found [this SO answer](https://stackoverflow.com/a/72739281/6581190) where you go over how to use queryFn to supply 3rd party libraries to RTK Query endpoints.

Using those as starting points, I have built [this test project](https://codesandbox.io/s/ecstatic-darwin-vfj1jx) that attempts to create the simple graphql Login mutation. Perhaps the endpoint is sufficiently constructed now, I'm not 100% sure. I've gotten it to the point where I'm no longer receiving type errors. My problem is that msw doesn't seem to be intercepting the call to the Login endpoint. Instead I'm getting "No credentials" errors. I'm assuming that this is because msw isn't intercepting my graphql calls. Although it may be something to do with aws's API or graphql methods. (I don't want to actually be testing the real aws-amplify endpoint at this point, we haven't set up the auth yet).

In my codesandbox clicking the Login button calls the login mutation and shows the same errors in the console that I'm getting. You can see my handler definition [here](https://codesandbox.io/s/ecstatic-darwin-vfj1jx?file=/src/mocks/handlers.ts) and my apiSlice definition [here](https://codesandbox.io/s/ecstatic-darwin-vfj1jx?file=/src/features/api/apiSlice.ts). 

I'm sure I'm missing something about how to name and/or catch the calls using msw that are created from RTK query, but I've looked around and I'm just not seeing it.

**Comment by phryneas** [comment]
@cjsilva-umich I don't see any request happening at all there. Could it be that the library is used incorrectly and throws an error before you even try that request?

**Comment by phryneas** [comment]
@cjsilva-umich honestly, I would just assume that you can use that graphql api by just sending normal graphql requests, without any requirements for an additional external client. That would take one variable out of the game. But of course I could be wrong.

As for an example with RTK query, codegen and msw mocks...: https://github.com/reduxjs/redux-toolkit/tree/master/examples/query/react/graphql-codegen

**Comment by DevTGhosh** [comment]
If you are using aws-amplify with graphql codegen I will just paste my basic code here

Main graphql Api file
```ts
import { createApi } from '@reduxjs/toolkit/query/react'
import * as queries from 'src/graphql/queries'

import { fetchPaginatedListGraphqlApi, getSingularDataGraphqlApi } from 'src/utils/fetchGraphqlApi'

const graphqlBaseQuery =
  () =>
  async ({
    queryName,
    data,
    isList,
  }: {
    queryName: keyof typeof queries
    data: any
    isList: boolean
  }) => {
    try {
      let responseData
      if (isList) {
        responseData = await fetchPaginatedListGraphqlApi({ queryName, data })
      } else {
        responseData = await getSingularDataGraphqlApi({ queryName, data })
      }
      return { data: responseData }
    } catch (error) {
      return { error }
    }
  }

export const graphqlApi = createApi({
  baseQuery: graphqlBaseQuery(),
  tagTypes: [
    'Client',
  ],
  endpoints: () => ({}),
})
```
 utility file that actually fetches the data 
fetchGraphqlApi.ts
```ts
import { API, graphqlOperation } from 'aws-amplify'
import * as queries from 'src/graphql/queries'

async function fetchPaginatedListGraphqlApi({
  queryName,
  data,
}: {
  queryName: keyof typeof queries
  data: any
}) {
  try {
    const responseData = [] as any
    let counter = 0
    async function paginateQuery(nextToken: string | null = null): Promise<void> {
      if (counter > 0 && nextToken === null) {
        return
      }
      const response = (await API.graphql(
        graphqlOperation(queries[queryName], { ...data, nextToken })
      )) as any
      const queryData = response.data[queryName]?.items
      nextToken = response.data[queryName]?.nextToken
      counter++
      responseData.push(...queryData)
      return paginateQuery(nextToken)
    }
    await paginateQuery()
    return responseData
  } catch (err: any) {
    console.error('err while fetching', err)
    console.log('queryName err: ', queryName)
    console.log('data err: ', data)
    throw err
  }
}

async function getSingularDataGraphqlApi({
  queryName,
  data,
}: {
  queryName: keyof typeof queries
  data: any
}) {
  try {
    const response = (await API.graphql(graphqlOperation(queries[queryName], { ...data }))) as any
    const responseData = response.data[queryName]
    return responseData
  } catch (err: any) {
    console.error('err while fetching', err)
    console.log('queryName err: ', queryName)
    console.log('data err: ', data)
  }
}

export { fetchPaginatedListGraphqlApi, getSingularDataGraphqlApi }
```

clientApi.ts
```ts
import { graphqlApi } from 'src/redux/api/graphqlApi'
import { API, graphqlOperation } from 'aws-amplify'
import * as queries from 'src/graphql/queries'
import * as mutations from 'src/graphql/mutations'
import { nanoid } from '@reduxjs/toolkit'
import { makeErrorToast, msg } from 'src/utils/makeToast'
import { getProperUpdateValues } from 'src/utils/updateApiUtil'
import { ReduxClients } from 'src/types/apiType'

export const clientApi = graphqlApi.injectEndpoints({
  endpoints: builder => ({
    fetchClientsByTenantId: builder.query({
      query: ({ tenantId }: { tenantId: string }) => ({
        queryName: 'clientsByTenantId',
        data: {
          tenantId,
          filter: { activeFlag: { eq: true } },
          limit: 1000,
        },
        isList: true,
      }),
      transformResponse: (response: ReduxClients[]) => response as ReduxClients[],
      providesTags: result =>
        result
          ? [
              ...result.map(({ id }) => ({
                type: 'Client' as const,
                id: id as string,
              })),
              { type: 'Client', id: 'LIST' },
            ]
          : [{ type: 'Client', id: 'LIST' }],
    }),
 }),
  overrideExisting: false,
})

export const {  useFetchClientsByTenantIdQuery} = clientApi

```
