### ISSUE TITLE
VS Code cannot auto import produce from immer

### ISSUE THREAD

**Issue by duthanhduoc** [reduxjs/redux-toolkit#1132]
I currently use "@reduxjs/toolkit": "^1.5.1". I know redux toolkit use immer and i see immer folder in node_modules. But my VS Code cannot auto suggest immer or reselect. So i have to type to import functions like produce...

https://user-images.githubusercontent.com/33114640/120915434-cfb0d500-c6cd-11eb-98d0-971fb8e24f6f.mp4

**Comment by phryneas** [comment]
Just because we use it internally, that does not make our dependencies available in your vscode autocompletion (it might, but that 100% depends on your setup).

We *do* re-export produce and a few other exports from `immer`, but we call produce `createNextState` on re-export. Generally, you can see those exports [in the docs here](https://redux-toolkit.js.org/api/other-exports#createnextstate) and you would import them from `@reduxjs/toolkit`, not from `immer`.

Also, we re-export `createSelector` of reselect in the same fashion, see [the docs on that](https://redux-toolkit.js.org/api/createSelector) but you'd also import that from  `@reduxjs/toolkit`, not from `reselect`.

If you want to import other things from `immer` and `reselect`, you should actively install those as dependencies because right now they are more "just there by lucky accident", but if we would ever choose to switch to another library with the same behaviour but a different name, those packages would not be installed alongside RTK any more.
