### ISSUE TITLE
Failed to parse source map (v1.6.0)

### ISSUE THREAD

**Issue by kien8995** [reduxjs/redux-toolkit#1154]
When I enable `inline-source-map` in webpack config. A warning was emitted:

`WARNING in ../node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '.../node_modules/@reduxjs/toolkit/dist/module.js.map' file: Error: ENOENT: no such file or directory, open '.../node_modules/@reduxjs/toolkit/dist/module.js.map'`

**Comment by adriankast** [comment]
Same here using the `source-map-loader` v3.0.0 and webpack 5.38.1 with custom webpack configuration.

**Comment by markerikson** [comment]
Can someone put together an example repo that demonstrates this issue?

**Comment by maciejpankanin** [comment]
Here is an example [repo](https://github.com/maciejpankanin/redux-toolkit-example).

I started from this [boilerplate](https://github.com/vikpe/react-webpack-typescript-starter), only changes are in this [commit](https://github.com/maciejpankanin/redux-toolkit-example/commit/fd129c363f551d16cada9fef841d10608dc95f47).

Hope this helps 😄

**Comment by many20** [comment]
1. The Problem is that in the npm package the bundled js code has a wrong "//# sourceMappingURL=" link at the end of the file.
The not minified ones has "//# sourceMappingURL=module.js.map"  and in the minified ones the line is missing. 
2. The source map references an not exiting file "module.ts".

changing sourceMappingUR redux-toolkit.esm.js  to "//# sourceMappingURL=redux-toolkit.esm.js.map" and removing the "modules.ts" Ref in the redux-toolkit.esm.js.map and its working again.
