### ISSUE TITLE
Does immer need to be a dependency in my app package.json?

### ISSUE THREAD

**Issue by hamhamhammy** [reduxjs/redux-toolkit#1201]
Apologies if this has already been asked, I could not find an answer to this question in the docs or github issues.

In my react app, I currently use redux and immer. However I am in the process of upgrading my app to use redux-toolkit.

In the docs - https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#package-cleanup

"we can remove the separate packages we have listed in our package.json - npm uninstall redux redux-thunk reselect".

My question is can I remove my current `immer` dependency in my package.json as well? Meaning redux-toolkit will include it automatically just like redux, redux-thunk, etc.

**Comment by phryneas** [comment]
If you just use the immer functionality from RTK, yes. If you want to import stuff from immer that is not re-exported from RTK, you will need to list it as a dependency.

**Comment by markerikson** [comment]
Yeah, in a typical RTK app, you won't even reference the `immer` package in your own code, because RTK uses it internally inside of `createReducer/createSlice`.  So, it should be safe to remove the `immer` dep from your `package.json` in most cases.  RTK depends on it and it will still be installed, you just don't have to list it explicitly.

**Comment by hamhamhammy** [comment]
Thank you both for the responses, it makes sense to not need immer as a local dependency in my package.json.

One more thought - It could be worth updating the RTK docs with the points you both made.
