### ISSUE TITLE
Suggestion: RTKQ Generated Hooks - return a status enum instead of isLoading etc. boolean

### ISSUE THREAD

**Issue by josiahayres** [reduxjs/redux-toolkit#1253]
I would like to see the generated hooks return a single enum value

```ts
const { data, error, status} = useGetPokemonByNameQuery('bulbasaur')
```
where 
```ts
status = "error" | "fetching" | "loading" | "success" | "uninitialized" 
``` 
rather than 5 different booleans:
```ts
const { data, error, isError, isFetching, isLoading, isSuccess, isUninitialized} = useGetPokemonByNameQuery('bulbasaur')
```

Perhaps this is simply personal preference, but it does feel like the current RTKQ approach is not aligned with the principles guiding Redux toolkit, which is intended to be the standard way to write Redux logic. 

Having a single status enum value will scale much much better, especially in larger components that use multiple queries. 

This change would also be in line with the suggestion given in the [Redux Tutorial](https://redux.js.org/tutorials/essentials/part-5-async-logic#loading-state-for-requests): 

![image](https://user-images.githubusercontent.com/8950327/124401199-10a71280-dd7c-11eb-85da-84f498c1fe5e.png)

**Comment by phryneas** [comment]
While an enum reflects the truth of the items in the cache (and those use such a status enum), it does simply not reflect the truth of the data available in the hooks, as a hook value can be a mix of multiple cache entries.

If you change from 
```
useMyQuery({ page: 4 })
```
to 
```
useMyQuery({ page: 5 })
```
the hook will have `data` for page 4 (and still be `isSuccess`) while at the same time loading (`isFetching`) for page 5. In this case, the hook just is representing two values at once.

While this could *technically* be shown as the enum you are describing up there, it would complicate user code, not make it easier.

At any given time, checks would be for `state === 'loading' || state === 'fetching'`   instead of just checking for `isFetching`. At the same time, a check for `state === 'success' || state === 'fetching'` would be necessary instead of checking `isFetching`.

Also, while it might not be obvious: the current boolean flags work as union discriminators on TypeScript level, just like a status enum would. So there is really no gain from using something else.


> This change would also be in line with the suggestion given in the Redux Tutorial:

You are missing one point: this **is** in line with the Redux tutorial. The Redux tutorial describes how data should be *stored in the state*. This data though is **not** in the state. It is **derived data** that is augmented with additional data that is not available in the store (the information about the last data the hook had already seen before). Derived data can follow completely different rules

**Comment by josiahayres** [comment]
Thank you for writing up such a detailed answer, that helped me understand why it works like this. Appreciate it!
