### ISSUE TITLE
Anyway to use callback for fullfilled / rejected event with createAsyncThunk?

### ISSUE THREAD

**Issue by thaindq** [reduxjs/redux-toolkit#1370]
Something like this?
```
payloadCreators: ...
onFulfilled?: (payload, thunkAPI) => void;
onRejected?: (errorOrRejectValue, thunkAPI) => void;
```
I'm aware that I can use attached action creators like `fulfilled`, `rejected` to catch these events in reducer but it's just way more convenient to have them in `createAsyncThunk`. For example: 

```
const uploadFile = createAsyncThunk(
    'file/upload',
    (file, thunkAPI) => {
        ...
    },
    onFulfilled: (payload, thunkAPI) => thunkAPI.dispatch(showAlert(`File uploaded: Url: ${payload}`)),
    onRejected: (error, thunkAPI) => thunkAPI.dispatch(showAlert(`Upload failed: ${error}`)),
)
```

**Comment by btielen** [comment]
How about using something like this?

```js
const uploadFile = createAsyncThunk(
    'file/upload',
    (file, thunkAPI) => {
        your_api.uploadFile(file)
          .then(response => thunkAPI.dispatch(showAlert(`File uploaded: Url: ${reponse.url}`)
          .catch(error => thunkAPI.dispatch(showAlert(`Upload failed: ${error.message}`)
    });

**Comment by phryneas** [comment]
Could be abstracted a bit:
```js
function wrapWithAlert(promise, thunkApi) {
  return promise.then(
    response => {
      thunkAPI.dispatch(showAlert(`File uploaded: Url: ${reponse.url}`)
      return response
    },
    error => {
      thunkAPI.dispatch(showAlert(`Upload failed: ${error.message}`)
      throw error
    }
  )
}

const uploadFile = createAsyncThunk(
    'file/upload',
    (file, thunkAPI) =>
        wrapWithAlert(your_api.uploadFile(file), thunkApi)
);
```

Alternatively, you could add [matching utilites](https://redux-toolkit.js.org/api/matching-utilities) **instead of your `showAlert` case**
```js
builder.addMatcher(isRejected, (state, action) => {
  // do whatever `showAlert` would do here
})
```

Or just handle it on a component level, or add a middleware for it.

Or just write it within the code of your asyncThunk - those callbacks would not do anything that could not just be written in there after all.

Bottom line: I don't think something like this would be necessary and there are already lots of other places better suited to handling this. 

I'd even say don't think adding another paradigm to Redux would do this any good, but probably just confuse many people.

**Comment by thaindq** [comment]
Thank you guys. I forgot that `payloadCreator` returns a promise. It should do what I need.

>I don't think something like this would be necessary and there are already lots of other places better suited to handling this.
Yeah I agree. I was just looking to see if there is a better way to achieve it. I just didn't want to do it in reducer because it would separate the logic of my async action.
