### ISSUE TITLE
RTK Query - Missing api for setting query data in advance, using local client data.

### ISSUE THREAD

**Issue by omerman** [reduxjs/redux-toolkit#1414]
Hi again, ( Promise this one should be the last one for now ;) )

I wonder if it is at all possible to have the ability to set the data of a query in advance, with local data that the client already have.

I'll explain,

Say I have a rest "api/dishes/{dishId}/createEmptyDishRecipe" that creates a Recipe object (and attaches it to the Dish object) and returns it.

once this POST request is fulfilled, I will update a query named `getDish` assigning the id to relation field.
```
dispatch(api.util.updateQuery("getDish", dishId, draft => { draft.recipeId = newRecipe.id }))
```

Now, the problem is that I also want to set in advance the data for query `getRecipe` with the newly created Recipe (a moment later the UI will navigate to a new Recipe screen) but since the recipe is new, and no one has ever observed the query `getRecipe` with the new id, `updateQuery` won't do anything, and prefetch is kind of a bummer since it means an extra request for something that I already have in my hand 
```
// This is ignored since the getRecipe query with the args sent was never observed.
dispatch(api.util.updateQuery("getRecipe", newRecipe.id, draft => newRecipe))
```

Is there any available solution for this kind of behavior?

Thanks again.. :)

**Comment by phryneas** [comment]
At the moment only by faking a `fulfilled` action, which I would not recommend.

With 1.7, we will support hydration, so you could use that to pre-set a few api slices, but since it is not the primary purpose of it you will likely have to hack a little bit around with it and "construct" the api cache entries that way.

That is going on, among other things (like suspense), in https://github.com/reduxjs/redux-toolkit/pull/1277 and you can already check out the codesandbox build. Feedback would be highly welcome.

**Comment by omerman** [comment]
Thank you! I'll be sure to take a look at that
