### ISSUE TITLE
[BUG] RTKQ invalidates all prefetched entries instead of the provided tag

### ISSUE THREAD

**Issue by adrianthedev** [reduxjs/redux-toolkit#1417]
👋 Hello,

I think I found a bug.

When using RTKQ with prefetching, when I use a mutation it invalidates all the prefetched records instead of the ones that match the `invalidatesTags` method.

Here's a video 👇 and [a stackblitz](https://stackblitz.com/edit/react-hzm9qy?file=src/App.js) for this scenario.

![5b5c0bfdd79c60a213b85af321e788e9](https://user-images.githubusercontent.com/1334409/129782989-60a4ebde-4670-4b91-b6c2-b4d80f7f1281.gif)

Steps to reproduce with this 👆 stackblitz:
- load the page
- hover over the items and notice them being pre-fetched in the network tab
- click one to select it
- click save to trigger the mutation

Bad behavior (current behavior). After the PUT request triggered by the mutation all the prefetched records get fetched again.

Good behavior (wanted). After the PUT request only the invalidated record gets refreshed again.

Thank you!

**Comment by phryneas** [comment]
Looking at the state in the Redux devtools, all those have an `id` of `undefined`:
![image](https://user-images.githubusercontent.com/4282439/129790202-920a391d-386c-43e3-ab2f-9e12dd4f5f0f.png)

Which makes a lot of sense, because you are defining them as `{ type: 'Record', recordId }`, not `{ type: 'Record', id: recordId }`

**Comment by adrianthedev** [comment]
🤦‍♂️ Yes. Totally makes sense. My bad on assigning the wrong id.

Thanks for the tip with the dev tools.
