### ISSUE TITLE
Simplifyiing Reducers Utility

### ISSUE THREAD

**Issue by Chetan11-dev** [reduxjs/redux-toolkit#1426]
I found a helpful pattern that redux complexity of my application.
One way of updating state in redux is by create many reducers.
```
updateSidebar(),
updateIsEditing()
```

We can write simplify it using a helper utility 

```js
const updatePartially = (state: Object, payload: Object) => {
    Object.keys(payload).forEach((k: string) => {
        state[k] = payload[k]
    })
}
// reducers
updateUi: (state, { payload }: PayloadAction<Partial<ReducerState>>) => {
            updatePartially(state, payload)
},

```
Now above functions become 
```
updateUi({isSidebarOpen:true}),
updateUi({isEditing:true}),
```
This leads less reducers and more idiomatic code in our applications.

**Comment by phryneas** [comment]
Instead of `updatePartially`, you could also use `Object.assign`, but generally we recommend explicitly against having that kind of setter-type actions. https://redux.js.org/style-guide/style-guide/#model-actions-as-events-not-setters

The big strength of Redux is that it helps you move your application logic out of your components and gives you a "readable" log in your DevTools. If you only ever use setter-type actions, your logic usually ends up very entangled with your components and the log in the DevTools loses all meaning.

**Comment by markerikson** [comment]
Yup, I was going to say the same thing.

We do always encourage users to write whatever reducer logic would be useful for your own apps, but yeah, we encourage avoiding ""setter"-style reducer logic if possible.
