### ISSUE TITLE
Allow queries to invalidate tags

### ISSUE THREAD

**Issue by JosNun** [reduxjs/redux-toolkit#1428]
Currently, the `invalidatesTags` property on a query endpoint definition is disallowed in TypeScript:
```ts
// Copied from https://github.com/reduxjs/redux-toolkit/blob/3960bc4ed11e2111843094509d4434fa6abfe3c9/packages/toolkit/src/query/endpointDefinitions.ts#L240-L243
/**
 * Not to be used. A query should not invalidate tags in the cache.
 */
invalidatesTags?: never
```

Typically, that's intuitive and expected behavior. However there are cases where one might want a query to invalidate tags. For my case in particular, I Have a route that logs whenever a user accesses certain data. Since the request that accesses the data is a query, and not a mutation, I have to use a workaround to invalidate the cache of the query that gets the logs.

As a workaround, I've used the onQueryStarted function, but it feels like a bit of a hack, and isn't consistent with the `invalidatesTags` method that mutation endpoints have.

```ts
onQueryStarted: async (args, { dispatch, queryFulfilled }) => {
  await queryFulfilled;
  dispatch(
    api.util.invalidateTags([
      { type: 'AccessLog', id: args.id },
    ])
  );
},
```

That said, I 100% understand if you believe the benefits of preventing cache invalidation outweigh the gains made for this particular edge case.

**Comment by phryneas** [comment]
I would not want to allow that, since the cases for it are so extremely rare. Essentially, from a logical standpoint, your query is not a query, but a mutation - since it does change state on the server that is impacting another query. I get why you write it as a query, but you're walking a very fine line there. I think in such an edge case, your current workaround is better than introducing a "way of doing things" that might lead others into doing stuff that can harm them later on.

**Comment by JosNun** [comment]
Sounds like a wise decision 👍 

Feel free to close this issue if it doesn't need to be discussed more. Thanks for the quick feedback!
