### ISSUE TITLE
LocalStorage bug when rtk query is combined with redux-persist

### ISSUE THREAD

**Issue by kuangshp** [reduxjs/redux-toolkit#1429]
When using rtk query to call the back-end interface and using redux-persist to persist data, it is meaningless to view the LocalStorage data in the browser's application, such as queries, etc., especially when a field of getAccountList(undefined) appears

When using slice to call the back-end interface, the data is clean and easy to use in other components, but the data queried by rtk query in LocalStorage has a lot more unnecessary data. I would like to ask what is the solution to rtk query query The data of is also the same as the data queried using slices. Only the data I want is stored in localStorgage, and there is no such data as getAccountList(undefined).

[Online demo](https://codesandbox.io/s/stupefied-https-qwcrk?file=/src/App.js)

![image](https://user-images.githubusercontent.com/15928680/130314664-1205c773-1ce7-470c-bb15-071a56160992.png)

baseApi uses the result of rtk query query
The result of the user query using slice

**Comment by phryneas** [comment]
It should not be your concern if you as a human think that that data is beautiful, too much, too little or anything else - it is how the data is internally stored and used by RTK Query.
The query cache key of `getAccountList(undefined)` is the result of calling `useGetAccountList()`, which is identical to calling `useGetAccountList(undefined)`.

Generally though, RTK Query is an api cache and you should not ever be persisting any api cache. 
What if your user re-starts the application 2 years later? They will be presented with horribly outdated data. 
If that data should be cached, make sure that your server sets the correct cache headers on them and your **browser** will take care of the caching, meaning that future requests for that data will be served from the browser cache instead of actually causing a request.

**Comment by kuangshp** [comment]
> It should not be your concern if you as a human think that that data is beautiful, too much, too little or anything else - it is how the data is internally stored and used by RTK Query. It is an implementation detail.
> The query cache key of `getAccountList(undefined)` is the result of calling `useGetAccountList()`, which is identical to calling `useGetAccountList(undefined)`.
> 
> Generally though, RTK Query is an api cache and you should not ever be persisting any api cache.
> What if your user re-starts the application 2 years later? They will be presented with horribly outdated data.
> If that data should be cached, make sure that your server sets the correct cache headers on them and your **browser** will take care of the caching, meaning that future requests for that data will be served from the browser cache instead of actually causing a request.

My initial idea was component-based development. In a large project, the data of this interface may need to be used in many pages, because I want to cache it so that it can be used directly in other components. Listen to what you say and combine it with me. With the knowledge of RTK Query, it seems that you understand how to operate. You can query the API directly through RTK Query without reading data from LocalStorage. Thank you

**Comment by phryneas** [comment]
When using Redux, you never should ever read anything from LocalStorage into your component. You should only use LocalStorage to persist and restore the parts of your state that should survive a page close/reopen. (This might be true for user input, or a choice like language or theme selection, but not for cache state.)

But even then you should only restore it directly into your Redux store. 

Your components should ever only read from the Redux Store, not from LocalStorage.
