### ISSUE TITLE
RTKQ: Feature request to keep identity stable

### ISSUE THREAD

**Issue by pserrer1** [reduxjs/redux-toolkit#1482]
I have a feature request for RTKQ.

Would it be possible to keep the identity of returned objects stable in case they didn't changed at all? I.e. by passing an optional compare function.

``` 
import { dequal } from 'dequal';

const api = createApi({
    ...,
    endpoints: (build) => ({
        getData: build.query<Response, number>({
            query: (id) => ({url: `/user/${id}`}),
            compareFn: dequal
        })
    })
});
```

**Comment by phryneas** [comment]
They already do - even if your response changes partially, we keep as much of it a stable reference as possible. If you refresh `useGetData(15)` and only part of it changes, only that part (and all parents containing it) will be a new reference.  
You can see tests for that here: https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/tests/copyWithStructuralSharing.test.ts

Or are you talking about keeping references between different cache values? That's not possible, because `useGetData(15)` and `useGetData(16)` are completely different objects stored independently of each other.

**Comment by pserrer1** [comment]
Hm.. thats strange. We use `refetchOnFocus` to refetch the data if the window gets the focus again and the returned object is each time different - we don't change the argument

**Comment by markerikson** [comment]
Can you post a CodeSandbox that shows this issue happening?

**Comment by pserrer1** [comment]
Sure - I will setup something. Maybe we have something strange going on in our rtk setup.

**Comment by pserrer1** [comment]
Seems, there was an issue on our side and I can't reproduce the issue anymore. Will close the issue
