### ISSUE TITLE
"Style Guide" and "Usage Guide": events vs. actions

### ISSUE THREAD

**Issue by nilshartmann** [reduxjs/redux-toolkit#1551]
Hi,

this might be nitpicking, but in the [Style Guide](https://redux.js.org/style-guide/style-guide#model-actions-as-events-not-setters) you recommend *Model Actions as Events, Not Setters*, but in the Usage Guide, [for example here](https://redux-toolkit.js.org/usage/usage-guide#simplifying-reducers-with-createreducer) the Actions in the sample code are imho looking more like Actions/Setters than Events (note the "orderAdded" example in the Style Guide vs. ADD_TODO in the Usage Guide). For me this seems a little bit contradictory and confusing (even if it might make sense in the concrete use-case of the Usage Guide example).

(On a side note: After re-reading the explanation in the Style Guide, I'm also not 100% sure, if "Model Actions as Events, Not Setters" could be read as "Model Actions as Events or Actions, but Not Setters", so that `{ type: "food/addOrder",  payload: {pizza: 1, coke: 1} }` might also be a valid Action in the sense of your recommendation? 🤔)

Just my 2cents. ✌️

**Comment by markerikson** [comment]
Yeah, the docs are inconsistent in example usage, mostly due to docs pages being written at different times - updating all the docs is a long-term ongoing process.

Generally, the concept is to have an action represent "here's a thing that happened, with some details" rather than "SET SOME SPECIFIC FIELD".  In this case, that might be something like `'food/orderAdded'` rather than `'food/setPizzaAmount'`.

**Comment by phryneas** [comment]
That said, PRs that move it more into that direction are very welcome. We just have a lot of stuff to do pretty much on every front.
