### ISSUE TITLE
isLoading initially false when using selectFromResult

### ISSUE THREAD

**Issue by TamasSzigeti** [reduxjs/redux-toolkit#1586]
Hi,
Firstly, this lib is amazingly awesome and I'm extremely grateful for all the work put into it.

My version is 1.6.2

Now strictly speaking this is not a bug if we read the docs carefully, but it is still a surprise, so I'm wondering if it would be possible to fix it. Worst case I'm just submitting it for awareness if anybody encounters this. 
The doc says selectFromResult can be used to select from a query already included in a parent component, and that actually works as intended. But it _almost_ works without querying anything in a parent as well, the missing bit is the isLoading flag (and I haven't checked but I assume it's true for isFetching too)

With this code, isLoading starts with false, then flips to true, then it correctly flips to false again the same time the data appears:
```
export const useGetSomethingByIdQuery = (somethingId: string) =>
    useGetSomethingsQuery(undefined, {
        selectFromResult: ({ data: somethings, isLoading }) => ({
            something: somethings?.find(
                (something) => something.id === somethingId
            ),
            isLoading,
        }),
    });
```

This however works correctly, isLoading starts with false, but then I can't benefit from the built-in memoisation.
```
export const useGetSomethingByIdQuery = (somethingId: string) => {
    const { data: somethings, isLoading } = useGetSomethingsQuery(undefined);

    return {
        something: somethings?.find(
            (something) => something.id === somethingId
        ),
        isLoading,
    };
};
```

Any chance to support this use case, perhaps?

**Comment by phryneas** [comment]
I think the best thing to do here would be to also take `isUninitialized` into account:

```js
    useGetSomethingsQuery(undefined, {
        selectFromResult: ({ data: somethings, isLoading, isUninitialized }) => ({
            something: somethings?.find(
                (something) => something.id === somethingId
            ),
            isLoading: isLoading || isUninitialized,
        }),
    });
```

**Comment by TamasSzigeti** [comment]
That indeed works, thank you. Shall I submit a doc update or are you considering fixing it?

**Comment by phryneas** [comment]
Well, there is no real "fix" to implement here - I *think*. 

Essentially, this is the default behaviour. 
We do have a little quality-of-life hack in place that if you are using a query without specifying `skip`, it will give you `isLoading` instead of `isUninitialized`, to prevent that you have to check for both - technically that first render will be *before* `isLoading` could start to take place, since that happens in a `useEffect`. 

By using `selectFromResult` you are essentially opting out of all these things and are deciding that you want to do optimizations like that yourself.

If you have a good idea on how document that, it might make a good addition to the docs :thinking:
