### ISSUE TITLE
UpdateQueryData function callback isn't called

### ISSUE THREAD

**Issue by maisterr** [reduxjs/redux-toolkit#1658]
I'm trying to implement an optimistic update function by manually update the cache, here is my code which has some differences from the example in the documentation. First console log inside onQueryStarted works and gets the data, but the callback inside updateQueryData does not work and console.log(patchCollection) return object with patches zero-length array

What is wrong with this and what do I need to pass in the args argument of the updateQueryData function it this case?

```
export const postsApi = createApi({
    reducerPath: 'posts',
    baseQuery: fetchBaseQuery({ baseUrl: BASE_URL }),
    endpoints: (build) => ({
        getPosts: build.query({
            query: () => '/posts',
        }),
        addPost: build.mutation({
            query(body) {
                return {
                    url: `/posts`,
                    method: 'POST',
                    body,
                }
            },
            onQueryStarted(post, { dispatch, queryFulfilled }) {
                console.log('works')
                const patchCollection = dispatch(
                    postsApi.util.updateQueryData('getPosts', undefined, (cachedPosts) => {
                        console.log("won't work")
                        cachedPosts.push(post)
                    }),
                )
                console.log(patchCollection)
                queryFulfilled.catch(patchCollection.undo)
            },
        }),
    }),
})
```

**Comment by tkharuk** [comment]
struggled as well.
In my case, I expect any argument in query builder, but mistakenly passed one arg to hook, thus `updateQueryData` never triggered.

I've read `a cache key, used to determine which cached dataset needs to be updated` multiple times, but it didn't help me much :(

**Comment by phryneas** [comment]
@Shrugsy could you maybe take a look at the docs there? This seems to confuse a lot of people.

**Comment by Huespal** [comment]
I have a doubt related.
How can one know the exact params used in the previous query while on the query trying to apply the updateQueryData?
So, for example, a GET /something exists and is performed with params { number: 1 }.
User continues to navigate and 'number' parameter changes from 1 to 3, to 25, etc.
Lately a POST /something is called with an optimistic update (which uses updateQueryData) over the GET. 
How do I know here, in the PUT, that page is still 1 and not 3, or 25?
And this example is with only one parameter, so it can be a lot more complex. 
I think it will be a lot easier if the params or arguments where skipped to allow the update on data only with the 'getSomething' endpoint name. Now, it complicates things a lot.

Thanks

**Comment by phryneas** [comment]
@Huespal well, the answer that I have been giving about a million times by now would be "we really don't want you to overuse `updateQueryData` and just invalidate and automatically refetch end points in 99.9% of all cases".

You can still do it but should so only in edge cases where you are sure that it brings a big benefit:

You can use `api.util.selectInvalidatedBy(state, tags)` to get an `Array<{ endpointName: string, originalArgs: any, queryCacheKey: string }>` for all endpoints and args that provided that tag. That way you can find those.

**But we still urge you to `invalidate` instead most of the time.**

**Comment by Huespal** [comment]
@phryneas Thank you, I'll try.
I think re-fetch fails over optimistic updates in a lot of cases on the UX side. People doesn't like 'loadings'.
But it is just an opinion. I am very grateful for your work here :)

**Comment by phryneas** [comment]
@Huespal I recently stumbled over this thread that talks about the topic on when optimistic updates don't make sense: https://twitter.com/TkDodo/status/1490623373700997123

Personally, I like to have them just visually inidicated without blocking usage. An update from the server should not take longer than a second. You don't need to disable the full UI with a "loading" indicator. Just gray it out a little bit or show an action indicator somewhere and the UI will be up-to-date within a second. Nobody will mind that. That's also why we have `isLoading` and `isFetching` seperately.

**Comment by Huespal** [comment]
That is very illustrative. Thank you I'll appreciate.
Sorry, to continue with the side doubt, but how can this help with eventual consistency? 
There's a case scenario where application re-fetch but the new created/updated data is not coming yet from server, because it will 'eventually' come from server. 
So the solution here should be to don't stop re-fetching until the data comes (maybe a few seconds in the worse case scenario)?
With optimistic update the data is instantly visible, without worries.

**Comment by phryneas** [comment]
Why will it "eventually" come from the server and why would you need to keep on fetching?

The moment your mutation finishes (the server closes the connection), your server should have the up-to-date data, so every request to the server from then on should give correct results.
And that is the moment that invalidation will cause all potentially impacted queries to make a request and refresh their data.

**Comment by Huespal** [comment]
Well, maybe is something just with our current implementation.

A mutation is performed, and then GET is called for the data refresh. But the data returned from the GET may not be the updated one, because of the way the server is coded, with 'eventual consistency'. Connection from the app to server is closed, sure, but data is still being updated (events working, views projected, etc.) on the server side. So with a quick GET, the data may not be ready yet.
I thought the same as you at the beginning, data should be there, but it is not, with this new paradigm, at least with a very quick data refresh.

So well, sorry to insist. I think this is enough. It may be just our case. 
Thank you.

**Comment by phryneas** [comment]
I'd see that as a conceptual problem with your "eventual consistency" to be honest. 
I mean, when you do the optimistic update it gets even worse: the user updates the data, it seems to be updated to them. Then they refresh the page, get the old data from the server again and lose all faith in your application, thinking something went wrong.  
I'd rather have them see that it takes a while, but if data shows up it really is there. But of course that depends on your app.

**Comment by alpfreda** [comment]
I have this problem too, callback is not work :(

**Comment by phryneas** [comment]
@alpfreda are you calling `updateQueryData` with  the exact same argument as you are calling the hook *and* are you dispatching it? This issue has been solved and was incorrect usage. Have you read through everything?

**Comment by alpfreda** [comment]
@phryneas thanks for replying 
yes it's my fault and this is how I solve my problem.

![image](https://user-images.githubusercontent.com/69018109/155398603-60c17640-ab3d-4b7a-bfaf-0e476f5c4a88.png)

**Comment by McGern** [comment]
Just to add to the "eventual consistency" chat - in my scenario there is a cost associated with each request. So (for example) we do a post or patch for a status update on an item in a list (set as "completed" or something like that) we just receive a "200 OK" response and not any additional data. So rather than do a round trip just to update that one item in the list (and incur a cost with the request), we do a pessimistic update (after the 200 status returns) on the item, with the anticipation that when the cache expires (or whatever scenario is setup to fetch the api again) the data will be the same.

The issue we have is that are a couple of different scenarios to fetch the data (depending on where in the app we are) and this is set with a boolean in this scenario, but it could as easily be a list of filters or paging. So knowing which endpoint we will be updating can be a bit tricky.

Will see if I can get the selectInvalidatedBy utility working.
