### ISSUE TITLE
How to cancel deduping queries?

### ISSUE THREAD

**Issue by LukerSpringtree** [reduxjs/redux-toolkit#1740]
I read the code in  example, the name is 'deduping-queries'.
my question is how can I cancle the deduping-queries?

tank you~

**Comment by phryneas** [comment]
I am not sure what you are referring to exactly and not sure what exactly your use case is either.

**Comment by LukerSpringtree** [comment]
![image](https://user-images.githubusercontent.com/9697295/141703785-cc9852b7-f652-40fa-ae71-5821a0e0204b.png)
This is the demo UI;  In example, every time I click "Add bulbasaur", app can gei me a "pokemon", bug don't request in Network. I know this is "deduping queries" and it's a useful feature.

What I expect is when I add a same pokemon, it can put a new request;  and when I have 5 "bulbasaur", it can make  bulbasaur requests.  

I know, this is a bad phenomenon. bug I want to  know How do I do that?

**Comment by phryneas** [comment]
But these *are* the same request item from the same url. That is the whole reason you use a global request state manager, to keep things in sync. Otherwise, you could be using local application state.

I will need to see a **real use case** where you do not want this and then I can give you an answer what might be the right thing to do in **that situation**.  
I **this situation**, it is the intended thing to happen.

**Comment by LukerSpringtree** [comment]
> But these _are_ the same request item from the same url. That is the whole reason you use a global request state manager, to keep things in sync. Otherwise, you could be using local application state.
> 
> I will need to see a **real use case** where you do not want this and then I can give you an answer what might be the right thing to do in **that situation**. I **this situation**, it is the intended thing to happen.

That was my idea, I do not have a 'real use case';
Anyway, thank you very much.
It was nice communicating with you
