### ISSUE TITLE
Export `createEntityAdapter` and possibly other API methods as their own package?

### ISSUE THREAD

**Issue by wldcordeiro** [reduxjs/redux-toolkit#1745]
Throwing this out here, I love Redux Toolkit and have found it super nice for my apps as I integrate Redux when it's called for. However I have some applications where I would love to use `createEntityAdapter` alone inside react's `useReducer` (well a nice little wrapper lib called `use-methods` that gives you basically `createReducer` in a hook).

I know that the toolkit itself isn't that large but would it hurt to maybe have `createEntityAdapter` or some of the other API exported as their own `@reduxjs/` packages?

**Comment by markerikson** [comment]
Is there a problem with just depending on `@reduxjs/toolkit` and importing it?  RTK should tree-shake (assuming your build setup works right), so anything you don't use will be excluded.

**Comment by wldcordeiro** [comment]
I believe tree-shaking should work just fine. I guess my suggestion comes from the perspective of convincing others and often people ignore tree-shaking and just look at npm dep size. For my particular case right now I've just been convincing my team to pull it in.

**Comment by markerikson** [comment]
Heh, "dep size" is misleading, especially if you're looking at the actual NPM package pages where they show the "size on disk", not "size in a browser".  RTK is like 10MB extracted on disk, because we ship 3 different entry points * 8 or 9 module formats, with sourcemap files for each one.

The _actual_ size in a browser is much much smaller.

I recently found https://bundle.js.org , which does real bundling in your own browser with ESBuild to show you exactly what minified code will be included.  In this case, per https://bundle.js.org/?q=@reduxjs/toolkit&treeshake=[{+createEntityAdapter+}] , importing just `createEntityAdapter` by itself is 18Kmin, 7Kmin+gz.  And that includes Immer.

**Comment by markerikson** [comment]
Closing as I don't think there's anything we should be doing here.
