### ISSUE TITLE
It seems redux-toolkit can't be used in a VS Code extension

### ISSUE THREAD

**Issue by fuzl-llc** [reduxjs/redux-toolkit#1754]
I've got a VS Code extension that is about to get some complicated state management requirements, so I'd love to use redux-toolkit. I start with a working Typescript-based VS Code extension. I then "npm install @reduxjs/toolkit" and try to debug the extension but get an error when the typescript compiler runs:

Cannot find name 'AbortSignal'. ts(2304).

When I go to view the error, it is in .\node_modules\@reduxjs\toolkit\dist\createAsyncThunk.d.ts on line 11 (signal: AbortSignal). I'm pretty new to both Typescript and Redux, but from what I've been able to find, this has to do with there being no accessible type definition for this AbortSignal type. It also seems that this is a type that is defined by a "DOM" library which has browser-related types. VS Code isn't a browser so I'm wondering if that is why the AbortSignal type is missing and if redux is somehow tied to this library and being in a browser runtime environment... but that seems like it can't be the case since redux is a node.js thing and of course we can run node.js outside of the browser. But it does seem strange that we seem to have a DOM-related dependency when we may operate in environments that have no DOM. I can put this line of code in that file, above the BaseThunkAPI declaration:

type AbortSignal = undefined;

The compile error goes away, my VS Code extension runs, and I can use the basic redux API (create store, subscribe, dispatch, etc.) but clearly this is not a real solution. Even though the basics work, this seems terrible, even for a temporary fix, especially since I'm probably going to need that "thunk" stuff pretty soon. I've tried to install the DOM library (but it didn't help - I assume since it is redux-toolkit itself that needs to reference it?). I've also found articles talking about referencing the DOM library "externally" somehow but haven't been able to get anywhere with that yet.

Is this a bug/flaw or am I just misunderstanding something? Is there a better fix for this issue? Should redux be able to be used in non-browser environments like a VS Code extension?

**Comment by phryneas** [comment]
It should be, and on a JS level it checks if `AbortSignal` is there and otherwise polyfills it - you just have hit a weird edge case where is is not there as a TypeScript type.

Writing
```ts
declare global {
  interface AbortSignal {}
}
```
anywhere in your code or adding a polyfill for AbortSignal (libraries like node-fetch etc. all bring one, which is probably why you are the first person to report this) should probably fix that.

Or, you just set `skipLibChecks` in your `tsconfig.json`, which will also improve your compilation time by a lot.

**Comment by fuzl-llc** [comment]
Thanks so much @phryneas! Declaring the global interface does solve the problem. However, it still feels very weird. I come from 20+ years of working with compiled, statically typed languages so this idea that my app has a reference to a library, that library has a missing definition/dependency, and I can fix it by just declaring an empty global interface is mildly disturbing to me. Like, how can the thunk code possibly work if I've declared an empty interface and it expects something else? I guess this is compile time Typescript and that is runtime Javascript... I'm going to keep reading/learning but in the meantime (and for future people who may come across this question) perhaps you can indulge with thoughts on these followups:

1. In the Javascript/Typescript world, is this an acceptable, real, and good long term solution or is this something that may have a more proper solution (i.e. by including this or another solution directly in the toolkit instead of relying on users happening to use another library that does a polyfill)?

2. With this solution, will I be able to properly use the BaseThunkAPI type in the future?

**Comment by markerikson** [comment]
This is perfectly normal TypeScript usage.

TS only knows as much about the environment and available types as you tell it.  It will also believe whatever you tell it, types-wise. If I load a runtime JS script that adds `window.meaningOfLife = 42` to the global scope, TS has no way of knowing that variable exists until I add some kind of type declaration to let it know that, because compile-time types are completely separate from runtime code behavior.  Conversely, if I tell TS that my API response looks like `{a: 'blah'}`, but instead the server sends back `{b: 42}`, TS will believe me and happily let me do `res.toLowerCase()`.  That will compile fine because it's a valid function to call on a string, but blow up at runtime because the field doesn't exist.

So, yes, adding additional type declarations to match the expected runtime environment of your code is how TS is expected to work.  Really, you could think of _all_ JS library TS typedefs as doing the exact same thing.

**Comment by phryneas** [comment]
Adding to this: RTK tries to find out if `AbortController` is there - and if it is not, it just fills in a non-functional dummy. In that case, you will not be able to use abort controllers - but if you want to do that, you can just load a polyfill in any environment.

Now, as a result from that our types are *referencing* AbortController and TS tries to find that too - and we cannot tell it that it's optional. So it is perfectly safe to either disable type checks for your `node_modules` (which I would *really* recommend as a lot of time and CPU is being spent there, revalidating types that are successfully shipped to millions of users) or add that little global declaration showed you earlier.

**Comment by fuzl-llc** [comment]
Thanks for weighing in @markerikson. I've just finished reading/watching some of your docs/videos and am totally inspired to get deeper into this. Thanks also @phryneas for the additional details. I'd sort of poo-pooed the idea of disabling type checks since my C# brain was telling me there was something wrong with it... but now realizing I'm only doing it for other people's code under node_modules which, as you say, is pretty safe to assume is "good," it does feel like that is the best solution. Thanks!

**Comment by fuzl-llc** [comment]
Ok, thanks @markerikson. I'm happily moving along at this point but can't resist one more... Having read and understood all the above as best I can at this point, I noticed you closed this issue which I take to mean no further action is planned. Is there any reason RTK shouldn't just put a definition for this AbortSignal type into its own code so that anyone (especially Typescript novices) won't run into this issue in the future? Or is that not appropriate for some reason (like it might then conflict with other definitions that are there in most common scenarios)?

**Comment by markerikson** [comment]
It's generally not a good idea for libraries to override global type behavior, in the same way the JS community has learned that it's a bad idea to mutate global prototypes like `Array` or `Object` :)

**Comment by fuzl-llc** [comment]
Makes sense. Well, at least now we have the above as a resource for anyone else who gets stuck on this. Thanks for taking the time.
