### ISSUE TITLE
[react]  Support for generic createApi type

### ISSUE THREAD

**Issue by jayjnu** [reduxjs/redux-toolkit#1756]
# version
- "@reduxjs/toolkit": "^1.6.2",

# Issues

Hello, I'm currently writing a ui framework agnostic library using redux-toolkit as core state management solution.

Currently, it seems impossible to decouple my core from any react related dependencies if I want to use auto-generated hooks and its typings of `@reduxjs/toolkit/query/react`

here are the libraries i am writing
- my-lib-core: provide abstractions for api fetching, state management  (no dependency to any ui libraries)
- my-lib-react: wrap `my-lib-core` with react api
- my-lib-vue: wrap `my-lib-core` with vue api
- etc..

if i create `Api` with `createApi` exported from `@reduxjs/toolkit/query`. i have to manually write all api hooks.

To avoid inventing the wheels, I searched documentations and official type declarations, but no luck

# Details

## Dependency Injection using Generic types

I am experimenting with generic createApi like this

```tsx
import  {CreateApi} from '@reduxjs/toolkit/query';

const createMyApi = <T>(createApi: CreateApi<T>) => {
  return createApi({...});
}
```

but it fails because `CreateApi` types requires `unique symbol`

So i did this:

**`core/api.ts`**
```tsx
// not officially supported type
import type {ModuleName} from '@reduxjs/toolkit/dist/query/apiTypes';
import  {CreateApi} from '@reduxjs/toolkit/query';

const createMyApi = <T extends ModuleName>(createApi: CreateApi<T>) => {
  return createApi({...});
};
```

**`react/api.ts`**
```tsx
import {createMyApi} from 'core/api';
import {
  buildCreateApi,
  coreModule,
  reactHooksModule,
} from '@reduxjs/toolkit/query/react';
import {useStore} from './hooks/useStore';
import {useDispatch} from './hooks/useDispatch';
import {useSelector} from './hooks/useSelector';

const customCreateApi = buildCreateApi(
  coreModule(),
  reactHooksModule({
    useDispatch,
    useSelector,
    useStore,
  }),
);

const api = createMyApi(customCreateApi);
```

this works, but uses unofficial types.

## Official api converter

i think it would be better if a converting helper was provided.

```
import {createApi} from '@reduxjs/toolkit/query';
import {withHooksHelper} from '@reduxjs/toolkit/query/react';

const api  = createApi({...});

const apiWithHooks = withHooksHelper(api);
```

**Comment by markerikson** [comment]
I'm sorry, is there an actual question here?

**Comment by jayjnu** [comment]
@markerikson 
sorry i accidentally posted. I updated original posting

**Comment by markerikson** [comment]
Hmm. So now I'm confused in a different way :)  You say you're building a UI-agnostic library, but you "want to use auto-generated hooks and its typings of `@reduxjs/toolkit/query/react`".

How does that go together?

FWIW, the `@reduxjs/toolkit/query` portion _is_ the UI-agnostic implementation of RTK Query.  That's why https://github.com/SaulMoro/ngrx-rtk-query can use RTKQ with NgRx, https://github.com/wobsoriano/vue-rtk-query with Vue, and https://redux-toolkit.js.org/rtk-query/usage/examples#svelte with Svelte.

Can you clarify what specific tasks you're trying to accomplish here and what the blockers are?

**Comment by jayjnu** [comment]
Sorry for confusion.

To clarify, the UI-agnostric  library i metioned only appiles to the `my-lib-core`

- api slice is defined in `my-lib-core` using `@reduxjs/toolkit/query` (this is UI-agnostic library)
- `my-lib-react` should extend api slice of `my-lib-core` to provide api hooks as public interface
- once an api slice is created by `createApi` of `@reduxjs/toolkit/query`, i have to implement all api as react hooks manually, which I want to avoid
- I think it would be helpful if official support for api conversion helper is natively supported by `@reduxjs/toolkit/query/react` because it already implements hooks builder internally

**Comment by markerikson** [comment]
I'm still not understanding what an "API conversion helper" is, or what "hooks" you're trying to implement here.  Can you give examples?

**Comment by jayjnu** [comment]
`my-lib-core`

**`api.ts`**

```tsx
import {createApi} from '@reduxjs/toolkit/query';

export  const api = createApi({
    reducerPath: 'kissApi',
    baseQuery: baseFetchQuery,
    endpoints: (build) => {
      return {
         getUser: build.query({...})
      }
    },
});
```

**`main.ts`**

```tsx
import {configureStore} from '@reduxjs/toolkit';
import {api} from './api';

// api is injected because i want to use extended api implementation for react   
const  createCore = <T extends typeof api>(api: T) => {
  // store is created internally
  const store = configureStore({
    // ...
    middleware: (getDefaultMiddleware) => {
      return getDefaultMiddleware().concat(api)
    }
  })
}
```

`my-lib-react`

```tsx
import {api, createCore} from 'my-lib-core';

const core = createCore(api);

const useUser = () => {
  return api.endpoints.useGetUser() // TypeError because api is created by `@reduxjs/toolkit/query`, not `@reduxjs/toolkit/query/react`,
}
```

This is what I asked for

**reactApi.ts**
```typescript
import {api} from 'my-lib-core';
// hopefully
import {convertApi} from '@reduxjs/toolkit/query/react';

export const reactApi = convertApi(api);
```

**Main.tsx**
```typescript
import {createCore} from 'my-lib-core';
import {reactApi} from './reactApi';

const core = createCore(reactApi);

const useUser = () => {
  return core.endpoints.useGetUser() //  valid type
}
```

**Comment by phryneas** [comment]
A `convertApi` is not in the books - the `react` module really is part of the api **creation** process and does not just get slapped on top - it really hooks into the whole thing.

We haven't really had a use case like that before :thinking: I think you might have found one of the better possibl solutions here.

**Comment by markerikson** [comment]
I'm honestly still not getting what the "conversion" step is supposed to _do_ here.  Is it supposed to be something like "given this custom API instance, generate React hooks based on that"?

Beyond that, what exactly are you customizing with the API generation in the first place?

**Comment by kasparkallas** [comment]
To add to the discussion, I'm also building a UI-agnostic core API package using RTK-Query, i.e. it's a slice published to NPM that consumers will plug into their Redux store.

So I don't want to include React hooks in the core library but I also don't want to give up this amazing feature. I also want to include the upcoming SSR/redux-persist support without actually including those packages in the core.

I hope it makes sense. In a nut shell, I want all the power of RTK-Query but in a completely compatible and agnostic manner. :)

A issue arises from the fact that `createApi` is not a callback* and creates a concrete object which means that I have to choose `@reduxjs/toolkit/dist/query` or `@reduxjs/toolkit/dist/query/react` at the time of creation. The same applies for `injectEndpoints` 
 which I've used to organize the code.

* By "callback" I mean exporting a function to create the slice instead of actually creating the slice and exporting it.

My current strategy is to make creation of the core API slice a callback (similar to OP) which takes `createApi` as input so the consumers decide whether they want the hooks or not. Also the callback will have extension point to include SSR/redux-persist support as well.

Currently working on it. No question here -- just sharing my experience and the way I'm using RTK-Query.

**Comment by kasparkallas** [comment]
I put together an example here: https://codesandbox.io/s/rtk-query-optional-createapi-persistance-grd4k?file=/src/App.tsx

## Relevant snippets

### Exporting a function instead of creating the API. Code-splitting with the function.
* This type of code-splitting doesn't support tree-shaking for the endpoints (as opposed to `injectEndpoints`).
```ts
export const createPokemonApi = <T extends ModuleName>(
  createApi: CreateApi<T>
) =>
  createApi({
    baseQuery: fetchBaseQuery({ baseUrl: "https://pokeapi.co/api/v2/" }),
    tagTypes: [],
    endpoints: (builder) => ({
      ...addGetPokemonByNameEndpoint(builder),
      ...addGetGreetingEndpoint(builder)
    })
  });
```

### Code-splitted "endpoint builder".
```ts
import { PokemonEndpointBuilder } from "./pokemon";

export const addGetPokemonByNameEndpoint = (
  builder: PokemonEndpointBuilder
) => ({
  getPokemonByName: builder.query<any, string>({
    query: (name: string) => `pokemon/${name}`
  })
});
```

### Consumer creating the API and deciding whether to include React Hooks or persistance.
```ts
import { createApi } from "@reduxjs/toolkit/query/react"; // `createApi` with hooks
// import { createApi } from "@reduxjs/toolkit/query"; // `createApi` without hooks

import { createPokemonApi } from "./pokemon";
import { REHYDRATE } from "redux-persist";

// Imagine this is the consumer creating the API:
// They might want React hooks or they might not... They might want SSR/persistance or they might not...
// Here they can configure it.
export const pokemonApi = createPokemonApi((options) =>
  createApi({
    ...options,
    extractRehydrationInfo(action, { reducerPath }) {
      if (action.type === REHYDRATE) {
        return action.payload[reducerPath];
      }
    }
  })
);

// Hook export only works with "@reduxjs/toolkit/query/react"
export const { useGetPokemonByNameQuery, useGetGreetingQuery } = pokemonApi;

```

**Comment by kasparkallas** [comment]
> I'm honestly still not getting what the "conversion" step is supposed to _do_ here. Is it supposed to be something like "given this custom API instance, generate React hooks based on that"?

In case of a library wrapping RTK-Query, I want the consumer to pass in either "create with hooks" or "create without hooks"; maybe "create with Vue hooks" in the future? If you don't make this optional and always generate React hooks then it creates a non-optional dependency.

> Beyond that, what exactly are you customizing with the API generation in the first place?

Nowadays support for `redux-persist` and `next-redux-wrapper` and whatever is added in the future. No?

Currently, the simple API creation function for the consumer `const createCustomApi<T extends ModuleName>(createApi: CreateApi<T>)` does not seem to work well with `import { createApi as createApiWithoutReactHooks } from "@reduxjs/toolkit/query"` because of the `unique symbol` error: 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/10894666/145835487-f8d434d3-e06e-4e36-98c7-dc2afa52d62b.png">
`import { createApi as createApiWithHooks } from "@reduxjs/toolkit/query/react";` does not share this problem.

**Comment by markerikson** [comment]
I'm going to close this because we don't have any plans to make specific changes in this direction, and tbh I'm not sure what changes we _could_ make.

To be clear, this is not a "we will _never_ add anything like this" - it's more of a "we don't have time to investigate this ourselves" thing.

If anyone can actually put together a PR that improves this behavior, we can definitely take a look.
