### ISSUE TITLE
(TS definitions) `error` and `meta` should be optional in `prepare` function

### ISSUE THREAD

**Issue by kesupile-kesupile** [reduxjs/redux-toolkit#1791]
# Summary

When using TS it would be preferable if I didn't **have** to provide a `meta` and `error` key to the return value of the prepare function.

# Steps to reproduce

In TS in strict mode, create a `redcuer.ts` file with the following content:

```ts
const slice = createSlice({
  name: 'foo',
  initialState: {
    test: true,
  },
  reducers: {
    testReducer: {
      prepare: (foo, payload) => ({ payload, meta: { foo } }), // <- TS error here 😞 
      reducer: (state, action) => {
        state.test = false;
      },
    },
  },
});
```

This causes a TS error because `error` is not defined. This can be resolved by doing the following:

```ts
prepare: (foo, payload) => ({ payload, meta: { foo }, error: undefined }),
```

However that solution is cumbersome and creates unnecessary noise in the file.

If there is a simple way to resolve this issue without having to do any declaration merging, please advise.

**Comment by markerikson** [comment]
I'm rather confused. `meta` and `error` are both optional, and the TS types _should_ reflect that:

https://github.com/reduxjs/redux-toolkit/blob/09939c1d95a6cca91966d46757de3e5353a7cf1f/packages/toolkit/src/createAction.ts#L47-L51

Can you post a CodeSandbox that shows this error happening?

**Comment by kesupile-kesupile** [comment]
Sure. I've created one here: https://stackblitz.com/edit/typescript-xmfw1p?devtoolsheight=33&file=index.ts

**Comment by markerikson** [comment]
@kesupile-kesupile I think the first issue here is that you haven't provided any types for either `prepare` or the `action` in the reducer. Does this still happen if you actually type all the arguments?

**Comment by kesupile-kesupile** [comment]
> @kesupile-kesupile I think the first issue here is that you haven't provided any types for either `prepare` or the `action` in the reducer. Does this still happen if you actually type all the arguments?

Could you send a snippet of how you'd modify the code I sent you? I was under the impression that the types would just be inferred and I didn't need to explicitly type everything.

**Comment by markerikson** [comment]
No, it's actually the exact opposite :)  You _must_ provide types for the arguments to `prepare`, otherwise TS (and RTK) have no idea what the resulting field types are.  Because there are no types provided for the arguments, TS is getting confused which of the possible return field structures should match, and that's why you're seeing the "have to include `error`" result.

tbh I'm still slightly hazy on whether you have to include an explicit `action: PayloadAction<x, y, z>` type when you use `prepare`, but yeah, at a minimum you _must_ provide types for `prepare`'s arguments.

**Comment by kesupile-kesupile** [comment]
I'm not sure how providing the arguments would help TS decide which `prepare` function to use, given that all them have the same signature for args(`(...args: any[])`). 

I've forked an example in which I explicitly type everything, but the issue persists: https://stackblitz.com/edit/typescript-ddsga1?file=index.ts

**Comment by markerikson** [comment]
TS also matches on the return type of the function, not just the arguments.

Additionally, the `prepare` callback doesn't include `type` in its return value - just `{payload?, meta?, error?}`.

This looks like it should work correctly:

```ts
const slice = createSlice({
  name: 'foo',
  initialState,
  reducers: {
    testReducer: {
      prepare: (foo: string, payload: number) => {
        return {
          payload,
          meta: { foo },
        };
      },
      reducer: (
        state,
        action: PayloadAction<number, string, { foo: string }>
      ) => {
        state.test = false;
      },
    },
  },
});
```

**Comment by kesupile-kesupile** [comment]
I see so I need to type reducer, not the prepare. Thanks for the help! Feel free to close the issue.

**Comment by markerikson** [comment]
To be clear: **you need to type _both_ functions correctly!**

You have to type `prepare` because the action creator will take its list of argument types from the arguments of the `prepare` function.

You also need to type `action: PayloadAction<payload, type, meta, error>` as well to match how you're returning things from `prepare`.  (I _think_ you may be able to skip that if your prepare function is only returning `payload`.)
