### ISSUE TITLE
Using updateMany in adapter with custom sortComparer ignores several updates with same id 

### ISSUE THREAD

**Issue by karlsoderback** [reduxjs/redux-toolkit#1853]
When I use updateMany in an adapter with a custom sortComparer, I only see effects of the first update when sending several with the same id. See reproducer [here](https://codesandbox.io/s/exehh?file=/src/App.tsx).

**Comment by karlsoderback** [comment]
I also tried a more simple sortComparer: `sortComparer: (a, b) => (a.id > b.id ? 1 : -1)`
The same issue was experienced with that one as well. The only way I have managed to mitigate the behavior is by having no sortComparer at all.

**Comment by markerikson** [comment]
Yeah, I think I see what's happening here.

The update logic for processing `updateMany` is different between "sorted" and "unsorted".

Here's the logic for "sorted":

https://github.com/reduxjs/redux-toolkit/blob/3b8d7a93609650b2402164f1c2f8c17b585d8bb0/packages/toolkit/src/entities/sorted_state_adapter.ts#L75-L97

and here's the logic for "unsorted":

https://github.com/reduxjs/redux-toolkit/blob/3b8d7a93609650b2402164f1c2f8c17b585d8bb0/packages/toolkit/src/entities/unsorted_state_adapter.ts#L125-L151

The unsorted logic continues to merge together the results for each ID.  But, for sorted items, the first time we see an update for a given ID we remove the item from `state.entities`.  When the second update gets processed, the `if (!(update.id in state.entities))` check fails and so we skip applying that update.

I'll be honest and say I don't know why the logic is actually organized like this in the first place :)  I copy-pasted the structure from `@ngrx/entity`.

At a minimum, the sorted logic ought to do something similar to what the unsorted logic is doing, or maybe group all updates by ID first.  It would be _really_ nice if we could consolidate on a single implementation instead of having this split.

I'm afraid this is somewhat lower priority for me atm, but this _is_ a real thing that ought to get fixed.

**Comment by jakeboone02** [comment]
@markerikson I'm going to try to address this by merging the sorted/unsorted logic into a single implementation. It doesn't initially appear to make sense to leave them separate.

**Comment by markerikson** [comment]
Yeah, tbh I don't know why the NgRx folks did it that way to begin with either :)  Might want to double-check the early PRs that added the entity adapter code to NgRx in the first place and see if there's hints why they did that?

I'm totally fine with rearranging / merging the logic in any way that A) keeps the existing tests working, and B) simplifies the implementation.  (smaller bundle size would be nice!)

**Comment by markerikson** [comment]
This should actually be fixed now in #2464 and will be out in whatever the next patch or minor release is.
