### ISSUE TITLE
A case where `action` is not typed correctly when using addMatcher 

### ISSUE THREAD

**Issue by srmagura** [reduxjs/redux-toolkit#1861]
This is not a serious issue, but it can cause type safety issues if you are not paying attention. Feel free to close if you think it is trivial.

Minimal repro: https://github.com/srmagura/rtk-add-matcher-repro

Code:

```ts
import { createAction, createReducer } from "@reduxjs/toolkit";

interface SpecialAction {
  // Uncomment the next line, and then `action` will be typed correctly
  // type: string;
  payload: number;
}

function isSpecialAction(action: any): action is SpecialAction {
  return action.type.startsWith("special/");
}

const myReducer = createReducer(0, (builder) => {
  builder.addMatcher(isSpecialAction, (state, action) => {
    // Hover over `action` to see that its type is `AnyAction`, not `SpecialAction`
    return action.payload;
  });
});
```

**Comment by phryneas** [comment]
Hmm yeah, because the type of the type guard does not contain a `type` field the overload does not work. We should probably widen the requirement there a bit to all type guards, not just specific ones. 
Good catch!

I'll mark this as help wanted & good first issue since I myself won't be able to get to this before the middle of january - maybe someone can already take over :)

**Comment by markerikson** [comment]
Should be out in 1.7.2, I think.
