### ISSUE TITLE
Redux store and Redux-Toolkit store

### ISSUE THREAD

**Issue by w1redl4in** [reduxjs/redux-toolkit#1908]
It is possible to use both redux store and redux toolkit store at the same project? or any workaround
```
import reduxStore from './store';
import rtkStore from './rtkStore';
import { Provider } from 'react-redux';

export const App = () => {
  return (
    <Provider store={reduxStore}>
      <Provider store={rtkStore}>
        <...Application />
      </Provider>
    </Provider>
  )
}
```

I have a legacy code using old redux pattern but willing to migrate to RTK + RTK-Query. Theres alot of actions/types/reducers/sagas that makes change difficult

**Comment by phryneas** [comment]
A "Redux Toolkit Store" is really just a Redux store. There is nothing special about it.

You can add reducers created with `createSlice` to a store created with `createStore` and the other way round (this is our recommendation!) add all your old reducers to a store with `configureStore`. You should not have two stores, ever.

**Comment by w1redl4in** [comment]
> 
So just to get things straight, if we move all the old reducers to the new `configureStore` both slices from RTK and old reducers will work? old reducers that are binded with actions and sagas

**Comment by markerikson** [comment]
Yep!

Also see https://redux.js.org/tutorials/fundamentals/part-8-modern-redux as an example of migrating existing "hand-written" Redux logic to use RTK.

**Comment by rnowak8** [comment]
That's great but there is one more case, I think it's very common. I have a legacy reducer with several actions. Could I add a new action to that specific reducer with a Redux Toolkit without migrating all existing actions to RTK?

**Comment by phryneas** [comment]
You can use `createAction` to write new action creators "RTK-Style", but generally when you are touching a reducer, it would be most advisable to convert it to `createSlice` at that point.

**Comment by rnowak8** [comment]
@phryneas Sorry, I meant new handler for new action, not action. Something like a new 'case' in legacy reducer, but I want it in RTK.

For example, I have that (legacy Redux):

```
function todosReducer(state = [], action) {
  switch (action.type) {
    case 'ADD_TODO': {
      return state.concat(action.payload)
    }
    default:
      return state
  }
}
```

and I want to add REMOVE_TODO, via RTK. Is that possible?

**Comment by phryneas** [comment]
```js
export const removeTodo = createAction('todos/remove')

function todosReducer(state = [], action) {
  switch (action.type) {
    case 'ADD_TODO': {
      return state.concat(action.payload)
    }
    case removeTodo.type: {
      // ...
    }
    default:
      return state
  }
}
```

**But at that point I would really not do that.** If you touch the file, change it to a `createSlice`.

const todosSlice = createSlice({
  name: "todos",
  reducers: {
    // new reducer goes here
    removeTodo(state, action) { 
      // ...
    },
   extraReducers(builder) {
    // old cases go here until you get around to refactor them
    builder.addCase('ADD_TODO', (state, action) => {
      return state.concat(action.payload)
    })
    }
  }
})

**Comment by rnowak8** [comment]
@phryneas Yeah but this way we're still not using RTK (with Immer) for the new handler body (in your first code example). And (for the second code) we need to make some code changes to legacy reducer code (which is taking time). I guess there is no quick way to do that. 

The problem is that migrating the entire legacy reducer is taking a lot of time but writing new handlers in a legacy way (without Immer) is making this time longer in the future. Would be great to have some possibility to merge legacy reducer with RTK Reducer I think.

**Comment by phryneas** [comment]
You can do that too, but I really would not do that.

Honestly, moving cases into `extraReducers` of a slice is a purely mechanical action. You add all the cases and just copy-paste them into the `extraReducers` without  any changes to the case logic. If your code is very consistend, you can even use a codemod for that. Otherwise, use editor snippet templates or just copy/paste. 
Either way, you should be able to migrate a reducer with 20-30 cases in under 10 minutes. That's not a big investment.

Having that migrated over you have the possibility to in the future change some of those reducers over to mutable immerized logic, which might greatly simplify working with them.

But if you insist on it:
```js
const todosSlice = createSlice({
  name: "todos",
  reducers: {
    // new reducer goes here
    removeTodo(state, action) { 
      // ...
    },
  },
  extraReducers(builder) {
    builder.addDefaultCase(yourOldReducer)
  }
})
```

**Comment by rnowak8** [comment]
@phryneas I totally agree with you about refactoring. With typescript, it's taking much more time, unfortunately. I will try your solution. Great thanks for your help.

**Comment by phryneas** [comment]
This is the difference for TypeScript:

```diff
const todosSlice = createSlice({
  name: "todos",
  initialState,
  reducers: {
    // new reducer goes here
-    removeTodo(state, action) { 
+    removeTodo(state, action: PayloadAction<PayloadType>) { 
      // ...
    },
  },
  extraReducers(builder) {
    // old cases go here until you get around to refactor them
-    builder.addCase('ADD_TODO', (state, action) => {
+   builder.addCase('ADD_TODO', (state, action: YourExistingActionType) => {
      return state.concat(action.payload)
    })
  }
})
```

to be honest, I don't see anything that "would take longer" here.
