### ISSUE TITLE
Typescript errors with Yarn PNP

### ISSUE THREAD

**Issue by DavidJFowler** [reduxjs/redux-toolkit#1919]
I created a new project with 
yarn create react-app my-app --template redux-typescript

I then migrated to Yarn 2 PNP following these [instructions](https://yarnpkg.com/getting-started/migration)

In VSCode I get these errors:
![Screenshot 2022-01-14 152629](https://user-images.githubusercontent.com/10775668/149540597-100373f4-86a2-44b2-9ec8-c52e3137651b.png)
![Screenshot 2022-01-14 152802](https://user-images.githubusercontent.com/10775668/149540800-cf5be774-3a84-4b91-bf65-f47ce37fa694.png)
)

Steps to reproduce:

```powershell
yarn create react-app my-app --template redux-typescript
yarn set version berry
```
add `nodeLinker: pnp` to .yarnrc.yml
```powershell
yarn install
yarn dlx @yarnpkg/sdks vscode
```

**Comment by phryneas** [comment]
You will likely have to change the used TypeScript version to the berry-patched one.

Generally, this has nothing to do with Redux Toolkit - you will probably get the exact same problems with any other package you are installing until your dev environment is 100% set up for yarn berry.

**Comment by DavidJFowler** [comment]
> You will likely have to change the used TypeScript version to the berry-patched one.
> 
> Generally, this has nothing to do with Redux Toolkit - you will probably get the exact same problems with any other package you are installing until your dev environment is 100% set up for yarn berry.

Sorry, I don't understand what you mean by this, please could you explain in a bit more detail?

Many thanks.

**Comment by markerikson** [comment]
@DavidJFowler just to expand on this a bit further:

Yarn PnP works radically differently than how NPM and Yarn normally work.  The standard installation approach is to extract all NPM `.tgz` files onto disk in `node_modules`. Then, Node looks for files in `node_modules/some-package/`.

Yarn PnP changes that by keeping all the packages zipped in their original `.tgz` files. But, that means that when Node tries to look for, say, `node_modules/typescript/index.js`, there is no file to open.

Yarn has to take over ownership of all file reads, so that it can intercept the request for `node_modules/typescript/index.js`, and instead open up `.yarn/cache/typescript-4.4.4.tgz` and extract `index.js` into memory.

Most applications don't know how to handle this at all. So, Yarn has to provide compatibility layers to redirect their file open requests so that Yarn can do that work instead.

In particular, TS itself doesn't support that change. Yarn has to maintain a set of custom patches for TS to make it work correctly.

So what you're seeing here is that VS Code + TS have not been patched and overridden to work with Yarn PnP, and therefore TS can't find _any_ type definitions at all (not just RTK).

**Comment by phryneas** [comment]
Well, by the instructions they patched that, but probably forgot to change the used TS version
![grafik](https://user-images.githubusercontent.com/4282439/149561887-c10d6f2c-6866-4a0a-b89c-2af94d32afbc.png)
