### ISSUE TITLE
How can we intercept APIs using RTK-query createApi ?

### ISSUE THREAD

**Issue by arpitjain-in** [reduxjs/redux-toolkit#1955]
Just like Axios provide facility to intercept API at the time of `request` and `response`, in same way how can we intercept using RTK-Query createApi?

**Comment by phryneas** [comment]
You just write a wrapper around the `baseQuery` function. You don't need an interceptor or any extra magic construct for that, it's just code that runs before or after the real `baseQuery` would be called.
Here's an example: https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

**Comment by yash-vaddi** [comment]
> You just write a wrapper around the `baseQuery` function. You don't need an interceptor or any extra magic construct for that, it's just code that runs before or after the real `baseQuery` would be called. Here's an example: https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

**Comment by nk11dev** [comment]
> You just write a wrapper around the `baseQuery` function. You don't need an interceptor or any extra magic construct for that, it's just code that runs before or after the real `baseQuery` would be called. Here's an example: https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

Thank you for your answer! Can you please help me with advice?

I am facing the problem with default `fulfilled` status instead of `rejected` using `fetchBaseQuery`. I described the problem in issue https://github.com/reduxjs/redux-toolkit/issues/3630 

I used custom axios base query before and liked how it works, but now decided to try `fetchBaseQuery` and this different behavior with `rejected` status. 

Is there some `global` way of setting the `rejected` status in base query using `fetchBaseQuery`?

**Comment by hesenv07** [comment]
// src/api/baseApi.js

import { createApi } from 'rdk-query';
import axiosInstance from './axiosInstance';

const baseApi = createApi({
  baseQuery: async ({ url, method, data, params }) => {
    try {
      const result = await axiosInstance({
        url,
        method,
        data,
        params,
      });
      return { data: result.data };
    } catch (axiosError) {
      let err = axiosError;
      if (axiosError.response) {
        err = {
          status: axiosError.response.status,
          data: axiosError.response.data,
        };
      }
      return {
        error: err,
      };
    }
  },
  endpoints: (builder) => ({
    // Endpoints here
  }),
});

export default baseApi;

**Comment by MarcosJBM** [comment]
> You just write a wrapper around the `baseQuery` function. You don't need an interceptor or any extra magic construct for that, it's just code that runs before or after the real `baseQuery` would be called. Here's an example: https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#automatic-re-authorization-by-extending-fetchbasequery

In the documentation we have an example, but the problem is that all **my** requests already have a [**dynamicBaseQuery**](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#constructing-a-dynamic-base-url-using-redux-state), responsible for returning a dynamic base query that I need to use in all my requests, the refresh token example in the documentation, executes the request to check if it returned 401, and returns the result of the request, and we cannot do this in dynamicBaseQuery, after all, it returns a custom base query function, and we cannot execute the refresh token logic and still return the base query, because it duplicates requests, with that, I do not know how I can proceed with this problem, I could not think of anything, besides implementing the refresh logic for each request manually.

**Comment by phryneas** [comment]
@MarcosJBM you can wrap a base query in a function to get a new base query, and you can wrap that in another function to get an even newer base query. You can repeat that any amount of times you want, and in any order that makes sense to you - or write additional logic in your original wrapped base query.
There is no perfect prefabricated recipe for each use case, you'll have to come up with your individual solution for your individual problem.
