### ISSUE TITLE
Specifying responseType

### ISSUE THREAD

**Issue by wkigenyi** [reduxjs/redux-toolkit#1993]
Is there a way to specify responseType on a given endpoint?

**Comment by phryneas** [comment]
You can either provide a [responseHandler](https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#parsing-a-Response) or write completely your own code by using [queryFn](https://redux-toolkit.js.org/rtk-query/api/createApi#queryfn) instead of [query](https://redux-toolkit.js.org/rtk-query/api/createApi#query)
