### ISSUE TITLE
RTK Query support for Hypermedia APIs

### ISSUE THREAD

**Issue by sazzer** [reduxjs/redux-toolkit#2021]
Hi there,

Firstly - Redux Toolkit and RTK Query are awesome. They've made it super easy for me to get working with this stuff :)

However... I'm currently working with a Hypermedia API (built using [Siren](https://github.com/kevinswiber/siren)), which is hypermedia throughout. This means that the *only* URL that my client knows onto the backend service is the API root, and all other URLs are provided by API responses.

Is there a clear way to work like this within RTK Query?

As an example, if I want to add a query for getting the current user details - e.g. to power a user profile screen. This would involve:
* Requesting the API root - hopefully this is cached by RTK :)
* From this, finding the Embedded Link with a Link Relation of "current_user"
* Requesting this URL with RTK Query
* Returning the returned document for my components to render.

Unfortunately, this requires me to have access to one document in order to know the URL for the one I actually want to use.

Is there any way to achieve this?

Effectively the code would be something vaguely like:
```
export function useCurrentUser() {
    const { data } = rootApi.useGetApiRoot();
    if (data == undefined) {
        // Do something here!
    }
    const currentUserLink = siren.findEmbeddedLink(data, "current_user");
    if (currentUserLink == undefined) {
        // Do something here!
    }
    return usersApi.useGetUser(currentUserLink);
}
```

Except obviously the above (probably) won't work for several reasons!

Cheers

**Comment by phryneas** [comment]
That is certainly a weird concept.

If you want to go with your hook, it could look like this:

```js
export function useCurrentUser() {
    const rootResult = api.useGetApiRoot();
    return api.useGetUser(rootResult.isSuccess ? siren.findEmbeddedLink(rootResult.data, "current_user") : skipToken);
}
```

Otherwise you could also use `queryFn` to combine multiple api calls into one endpoint, but then the first call would not be cached individually.

(note that you should have only one api, not multiple, from the docs:)
![grafik](https://user-images.githubusercontent.com/4282439/153500885-95693f00-14cf-4ebd-ac0e-f46f9000371b.png)

**Comment by sazzer** [comment]
For the second part first, I do only have one API slice. I'm using TypeScript, so I've got a single slice and then I'm using:

```
const enhancedApi = api.enhanceEndpoints({
.....
});

const usersApi = enhancedApi.injectEndpoints({
.....
});
```

In each API file to allow me to have different files for different concerns. Works really well :)

But regarding the first part - what is `skipToken`? Is this anything special or just something you're proposing that the app use to indicate the provided URL doesn't exist, and then some clever handling in `query` or `queryFn` to understand not to react to this?

Cheers

**Comment by phryneas** [comment]
It's an export of RTK-Query. Passing it in as an argument is like setting `{ skip: true }` in the options, but plays better with TypeScript.

**Comment by sazzer** [comment]
Ooh - That actually works really well. Thanks :)

**Comment by marcusjwhelan** [comment]
RTK Query examples use the pokemon api as an example, this works great with a single endpoint like this.

However if you request all you get a list of names with urls to the resource. Attempting to use RTK Query to fetch each pokemon by name doesn't seem very straight forward. Can you show an example of pulling down the first 20 elements data given that setup or even using the given url to make the request? This isn't uncommon and is now a recommended architecture for REST https://restfulapi.net/hateoas/ .

**Comment by phryneas** [comment]
At the moment you have the problem with the rules of hooks: no loops. So usually, you would call the `useSinglePokemon` hook in a child and render a list of child components. There was a request for a `useQueries` hook, but so far nobody has stepped up implementing it - and for me it's on the list, but I didn't get to it yet.

**Comment by phryneas** [comment]
You can always use `queryFn` to write your own query logic and also make multiple requests with that single endpoint, but that would imho kinda defeat the "strength" of that approach that you can have multiple separate cache entries.

**Comment by marcusjwhelan** [comment]
@phryneas  The query is a single query to get one object from the API. Since that query is called for every row does RTK cache every one of those rows requests? I would think that it would only cache for a single request but if its in a table there will be 20 request for that one query in that `createApi`. 

Also if not using `queryFn` it is very slow to tie every request to a component, making all actions dom related.

 I also don't see a way to access the requested data from another component without knowing the arguments, like being able to get the data from another query that has been ran, I know `createApi` uses `slice` under the hood so shouldn't the state of the api be available some how?

**Comment by phryneas** [comment]
Regarding "slice and whatnot": a slice is what your normal Redux reducer was before, just written in a more convenient way. No real difference there.

Then I guess I'll have to go into the "normalized store vs document store" thing a bit deeper.

There are essentially two schools of thought:

* we fetch all the data, put it somewhere into state and manipulate it on the client (sorting, filtering etc.)
* we assume that there is more data than we could ever fetch on the server and leave sorting, filtering etc. to the server

Doing it manually (like you did or like it is shown in [chapter 5 and 6 of the Redux tutorial](https://redux.js.org/tutorials/essentials/part-5-async-logic) is school 1 - "keeping relational data". I assume that's where you are with your hyperapi. This is pretty traditional, but since that data can be structured in all kind of ways, it's almost impossible to write a "generic cache client" for it - you'll have to write your own code.
In that case, RTK Query is just the wrong tool.

School 2 - or the "just dont' overcomplicate it on the client and leave it to the server" approach is "document caching". We just tell the server "hey, give me 10 users, sorted by X and filtered by Y". This is where RTKQ excells. We're okay if the same user has been returned by three different requests and we don't even try to accumulate them together. We just care that we refetch data that might be stale, so it is "synchronous enough".

If you go with school 2, you rarely have two subsequent queries that really belong together. Because if they really belonged together, the api would already put them together in one response.

**Comment by marcusjwhelan** [comment]
@phryneas I see, more of school of thought vs tool of application. Thank you for taking the time to read and reply to my concerns. Fantastic
