### ISSUE TITLE
RTKQ: selectFromResult causing rerender when returning new array or object

### ISSUE THREAD

**Issue by nickkitto** [reduxjs/redux-toolkit#2039]
RTK Query is causing multiple rerenders when selectFromResult is used when I don't think it should.

My api returns a list of objects, and I want to grab the ids from them in the selectFromResult. I was performing a map to do this, however this causes multiple re-renders. Is this a bug or am I missing something here?

Here is a simple reproduction, switch out any query that returns an array and grab a field from it
```
import { useGetEngineQuery } from "../../api/api.generated";

const Dashboard = () => {
	var { ids } = useGetEngineQuery(
		{ tag: [""] },
		{
			selectFromResult: ({ data }) => {
				return { ids: (data ?? []).map((d) => d.id) };
			},
		}
	);
	console.log("log called", ids);

	return <div />;
};

export default Dashboard;
```
unexpectedly results in 4 logs. I expect 2 in this case, once with undefined during load, and then with the real data.

Changing the selectFromResult to just return a empty array
```
selectFromResult: ({ data }) => {
    return { ids: [] };
},
```
unexpectedly results in 4 logs. I expect 1 in this case.

Changing it to a primitive:
```
selectFromResult: ({ data }) => {
    return { ids: "dummy" };
},
```
results in 1 log as expected.

Returning the object returned directly:
```
selectFromResult: ({ data }) => {
    return { ids: data };
},
```
results in 2 logs as expected, once with undefined during load, and then with the real data.

**Comment by markerikson** [comment]
Yes, that is entirely intentional _and_ expected.

The query hooks use a shallow equality check on the entire overall return value of `selectFromResult`.

If you're returning new objects or new arrays _inside_ the returned object, then those are not equal and will force a re-render.

See these resources for reference:

- https://redux.js.org/tutorials/essentials/part-8-rtk-query-advanced#selecting-values-from-results
- https://redux-toolkit.js.org/rtk-query/usage/queries#selecting-data-from-a-query-result

Hmm. Actually, now that I look at the latter bit, we really should add more detail to clarify that bit of behavior.

**Comment by nickkitto** [comment]
Thanks for the quick reply Mark.
Looking at the first link I got it working as expected 👍.
I do agree that the second link doesn't describe the behavior adequately, but the first is fairly sufficient.
Feel free to close this or leave it open to enhance the docs.

**Comment by markerikson** [comment]
Docs issue it is!  Thanks!

**Comment by nickkitto** [comment]
Closing this as it is well described now. Thanks!
