### ISSUE TITLE
Cancel a query dispatched with RTKQ hook useGetSomethingQuery

### ISSUE THREAD

**Issue by gygabyte017** [reduxjs/redux-toolkit#2059]
Suppose we have a component which uses a query declared as usual with RTKQ, which depends on an user input:

`const {data} = useGetSomethingQuery(userInput)`

The user inputs for instance `first` and the query fires correctly. Now, _while the query is still pending_ (assume it is a huge request or the server is slow or anything), the user changes his mind and changes the input to `second`. A new query is fired correctly (and eventually the correct output will be displayed), but the first query is still ongoing (and the result will never be shown the user unless he inputs again `first` which hits the cache). While this is ok from a functional point of view (the user and the app don't have any problem) it is a waste of the server resources.

Is there a way to indicate RTKQ to cancel the query in these use cases?

**Comment by phryneas** [comment]
That assumes that aborting a request in the browser would actually stop it on the server. Usually, that is not the case at all. Server processing usually continues.

Now, turning the logic around. Assume the user had a typo, and presses backspace. Now, if the previous request was cancelled, we can just wait for that. Or we have to start it again after aborting it - which would trigger twice on the server (as I said before, probably for a full execution regardless of the cancellation).

So, there is little value in most common cases for request cancellation. We do expose it, but only in cases where you explicitly started a request - for lazyQueries and for mutations.  
But we do not expose it for the `useQuery` hook, because that one would require a lot of extra library code and does not seem to be worth the tradeoff of shipping it for everyone.

**Comment by gygabyte017** [comment]
Thank you for your answer, I didn't notice that cancellation was available for lazyQueries, it makes perfectly sense since it is indeed the specific use case where one needs manual control over the query.

Moreover, I realized that as you say there is no guarantee that the server will actually stop the computation, and for my use case that is not the case so the cancellation is pretty useless. The only good thing may be that if the query returns a oversized response, in that case the fetch would be skipped and the client/server bandwidth would be saved - but the server computation would not be spared in any case.

Thank you for all the clarifications, this can be closed.
