### ISSUE TITLE
QueryFn return type if result data is undefined.

### ISSUE THREAD

**Issue by KwehDev** [reduxjs/redux-toolkit#2090]
Hello!

I'm currently implementing RTK Query on one of our API endpoints, which can return an empty response for some 204 `DELETE` requests.

As per the documentation, the return types expected appear to be either an Error, or in case of success, a non-empty `{ data: value }` object.

I have something like this currently;

```
const baseQuery = fetchBaseQuery({
  baseUrl: apiBaseUrl || '/api/v1',
  prepareHeaders: (headers, { getState }) => {
    // If existing, set the idToken as the Bearer authorization token for all requests.
    const idToken = (getState() as RootWebState).auth.idToken;
    if (idToken) {
      headers.set('Authorization', `Bearer ${idToken}`);
    }
    return headers;
  },
});

export const baseQueryWithReauth: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (args, api, extraOptions) => {
    const result = await baseQuery(args, api, extraOptions);

    if (result.error && result.error.status === 401) {
      // Refresh Session
    }
    return result;
  };
```

However, in the case of the aforemented 204s returning no response, what would be the 'correct' way to approach this? 
The approach I have now results in an error;
```
 `baseQuery` returned an object containing neither a valid `error` and `result`. At least one of them should not be `undefined`
              It needs to return an object with either the shape `{ data: <value> }` or `{ error: <value> }` that may contain an optional `meta` property.
              Object returned was: {data: undefined, meta: {…}}
```

**Comment by phryneas** [comment]
Have you tried `{ data: undefined }` for the queryFn?

**Comment by KwehDev** [comment]
> Have you tried `{ data: undefined }` for the queryFn?

Yes, no luck I'm afraid :(

**Comment by phryneas** [comment]
Hmm yeah, remembering. 
`undefined` is a special value that we never allow as a result - that's usually not a problem since `undefined` is also not JSON-ifyable, so we do not expect it as a return value from any api.
Can you work with `null` instead here?

**Comment by KwehDev** [comment]
> Hmm yeah, remembering. `undefined` is a special value that we never allow as a result - that's usually not a problem since `undefined` is also not JSON-ifyable, so we do not expect it as a return value from any api. Can you work with `null` instead here?

Yes, that seems to do the trick!

If I add the following check;
```
  if (!result.data && !result.error) {
    return {
      data: null,
      meta: result.meta,
    };
  }
```
to the queryFn it seems to work as expected. Would this be the recommended solution, in that case?

**Comment by phryneas** [comment]
You could also do a
```js
  if (!result.error) {
    return {
      data: result.data ?? null,
      meta: result.meta,
    };
  }
```

**Comment by thisisgit** [comment]
Hi @phryneas, I also bumped into this issue while trying to return `undefined` as value of `data`.

While `null` works perfectly to represent "no data but not an error", I'm curious if there's specific reason of not allowing `undefined`? I think your above comment, **"... since undefined is also not JSON-ifyable"**, may be the answer to that but I don't quite understand what it means 😢

The intention of trying to return `undefined` instead of `null` is just that some teams (yes, including myself) use only `undefined` to represent non-value. So technically it won't result to any problem by using `null`, but it is just to keep code style consistent.

**Comment by phryneas** [comment]
Many reasons.

* upsertQueryData/updateQueryData need a result that is not `undefined` per design (`undefined` is reserved for "no change")
* we need one special reserved value for "this has not been fetched" ourselves
* SSR rehydration crashes with `undefined` anywhere in store, since that cannot go over the wire as JSON

Probably a dozen more that I don't think of right now
