### ISSUE TITLE
Add type parameter for Id in createEntityAdapter

### ISSUE THREAD

**Issue by Matt-Ord** [reduxjs/redux-toolkit#2098]
Currently `createEntityAdapter` provides no type checking for the id of an entity

This prevents type checking when using the selectors, and means that the return type of functions such as `getAllIds` returns `EntityId[]` rather than a type specific to the entity.

Introducing an (optional) type parameter for Id will solve all of these propblems, and also allow for the newtype pattern to ensure types between different adapters do not get mixed up
```typescript
type MyIdType = string & { readonly __tag: unique symbol }
```

**Comment by markerikson** [comment]
Hmm. @phryneas , thoughts?

**Comment by Matt-Ord** [comment]
Just thought I would drop another message to see what the status was with this - I'm happy to give more details of my use case if it would be helpful

**Comment by phryneas** [comment]
I'll have time this friday. 
Generally, something like this might be useful, but there is a very fine line balancing "adding additional generic parameters in many places" and "is the feature worth it" - since additional generic parameters become part of a contract we cannot change any more and have to support pretty much indefinitely.

**Comment by markerikson** [comment]
Available in the 2.0 betas.
