### ISSUE TITLE
`getPendingMeta` equivalent for shared values across lifecycle actions in `createAsyncThunk` (optimistic updates)

### ISSUE THREAD

**Issue by nathan-knight** [reduxjs/redux-toolkit#2102]
I'm writing optimistic actions that mutate a value in a normalized slice. I need to provide an interface that takes just an ID and a sparse update object. The pending action will apply the update and if there is an error then the rejection action must revert the change from the pending action.

Ideally I could use something like `getPendingMeta` that would let me get the original value from the state before the pending action and add it to the rejected/fulfilled meta (perhaps `getSharedMeta`). At the very least it could pass it to the payload creator and I could use `rejectWithValue` to pass the information along.

I read through #750 but the solution (#1083) doesn't do the trick because:
1. `getPendingMeta` only gets passed to the pending action, there is no way to use it later (that I can see)
2. `getState` in the payload creator will return the state after it has been mutated by the pending action so I can't use `rejectWithValue` to pass along the original in the meta.

I also read through #500 and the solution there of passing the entire original object introduces issues with the callers needing to always have the latest complete object instead of just being able to update a single field and is just less ergonomic to use in many circumstances. RTK Query isn't an option unfortunately, although it does look nice.

**Comment by phryneas** [comment]
Hmm. I don't think that will work out with `createAsyncThunk`. It might make sense to just write a normal thunk on your own for this.

**Comment by shernjauhal** [comment]
I've also been looking for a good solution for implementing optimistic updates using createAsyncThunk with the case of the dispatcher of the update only needing to pass in the pieces of state they wish to mutate. And handling pending/fulfilled/rejected with extraReducers.

In the pending action I have the incoming partial state change. I need a way to take the current state before the change and save the pieces that will be mutated (call this saved partial original state). Then mutate the state with the new values and fire the call to the backend.

In the reject action I need a way to get back that saved partial original state so that I can use it to UNDO the optimistic change that was made in the pending action.

Ideally this would all be accomplished within the thunk, so the only common thread would be the action object. Provide some way for the pending action to add the saved partial original state into the action, so that the reject action can retrieve it.

Right now the only solution I have is to store that saved partial original state outside the thunk in the main store. Which is not an ideal solution.

**Comment by phryneas** [comment]
You could wrap the call to the thunk in another thunk. In that thunk, you could get the current state, start a `produce` call with patches enabled and apply your patches in there. That would give you forward- and backwards-patches that you could pass into an argument of your wrapped `cAT`-thunk.

**Comment by shernjauhal** [comment]
Sounds interesting. I'll give it a try.
