### ISSUE TITLE
add custom meta do pending thunk

### ISSUE THREAD

**Issue by wmatyjanomtek** [reduxjs/redux-toolkit#2103]
Hey, 
I just wanted to ask if there is any option to pass custom data (other than args of a thunk) to the pending status. 
Before I had a situation in which I was fetching the user from the state in the action and passing it to the `REQUEST` action in the payload. Currently, there is no such option. I see three solutions: 
1. I don't know how to do this and someone here will help me. :D 
2. I can pass user in the thunk args
3. I can create a custom action, pass the user to its payload and dispatch it from the thunk.

Which is the best in your opinion guys?

**Comment by markerikson** [comment]
Yes, that is specifically covered here, with `getPendingMeta`:

https://redux-toolkit.js.org/api/createAsyncThunk#options

**Comment by thoughtworks-tcaceres** [comment]
> Yes, that is specifically covered here, with `getPendingMeta`:
> 
> https://redux-toolkit.js.org/api/createAsyncThunk#options

I tried searching through the docs but couldn't find anything.
Is there anything similar to `getPendingMeta` for RTK query queries?

**Comment by phryneas** [comment]
> Is there anything similar to getPendingMeta for RTK query queries?

No, all you pass in there is the `arg`.

**Comment by thoughtworks-tcaceres** [comment]
> > Is there anything similar to getPendingMeta for RTK query queries?
> 
> No, all you pass in there is the `arg`.

I see, thanks for the response.
I was trying to come up with a way to work with `react-native-offline`.
Before the fetch base query happens, i wanted to check to see if the connection was active, if not, i wanted to dispatch an action which contains the meta information from the api/executeQuery/pending action - but it looks like thats not possible.

**Comment by dimsumc** [comment]
> > Is there anything similar to getPendingMeta for RTK query queries?
> 
> No, all you pass in there is the `arg`.

I know this is a slightly old thread, but I’m wondering how to achieve the same effect as getPendingMeta. I’m trying to show a loading UI when an action is pending, but for some APIs, I don’t want to show the loading UI. Currently, I can’t distinguish which API triggered the reducer, because the pending action doesn’t contain extra information (e.g. skipLoading) for specific APIs.

```js
  extraReducers: builder => {
    builder.addMatcher(isPending, (state, action) => {
      return true
    })
...
}
```

Although I can pass a flag (e.g. skipLoading = true) in the args, it feels a bit misleading, since the args are meant to represent the request payload sent to the server. What would be the best approach in this scenario?
