### ISSUE TITLE
Have to pass types explicitly in createAsyncThunk

### ISSUE THREAD

**Issue by original001** [reduxjs/redux-toolkit#2150]
Hi! I want to use createAsyncThunk in my project, but there is some problems:
1. Every time I want to use createAsyncThunk, I must pass types explicitly. Otherwise, I don't get types of state, extra, etc.
2. If I pass my types, I lose type inferring of payloadCreator result. I need pass it explicitly too. Also, type of thunk argument moved to generic.

There are some redux libraries there is possible to redefine global interfaces. For example, react-redux do like that:
```ts
//  This interface can be augmented by users to add default types for the root state when
export interface DefaultRootState {}
```

This way is more convinient and can resolve these problems. I don't see any problems with that solution. In redux project is only one state.

In redux-toolkit I didn't find the same approach. `ThunkApi` depends on `declare type AsyncThunkConfig`, which I cannot redefine.

**Comment by markerikson** [comment]
Correct. Per the instructions in the [`createAsyncThunk` section of the "Usage with TypeScript" page](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk), you _must_ provide the types for the payload arg and the return value if you need to supply types for `state` and `extra`.

Frankly, a simpler option here is to just do `const state = getState() as MyAppRootState`.  You're really not going to lose any meaningful type safety there.

Also, note that [we're thinking about removing that `DefaultRootState` type from React-Redux itself](https://github.com/reduxjs/react-redux/issues/1879), specifically because globally overriding types is an anti-pattern.

**Comment by phryneas** [comment]
We are also thinking about adding an api for type pinning though, which will allow you to declare that only once per app: https://github.com/reduxjs/redux-toolkit/issues/1986#issuecomment-1027652620
