### ISSUE TITLE
Question: What is `extra` in `prepareHeaders` signature? [rtk-query]

### ISSUE THREAD

**Issue by akshay-nm** [reduxjs/redux-toolkit#2198]
Is the `extra` in `prepareHeaders` signature same as the `extraOptions` passed in a `endpoint` definition?

[link to the prepareHeader signature docs](https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#:~:text=provides%20access%20to-,extra,-%2C%20endpoint%2C%20type%2C%20and)
[link to extraOptions docs](https://redux-toolkit.js.org/rtk-query/api/createApi#:~:text=Copy-,extraOptions%E2%80%8B,Passed%20as%20the%20third%20argument%20to%20the%20supplied%20baseQuery%20function,-providesTags%E2%80%8B)

**Comment by phryneas** [comment]
Yes.

**Comment by phryneas** [comment]
That's right, 
I don't know where my mind was when answering this. `extra` in `prepareHeaders` is the `extraArgument` that is passed into the `redux-thunk` middleware. `extraOptions` is called `extraOptions` wherever it is available.

**Comment by jessepinho** [comment]
@phryneas would it be possible to include `extraOptions` from the endpoint definition when calling `prepareHeaders`? 

My use case: in my endpoint definitions, I include a `requiresAuth` key for the endpoints that need an auth token. I'd like to then check the value of that key in `prepareHeaders` to determine whether to fetch the auth token from the store.

It's not critical, since I can just always include the token if it exists; but it'd be nice to have!

**Comment by bolddp** [comment]
@jessepinho Did you figure out how to solve this, I have the exact same use case, e.g. I want to indicate for some endpoints that authorization should be handled in a special way

**Comment by jessepinho** [comment]
@bolddp I'm afraid I ended up not using RTK-Query.
