### ISSUE TITLE
Examples Not Working

### ISSUE THREAD

**Issue by ahmetcaglayan** [reduxjs/redux-toolkit#2213]
https://redux-toolkit.js.org/rtk-query/usage/examples

React Hooks and Svelte example not working.

**Comment by phryneas** [comment]
Both work fine for me. For the svelte example, you have to click the popup in the bottom right at the right moment when it comes up.

**Comment by ahmetcaglayan** [comment]
<img width="1373" alt="Ekran Resmi 2022-04-07 15 07 43" src="https://user-images.githubusercontent.com/13018803/162185844-6e81e999-5393-45ec-a198-4e6114f5ac5b.png">

Is there a problem with my computer?

**Comment by ahmetcaglayan** [comment]
"dependencies": {
    "@reduxjs/toolkit": "^1.5.0",
    "@rtk-incubator/rtk-query": "https://pkg.csb.dev/rtk-incubator/rtk-query/commit/e4ccd12a/@rtk-incubator/rtk-query",
    "msw": "0.21.3",
    "react": "17.0.0",
    "react-dom": "17.0.0",
    "react-redux": "7.2.2",
    "react-router-dom": "5.2.0",
    "react-scripts": "3.4.1"
  },
  
  @rtk-incubator/rtk-query I think there is an access problem. Can you update it with an updated link?

**Comment by phryneas** [comment]
As I said, I just tested it. It's a very outdated version of RTK Query and we should probably update those examples, but when you click on "Open Sandbox" they will just work fine. I have not tested them embedded, since I'm on the road and don't have the screen size - but it should just be an embed of the same thing.

**Comment by markerikson** [comment]
Yeah, we really _should_ update these to use the latest RTK.  I think there may also be some API changes that need to be applied ("entites" -> "tags", etc).  Unfortunately it's also kind of low priority, and it would be really helpful if someone could help us with that.

**Comment by sidwebworks** [comment]
@markerikson I would like to help with this, I saw your tweet about this issue.

**Comment by markerikson** [comment]
Thank you!

It _should_ basically be going through the `examples` folder in our repo and seeing which ones still refer to the RTK "incubator" package, and updating those to import from the actual RTK Query package instead and also fixing any broken options usages.

Longer-term, there may also be some CodeSandboxes in our RTK docs that are standalone or pointing to the old alpha repo.  Those ought to be updated to, but first step is fixing the ones that _are_ in the main RTK repo.

**Comment by sidwebworks** [comment]
Got it, I'll get started right away.

**Comment by sidwebworks** [comment]
@markerikson I went through all the examples inside `examples/query/react`, didn't find any package with `@rtk-incubator/rtk-query` in it's dependencies or imports. Most of them are using `^1.6.0-rc.1`.

Should I bump them up to `1.8.1` and check for any broken options ?

**Comment by markerikson** [comment]
You can go ahead and bump them, but it sounds as if the real issue is that we still have example sandboxes that were never ported over to the repo.

An example is the "React Hooks" sandbox at https://redux-toolkit.js.org/rtk-query/usage/examples#react-hooks .  Which, now that I look at the file source in https://github.com/reduxjs/redux-toolkit/blob/f098c9238c826abc83a2329ac1c0b9593f608440/docs/rtk-query/usage/examples.mdx , it's pretty clear which ones are "just" in CodeSandbox and which ones are pointing to the `examples` folder in our repo.

So, change of plans here.

Could you try tackling porting the remaining examples from the CodeSandbox into the `examples` folder in our repo?  You might be able to speed up some of the process by copy-pasting the skeleton from another example (say, `package.json`, any config files, etc), download the CodeSandbox as a zip, copy-paste the source into the new example folder, and then fix up the RTK imports.

**Comment by sidwebworks** [comment]
Okay so I am almost done refactoring the `react-hooks` example. Just Like Mark told I used the `base` example as a template to port the Codesandbox source into the repo examples. 

I have updated the imports, fixed the broken options for tag types, etc. 

However there is one slight issue with the Code splitting part, Seems like `ApiWithInjectedEndpoints` is removed, 

```ts
export const splitApi = emptySplitApi as ApiWithInjectedEndpoints<
  typeof emptySplitApi,
  [
    // these are only type imports, no runtime imports -> no bundle dependence
    typeof import('./posts').apiWithPosts,
    typeof import('./post').apiWithPost
  ]
>;
```

But looks like TS doesn't like it,
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58144379/162328379-52c62b5f-a747-40b1-96a2-7ed077e85bc3.png">


Also got the MSW working again.

**Comment by sidwebworks** [comment]
Cool, thanks to @phryneas I read some discord messages where he talked about the deprecation, seems like importing the `apiWithPosts` directly fixed the issue. 

https://discord.com/channels/102860784329052160/103538784460615680/834525930835148811

**Comment by sidwebworks** [comment]
Will open a PR now, btw because all examples were hook based I thought it would make more sense to rename the example from `react-hooks` to `kitchen-sink`, if that's fine?

**Comment by sidwebworks** [comment]
@markerikson I got a local branch `bump-examples` when I try to create a pull request against master, I get this error 
```
422 Validation Failed 
Create pull request error:
```

Any ideas what's wrong?

**Comment by markerikson** [comment]
Huh, no, never seen that before. Where's that error happening? When you push to your fork? When you hit a "Create Pull Request" button in the Github UI?

**Comment by sidwebworks** [comment]
@markerikson Can you please have a look at the PR, sorry for multiple gh jobs, I didn't expect netlify build errors from the docs site. 

Here is the new codesandbox url https://codesandbox.io/embed/github/sidwebworks/redux-toolkit/tree/master/examples/query/react/kitchen-sink?fontsize=12&hidenavigation=1&theme=dark&runonclick=1

**Comment by sidwebworks** [comment]
Hey @markerikson is this good to merge or is there anything else I can help with?

**Comment by markerikson** [comment]
Just merged that PR - hopefully this should be live shortly!

**Comment by sidwebworks** [comment]
Awesome, thanks
