### ISSUE TITLE
reducers are not type-safe

### ISSUE THREAD

**Issue by ethanneff** [reduxjs/redux-toolkit#2236]
Using this example as a guide: https://redux-toolkit.js.org/usage/usage-with-typescript#createslice

This should fail
<img width="537" alt="Screen Shot 2022-04-12 at 1 36 29 PM" src="https://user-images.githubusercontent.com/2933593/163049463-b4fe4a5a-63f1-4bfa-b30e-723200f0c100.png">

But it only does if you have an explicit return type
<img width="593" alt="Screen Shot 2022-04-12 at 1 36 37 PM" src="https://user-images.githubusercontent.com/2933593/163049505-00a807f0-4936-4a7b-bc77-3c5d6680ff5b.png">

The docs or the typings should probably be updated

**Comment by phryneas** [comment]
No, this is from a "TS design perspective" okay as it is.  
From TypeScript's perspective, a function that returns `A & B` is still a function that returns `A`. 

If you want the extra safety, you can specify that return type - but generally, we are not going to enforce it. It will end up as an additional property, but it is guaranteed that it will never clash with any typed usage of the object you will ever make, which essentially all that TS can try to guarantee in the first place. Every TS-typed object could at any point have any number of additional runtime properties. That is just how the language is.

**Comment by ethanneff** [comment]
This was a simplified example. Where this error showed up in our code was when a nested object was not updated correctly because there was no compile-time TS error to warn us. This seems to be a significant design flaw of redux-toolkit. I've been using Redux and Typescript together for over 4 years, and this lack of type safety is new to redux-toolkit.

<img width="448" alt="Screen Shot 2022-04-12 at 2 32 32 PM" src="https://user-images.githubusercontent.com/2933593/163058173-13c8669c-ee76-4897-811a-6288bf7596fd.png">

**Comment by phryneas** [comment]
As I said: **this is how TypeScript works**.

On RTK Level we can just say "here should be a method with the signature `(state: State, action: SomeAction) => State`.

TypeScript will not care if you supply a function with the signature `(state: State, action: SomeAction) => State & { someOtherProp: number }`.  
It is a 100% assignable/compatible function, so the library types can not do anything to catch this.


In the same sense, the following is 100% valid TypeScript code:

```ts
type A = {
  foo: string
}

type B = A & {
  bar: number
}

let a: A = { "foo": "foofoo" }
const b: B = { ...a, bar: 1 }

a = b
```

The only thing that could catch this is, as you already showed, a manual return type annotation on user level. But if a code base should have those annotations at all is not up to us to decide. That is a per-codebase style decisions and both styles have their pros and their cons.  

If you decide to annotate that type everywhere, there are linter rules enforcing that. If you don't you won't only have this problem in RTK, but also in every single other function in your application.

It's not up to us to force users either way. Personally I don't enforce it in my projects.

Either way, that additional property is just that: an additional property. Since no type for it exists, no code you have will ever be able to access it. So it will just dangle around uselessly.
