### ISSUE TITLE
"Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization" error in RTK Query

### ISSUE THREAD

**Issue by ahmetcaglayan** [reduxjs/redux-toolkit#2318]
What exactly am I doing wrong here?

As soon as I add **builder.addMatcher** to **extraReducers**, I start getting an error. Everything works fine before I add it. totally the problem is related to my adding **extraReducers**. But I didn't understand what I did wrong.

```
extraReducers: (builder) => {
    builder.addMatcher(
      authenticationApi.endpoints.postLogin.matchFulfilled,
      (state, { payload }) => {
        state.isLogin = true;
        state.token = payload.data;
      }
    )
  },

```
Store
<img width="571" alt="image" src="https://user-images.githubusercontent.com/13018803/168010116-1f8d7a13-220f-40be-b4b5-bd95bdfaa040.png">
Slice
<img width="668" alt="image" src="https://user-images.githubusercontent.com/13018803/168010274-1fe71e69-e8e9-4267-815e-6c55c41bc68d.png">
Api
<img width="668" alt="image" src="https://user-images.githubusercontent.com/13018803/168010386-c9650cc4-f8c9-408f-8425-05d21d0999f4.png">
Api call page
<img width="668" alt="image" src="https://user-images.githubusercontent.com/13018803/168010523-d695beb2-2f40-400a-95d6-7b104c213ab0.png">
Error
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/13018803/168010681-1eaaa12a-7f10-42a1-b9da-98ca215911ee.png">

**Comment by markerikson** [comment]
Not sure I have an answer without being able to see an actual project and investigate it.  Can you post a repo or CodeSandbox?

BTW, there _is_ a problem with your store setup.  You need to use `getDefaultMiddleware().concat(otherMiddleware1, otherMiddleware2)`, not `[...getDefaultMiddleware()]` - spreading it loses the correct TS types.

**Comment by ahmetcaglayan** [comment]
The problem is related to the api.dispatch that I throw in baseQueryWithReauth. After deleting api.dispatch, the problem went away. I think it's a problem to dispatch about authenticationSlice from here again. I'm going to fix the problem by changing the build.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/13018803/168144792-8484911a-7f58-4d6e-85b9-dd0c8c82c323.png">

**Comment by ahmetcaglayan** [comment]
So if I can't dispatch here, how will I handle the 401 status?
How can I set the authenticationSlice login status to false?
I also need to delete the token key?

<img width="735" alt="image" src="https://user-images.githubusercontent.com/13018803/168145920-efaf41ef-3c44-4b68-98fd-38a737016131.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/13018803/168146000-dc7d033b-df4f-4ccb-abe5-adcc84a902bf.png">

**Comment by markerikson** [comment]
I think the issue is you have a circular import problem.  The API file is importing the `baseQuery`, `baseQuery` imports the auth action, and the auth slice imports the API.

You're probably going to need to rearrange that logic to fix the circle.

I don't have an immediate answer on how to best do that atm - ironically _I'm_ in the middle of fixing a bunch of circular imports in my own app and that's taking up all my brain space :)

**Comment by ahmetcaglayan** [comment]
I guess I'll have to add another authenticationSlice that isn't extraReducers. This will fix the problem. But I will have an extra slice :)

**Comment by MartinMasek** [comment]
Hi @ahmetcaglayan did you fix the issue? I'm facing the same thing
1) Redux holds auth info
2) If network fails I want to clear the info
3) Network.ts -> authSlice.ts & store.ts
4) authSlice.ts -> Network (so thunk action can call Network) -- circular dependency

Previously, I would just do
`store.dispatch(
  {
    type: SET_AUTH,
    payload: emptyState
  }
)`

This approach seem not to work in new Redux.

**Comment by markerikson** [comment]
@MartinMasek There's nothing Redux-specific about this error per se. It's a build system issue.  It's possible that with a different set of files, things may be getting imported in a different order.

Generally, you should _not_ be importing the store directly into other files.  Instead, inject it from the entry point on startup.  See:

https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files

**Comment by MartinMasek** [comment]
### The problem
I've resolved the issue so I think it deserves a little context first because I struggled to google answer fast.

My app uses **Network.ts** (basically a static class - singleton) file. The app uses **Network.fetch** instead of system fetch. The reason is so I can pass access token with every request.

Now this Network class is basically a wrapper around fetch and if it sees 401 it wants to dispatch empty auth state so user is shown "Not authenticated" screen

The issue is that when you init a new project using https://github.com/reduxjs/cra-template-redux-typescript (which you are so kind to contribute @markerikson) it doesn't have a scenario for when you want to update the store from outside React component.

When there is UI action (say user clicks a button) it triggers Redux async action which uses internally the Network.ts class. That causes the problem as I described above.

### The solution:
Keep the authSlice.ts file but create new authActions.ts, authReducers.ts and authTypes.ts
The files can look like this (rather focus on the concept)
**authTypes.ts**
`export const AUTH_LOCAL_STORAGE_KEY = 'auth-token'
export const AUTH_SLICE_NAME = 'auth'
export const SET_AUTH_STATE_ACTION_NAME = 'setAuthState'

export type AuthReduxState = {
    isAuthenticated: boolean
    ... // other props
}

export const getEmptyAuthState = (): AuthReduxState => {
    return { ... }
}`

auth-actions.ts
`import { createAsyncThunk } from '@reduxjs/toolkit'
import { Network } from '../../api/Network'
import authSlice from './authSlice'

export const { setAuthState, ... } = authSlice.actions

export const myAction = createAsyncThunk('auth/fetchData', async () => {
    await Network.fetch('...')
})
`

authReducers.ts
`import authSlice from './authSlice'

export default authSlice.reducer`

The **authSlice.ts** file looks like a typical Slice with one change
`export const authSlice = createSlice({
    name: AUTH_SLICE_NAME,
    initialState: getEmptyAuthState(),
    reducers: {
        [SET_AUTH_STATE_ACTION_NAME]: (_, action: PayloadAction<AuthReduxState>) => {
            return action.payload
        },
        ...
    },
})

export default authSlice`

The store.ts has a slight change
`
import authReducers from './auth/auth-reducers'

reducer: {
        auth: authReducers,
    },`
    
And finally the **Network.ts** can dispatch to store
`...
if (result.status === 401) {
            localStorage.removeItem(AUTH_LOCAL_STORAGE_KEY)
            store.dispatch({ type: `${AUTH_SLICE_NAME}/${SET_AUTH_STATE_ACTION_NAME}`, payload: getEmptyAuthState() })
        }`
