### ISSUE TITLE
Store does not have a valid reduce & useSelector returns undefined state

### ISSUE THREAD

**Issue by KrowNFL** [reduxjs/redux-toolkit#2319]
Hello fellas!

Thank you for your help in advance!

I am facing a very odd problem with my React Native app, with my store not accepting the reducers I pass from Slice function. Would appreciate any insight on this!

Edit: Console logs the following error:
_Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers._

**App.js**
```
import {enableES5} from 'immer';
enableES5();
import AppNavigator from './routes/app.navigator';
import { Provider } from 'react-redux';
import poiReducer from './poistate';
import { configureStore } from '@reduxjs/toolkit';
import { AppRegistry } from 'react-native';


export default function App() {

  AppRegistry.registerComponent('main',() => App);

  const store1 = configureStore({
    reducer: { loc: poiReducer }
  });

  return(
  <Provider store={store1}><AppNavigator/></Provider>
  )
```
**PoiState.js**

```
import { createSlice } from "@reduxjs/toolkit";
import { createAsyncThunk } from "@reduxjs/toolkit";

export const getPoi = createAsyncThunk(
    'poi/getPoi',
    async () => {
        console.log('here');
        const response = await fetch('https://warply.s3.amazonaws.com/data/test_pois.json')
        const format = await response.json();
        return format;
    }

);

export const poiSlice = createSlice({
    name: 'poi',
    initialState:{
        poi:[],
        isLoading: false,
    },
    
    extraReducers:{
        [getPoi.pending]:(state)=>{
            state.isLoading = true;
        },   
        [getPoi.fulfilled]:(state, action)=>{
            state.loc= action.payload;
            state.isLoading = true;
        },
        [getPoi.rejected]:(state)=>{
            state.isLoading = false;
        },
        
    },
});

export default poiSlice.reducer;
```

**Comment by markerikson** [comment]
Hiya.  A few thoughts:

- You don't have to call `enableES5()`, because RTK actually already does that internally for compatibility.  (And fwiw if you're using a relatively recent RN version + the Hermes engine, that supports ES2015 `Proxy` anyway.)
- Can you try doing a `console.log(poiReducer)` inside of `App.js`?  What does that print?
- I'm not an RN user myself, but doing the `AppRegistry.registerComponent('main',() => App);` line _inside_ of `App` seems kind of suspicious.
- You also probably shouldn't be creating the Redux store _inside_ of `App` either. That probably needs to be done _outside_ of `App`

We unfortunately don't have an official RN template, but https://github.com/rahsheen/example-redux-toolkit-react-native-app may be a good example to compare against.

**Comment by KrowNFL** [comment]
Hello! And thank you sincerely for your time!

In regards to the console log, this is what it prints
**/static/media/poistate.31d6cfe0.bin**

As for the ES5, I scoured the internet for an answer but I was unable to find why immer was crashing and the only solution was from a person here, 2 years ago who resolved this with this call.

**Comment by markerikson** [comment]
@KrowNFL hmm. I'm confused - are you saying that `console.log(poiSlice.reducer)` literally prints out `"/static/media/poistate.31d6cfe0.bin"` as a string?  because if so, that's A) really weird, and B) definitely not right :)  

I do note that your import statement is `import poiReducer from './poistate';`, but you labeled the code snippet as `PoiState.js`, and those aren't the same filename casing.

Can you post the repo so I can take a quick look?

**Comment by KrowNFL** [comment]
> Can you post the repo so I can take a quick look?

Certainly

[]((https://github.com/KrowNFL/Warply))

**Comment by markerikson** [comment]
@KrowNFL I think you've got multiple problems going on here, unfortunately :(

- there's an empty file named `poistate` in the root .  That may be confusing the imports.
- You're doing `export default poiSlice.reducer` in `poistate.js`, which exports _just the reducer_ by itself.  That part is good. _But_:
    - you are doing `import poiSlice from './poistate'` in `App.js`, so conceptually the name is wrong - it's not the "slice object", it's the "slice reducer"
    - you have `console.log(poiSlice.reducer)` in `App.js`, which isn't right because you didn't import the entire slice
    - You have `configureStore({reducer: { loc: poiReducer }})`, but there _isn't_ a `poiReducer` variable in this file because you didn't give it that name when you imported from `poistate`
- Per earlier comment, you're creating the Redux store _inside_ of `<App>`, which isn't good

So, tbh you've got some very confused code, and none of this is a Redux-specific problem.  You're mismatching import names and variables and values, and none of this is lining up correctly.

I'd recommend looking at the repo I linked above, and using that as a guideline for setting up the project.
