### ISSUE TITLE
Argument of type 'AsyncThunkAction<Admin, void, {}>' is not assignable to parameter of type 'AnyAction'.   Property 'type' is missing in type 'AsyncThunkAction<Admin, void, {}>' but required in type 'AnyAction'

### ISSUE THREAD

**Issue by hanyunmuyu** [reduxjs/redux-toolkit#2364]
Argument of type 'AsyncThunkAction<Admin, void, {}>' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type 'AsyncThunkAction<Admin, void, {}>' but required in type 'AnyAction'
```
export interface AdminState {
	loading: boolean;
	admin: Admin;
}
const initialState: AdminState = {
	loading: true,
	admin: {
		id: 0,
		name: "",
	} as Admin,
};
const adminSlice = createSlice({
	name: "admin",
	initialState,
	reducers: {},
	extraReducers(builder) {
		builder.addCase(
			getAdminInfoAsync.fulfilled,
			(state, payload: PayloadAction<Admin>) => {
				state.loading = false;
				state.admin = payload.payload;
			}
		);
	},
});
export const getAdminInfoAsync = createAsyncThunk(
	"getAdminInfoAsync",
	async () => {
		const admin = await getAdminInfo();
		return admin.data;
	}
);
export default adminSlice.reducer;


```

 

`
	useEffect(() => {
		dispatch(getAdminInfoAsync());
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);
`

**Comment by markerikson** [comment]
This is a common issue. The problem is that `const dispatch = useDispatch();` only knows about the basic `Dispatch` type from the `redux` core. That `Dispatch` type does not know that thunks exist - it only accepts plain action objects. So, when you try to dispatch a thunk, it (correctly) errors.

The fix is to follow our "Usage with TS" guidelines for correctly inferring an `AppDispatch` type from store.dispatch, and then defining pre-typed hooks that have the thunk types baked in:

https://redux.js.org/tutorials/typescript-quick-start

**Comment by yibird** [comment]
@markerikson  issues #2364。Excuse me, sir. I also encountered the same problem. I checked the document, but I may not understand it clearly. So I checked the case, but I still couldn't find a solution. The most violent way is not to transfer middleware. I need your help. Can you write an example? Thank you! love you

**Comment by phryneas** [comment]
@yibird you need to share your full store setup including the setup of the types and hooks or we won't be able to help you show where you are going wrong.
