### ISSUE TITLE
Multiple calls of useSelector's function

### ISSUE THREAD

**Issue by DmitrySkripunov** [reduxjs/redux-toolkit#2424]
I'm a new guy in Redux, maybe I'm doing something wrong, but...

1. I installed **create-react-app** with **redux**
2. Copied and renamed **counterSlice** to **userSlice**
3. **userSlice** does the same behavior.
4. Added selector to Counter component
`const user = useSelector(selectUser);`
5. Now when I click on increment counter button I received 3 calls of **selectUser** function. But only ONE render of Counter component!
Is it correctly behavior? If my **selectUser** will be really havy function it will become a problem.
I understand about memoization, but I really confused by number of calls **selectUser**.

Thank you!

**Comment by markerikson** [comment]
@DmitrySkripunov That sounds plausible, yes:

- There will definitely be one call after the action is dispatched and store subscribers are notified
- There _may_ be another call in the component itself as it renders
- And React will re-render your component extra times during development.

So yes, we've _always_ said that selector functions _should_ be very fast to run, which is one of the reasons to do memoization.

**Comment by DmitrySkripunov** [comment]
Thank you, Mark!
One little question.
Why only one of two select functions are called 3 times in this case? The second one called only one time.

**Comment by markerikson** [comment]
@DmitrySkripunov Not sure - I'd need to see the actual code as a CodeSandbox or a Replay ( https://replay.io/record-bugs ) in order to know what's going on.

**Comment by DmitrySkripunov** [comment]
@markerikson https://codesandbox.io/s/determined-brown-74g3ss
Take a look at the console.
Each time when you increment or decrement counter state you will receive 2 calls (on my local machine 3 calls) of user select and only one count select.

**Comment by markerikson** [comment]
Okay, I see what's going on.

If you look at the replay I made at https://app.replay.io/recording/redux-useselector-call-behavior--48b5e298-0016-4c08-89db-2f4c0f2a1d0e , what's happening is:

- We're dispatching `increment` for the `counter` slice
- That causes the `checkForUpdates` check for `selectCount` to see that `state.counter.value` changed, so it saves a copy of the latest state.  When the `useSelector(selectCount)` runs during render, it sees the state is the same, so it doesn't re-run `selectCount`
- But, `checkForUpdates` for `selectUser` sees that `state.user.value` has _not_ changed.  So, it bails out _before_ saving `latestState.current =`.  Then, when `useSelector(selectUser)` runs, it sees that the saved state _did_ change, so it has to run `selectUser` a second time.

So, it's complicated, but this is actually expected behavior and working as intended.

**Comment by DmitrySkripunov** [comment]
@markerikson oh, I see, thank you so much!)
