### ISSUE TITLE
Bikeshed discussion: naming and marketing, again

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#246]
# Issue Update

The current plan is to rename the RSK package to "Redux Toolkit" / `@reduxjs/toolkit`.  See #248 for current migration status.

# Original Post

Back in #36 , we debated name options for a while.  We settled on `redux-starter-kit` because that's basically what we already had (`@acemarke/redux-starter-kit` , which itself came from https://github.com/reduxjs/redux/issues/2859 ), and the NPM package name was donated to us in that thread.

Unfortunately, I'm seeing a _lot_ of folks say that they didn't even want to look at the lib, because the name "starter" suggests it's only good for beginners, like these examples:

- https://twitter.com/Vall3y/status/1191514976177074177
- https://twitter.com/thehousecat/status/1190383361044299776
- https://www.reddit.com/r/reactjs/comments/dp55sh/just_finished_making_this_dashboard_for_trading/f5tlup8/

I don't _want_ to rename RSK, but clearly the name is throwing people off, and that concerns me.

I tried [asking about ways to improve the marketing](https://twitter.com/acemarke/status/1190296894494388229), and mostly got a bunch of random name suggestions.

Soooo... I'm gonna open this up for discussion again, and ask if we should seriously consider renaming RSK to something else, and if so, what.

Overall, the options are:

- Don't rename it at all, just live with it and try to improve marketing
- Rename it:
  - Some other global NPM name
  - Something scoped, likely under `@reduxjs/`
- Merge everything straight into the Redux core (https://github.com/reduxjs/redux/issues/3321)

Pros and cons:

- Don't rename:
  - :+1: keeps existing SEO; no migration step
  - :-1: folks continue to get confused about the benefits and audience
- Rename to something global:
  - :+1: maybe a better name?
  - :-1: migration, loss of SEO; have to find an available package name
- Rename to something scoped:
  - :+1: differentiates from other random Redux packages; precedent from `react-testing-library`
  - :-1: migration, loss of SEO
- Merge into core:
  - :+1: becomes very obvious that this is official and the default approach; everyone gets it
  - :-1: everyone gets the deps; no tree-shaking atm; recursive dependencies from libs to core?; migration, loss of SEO; where do all the RSK docs go?

Merging RSK into the core is highly unlikely, and @timdorr has said he's against that.  Still, it's a hypothetical option.

_If_ we were going to rename it, my inclination would be something like `@reduxjs/toolkit`.

Thoughts?

**Comment by mfpiccolo** [comment]
How hard would it be to achieve including it with tree shaking? That would be my vote if that was achievable. If not, I would vote for don't rename.

**Comment by Ericnr** [comment]
I see no downside to merging into core, if tree-shaking is possible. Without tree-shaking it's probably not an option. Second best would be using the @redux scope, as it shows right away its an official redux lib. @redux/starter-kit or @redux/toolkit sounds good.

**Comment by markerikson** [comment]
There are at least a couple potential technical issues with merging everything into the core:

- Apparent duplication of `createStore` and `configureStore`
- Recursive dependency: `redux-devtools-extension` depends on `redux`, but now we'd depend on it unless we went back to setting up the devtools manually
- Added dependencies for folks who aren't using the rest of the pieces (although this would maybe be less of a bundle issue with tree shaking, it's still a bunch of additional stuff that many folks don't currently use)

**Comment by stevensacks** [comment]
Use apollo-boost as your guide. 

Drop the word “starter”. I think `redux-kit` would suffice. It’s not a starter kit, it’s just a kit. But kit also has connotations of a toy, or something for teenagers. Worth picking a new name.

Apollo’s docs make no bones about boost. They don’t offer it as an option. From the get-go they say that boost is how you use apollo, and only mention the non-boost methodology later. They go all in on boost because for most people it will suffice, and you won’t even know when it won’t suffice until you hit those situations.

You have to make a decision about how important this kit is. If you want more people to use it, make it sound like it’s the best way to use redux for most situations and only in specific cases would you want to go custom, with instructions on how to import all the individual pieces separately, just like boost.

**Comment by phryneas** [comment]
As I think scoping would be the way to go, to make it stand out from all the non-official redux boilerplate toolkits (you noticed how it's received if you're not saying that "it's official" in [this thread](https://www.reddit.com/r/reactjs/comments/dp55sh/just_finished_making_this_dashboard_for_trading/f5t4kr4/), didn't you?), I'll suggest to split that option up:

* add the scope, keep the name ( => optimally @redux/starter-kit, if that doesn't work out @reduxjs/starter-kit )
  *  :+1: differentiates from other random Redux packages; precedent from react-testing-library 
  * :+1: :-1: almost no loss of SEO, since domain, articles etc can stay largely unchanged
  * :-1: migration
  * :-1: still has "starter" in the name

* add the scope, change the name ( => @redux[js]/[tool]kit )
  *  :+1: differentiates from other random Redux packages; precedent from react-testing-library 
  * :+1: "starter" is gone  
  * :-1: no loss of SEO
  * :-1: migration

**Comment by markerikson** [comment]
Unfortunately it seems to be the word "starter" that's throwing everyone off, so _if_ we're gonna rename it, that's gotta go.

**Comment by markerikson** [comment]
Looking through https://twitter.com/acemarke/status/1190296894494388229 and https://twitter.com/acemarke/status/1191518131765821443 , here's a list of all the proposed names (even the silly ones).  Repeated suggestions counted in parentheses:

- "initials only"
- @redux/starter-kit
- ++
- Accelerator (2)
- Advanced Kit Pro With Hooks
- Basics
- Batteries
- Catalyst
- Concurrent Mode
- Dev Kit
- Essentials
- Fire
- Focus
- Kit (3)
- Lightning
- Magnify
- On Rails
- Plus (3)
- Pro Max
- Recipes 
- Reduxnator 3000
- Rocket
- Setup
- Shortcut
- Simply
- Sparkle
- Super Kit
- Superstar Kit
- Supreme Kit
- Toolbox
- Toolkit (4)
- Tools
- Tools
- With-No-More-Boilerplate


The ones that actually have multiple votes are:

- Toolkit
- Kit
- Plus
- Accelerator


And as one person pointed out, [a search for `redux toolkit` turns up RSK as the first hit already](https://twitter.com/getDanArias/status/1191701603239301120).

There is an existing [`redux-toolkit` package on NPM](https://www.npmjs.com/package/redux-toolkit), and ironically it's pretty close in concept.  But, it was also last published over four years ago.  There's also http://rekit.js.org/ , a CLI and IDE for React+Redux development.

So yeah, _if_ we were going to rename it, it seems like `@reduxjs/toolkit` would be the most likely option.  "Redux Toolkit" as a name is similar enough to "Redux Starter Kit", and we could abbreviate it as "RTK" instead of "RSK".

Here's the obligatory Twitter poll on renaming options:

https://twitter.com/acemarke/status/1191755498749648896

**Comment by markerikson** [comment]
Okay, so let's discuss what would actually be needed to do this migration.  We would need to:

- Publish the new package name
- Get the new `redux-toolkit.js.org` domain name
- Point it at the docs site
- Also somehow have `redux-starter-kit.js.org` still pointing at the docs site.  (This may not require any work, if the `.js.org` settings just point both names at the same place.)
- Rewrite all the docs content to scrub and update the package name, the actual name, and the abbrevations
- Also preferably come up with a single "sales pitch" description line.  I've been using multiple variations in different places, and it would be nice to have something short, descriptive, and consistent.

Anything else?

The other complication is that #226 is in the process of trying to switch the docs site over to Docusaurus v2.

**Comment by phryneas** [comment]
We'll need a version bump (patch/minor/major?) of the old package name that either
* throws an exception with a migration message ([testing library currently does that](https://unpkg.com/react-testing-library@8.0.1/index.js))
* re-exports everything from the new package and prints a mirgation guide on installation/in dev environments on the console

**Comment by markerikson** [comment]
Another line of thought on naming suggestions :

Any good words that start with 'S' and go well with "Kit", to keep the RSK acronym? 

Or, another suggestion that popped into my head : "Redux Standard Toolkit" / `@redux/standard-toolkit`?

**Comment by stevensacks** [comment]
Forget about SEO, that doesn’t matter. It’s already been established that the current name is unpopular and confusing so what’s the benefit to hanging on to it? None. This is a rebranding. Start fresh.

Names that are unique and sticky are better than ones that are descriptive and accurate.

Fire
Catalyst
Rocket (alliteration ftw) 🚀

**Comment by markerikson** [comment]
I wouldn't say that the name is _unpopular_, just that the "starter" term is confusing people.

I would like any new name to be meaningful (ie, not a random code word), and ideally as similar as possible to the existing name.  "Redux Toolkit" seems to be the best option at this point.

**Comment by mplis** [comment]
I think I prefer `@reduxjs/toolkit`, but I do think one benefit of a "code word" name is that people are less likely to assume they know what it does before even looking into it, which seems like the problem `redux-starter-kit` has.

I'm a little surprised `redux-boost` didn't get any traction after you brought it up in the beginning of #36.

**Comment by markerikson** [comment]
@mplis : honestly, I'm against `redux-boost` simply because Apollo is using that naming already, and I want to avoid any confusion or appearance of copy-cat behavior.

**Comment by Ericnr** [comment]
also, in Apollo's case, apollo-boost REALLY is a starter kit. You quickly find out you need to ditch it if you more control over the lib. I think that's the exact mentality we are trying to avoid here.

**Comment by thehousecat** [comment]
I thought I'd throw my 2c in since I made one of the Twitter comments you quoted above.

I honestly think `redux-starter-kit` is fine. There might be the odd person like me who gets the wrong end of the stick initially. Once it becomes established in the blogosphere and social media it won't matter in the long run - it'll just be another name. It's not like "starter" doesn't make sense - it's obvious (now) it helps you start a new project and nothing to do with learning Redux. 

If you do decide to change the name then one I like best is `standard-toolkit`.

I don't like "boost" because it assumes that I know what a "boost" or an Apollo is :-). It's adding another terminology dependency that may not be ubiquitous enough.

**Comment by phryneas** [comment]
Oh, to add another thing: Initially, I didn't think that "starter" would confuse ppl too much. Until last week a team member told me that it had confused him when I added RSK to the project, because surely, we need no starter kit. 
Seems people actually *do* read the package name 🤷.

**Comment by giacomocerquone** [comment]
I'm following this from the very first tweet and yes, I was initially throwed off by the "starter" word too.
To me, redux-toolkit is great, but in order to keep the rsk acronym, I'd say redux-standard-kit (I wouldn't use toolkit, it'd become too long) and as someone else already pointed out, I wouldn't worry too much about seo. 
These kind of things are established because of the people who use them and not because of the fame.
One will use this not because it's famous but because it's good/needed and if something in the actual name is throwing people off, that is the issue.

**Comment by markerikson** [comment]
It'd be nice to keep the "RSK" acronym, but I could live with "RTK" for "Redux Toolkit".

**Comment by RichiCoder1** [comment]
👍 For `@reduxjs/toolkit`, I think it has good clarity. The other thing I'd say, piggy backing on the Apollo docs comment about, would to maybe have Redux & RTK under the same domain? E.g. `https://redux.js.org/toolkit` or something?

**Comment by markerikson** [comment]
@RichiCoder1 : hmm.  That's an interesting suggestion, actually.  

The immediate issues I see are:

- The RSK docs are currently completely separate in terms of repo, content, and location
- I don't think Docusaurus would have any way to do some kind of "embedding" or something.

I suppose we could duplicate some of the content, maybe, kind of like how we cover some of the React-Redux API and usage in the core docs.  That might be a reasonable approach - have an additional category for RTK, duplicate some of the API and usage stuff, and point to the actual RTK docs for the complete coverage.  Thanks for the idea!

**Comment by markerikson** [comment]
Opened an issue to ask about migrating the `redux-starter-kit.js.org` domain to `redux-toolkit.js.org`, with redirects:

https://github.com/js-org/js.org/issues/3532

**Comment by markerikson** [comment]
Opened a new issue to track the actual migration process: #248

**Comment by markerikson** [comment]
Having established that, I'm still looking for suggestions on a good marketing / sales pitch summary sentence. I've been using different variations, and it'd be nice to have a single consistent one.

Phrases I've used so far:

> - A simple set of tools to make using Redux easier 
> - A simple batteries-included toolset to make using Redux easier
> - The official, opinionated, batteries-included toolset for Redux

Also, my typical paragraph description:

> Check out our new Redux Starter Kit package. It includes utilities to simplify several common Redux use cases, including store setup, defining reducers, immutable update logic, and even creating entire "slices" of state at once [without writing any action creators or action types by hand]

Any better suggestions?

**Comment by sumitngupta** [comment]
Something around the "Reduction and elimination of common Redux boilerplate like action creators and action types". 

Eliminating boilerplate is what hooked me.

**Comment by RichiCoder1** [comment]
I'd err away from simple, if only since that might convey the same issues that docs have with the word "just". That said, I really like batteries included and opinionated as descriptors, as that's often what statements critical of Redux zero in on.

For the paragraph description, I think that's a great sell to *existing* Redux users, but makes a lot of prerequisite knowledge assumptions that might drive away beginners and skeptics.

Maybe something like:

> Redux Toolkit is a high level, opinionated set of tools to make it simple to manage your state using Redux. From quickly creating "slices" of your application's data to scaling up and composing complex state management, RTK provides a variety of foundational tools to build and update your application's state. Write less boilerplate, all while still taking advantage of Redux's rich ecosystem of middleware and tools.

**Comment by tgallacher** [comment]
More of a brain dump, but something along the lines of: 

> 1. Redux Toolkit: A utility belt of tools to streamline Redux state management 

or maybe just: 

> 1.  Redux Toolkit: Streamline and scale your application's Redux state management

**Comment by markerikson** [comment]
Hmm.  Maybe:

> The official, opinionated, batteries-included toolset for streamlined Redux development 

Could drop "opinionated" out of there, or say "efficient" instead of "streamlined".

**Comment by tgallacher** [comment]
> Hmm. Maybe:
> 
> > The official, opinionated, batteries-included toolset for streamlined Redux development
> 
> Could drop "opinionated" out of there, or say "efficient" instead of "streamlined".

Or possible drop both: 

> The official, batteries-included toolset for Redux development

Succinct and mostly objective? In fact, maybe even:

> The official toolset for Redux development

Which is fully succinct and objective?

**Comment by markerikson** [comment]
And the migration is basically done!  New package is published, repo and website have been renamed, and the docs have been mostly updated.  I still need to rework the RTK tutorial repos and sandboxes, and clean up some other bits.  But, not bad for one night :)

I settled on a sales pitch phrase of:

> **The official, opinionated, batteries-included toolset for efficient Redux development**

Since this is basically done, I'll go ahead and close the issue.  Thanks for all the feedback - now go migrate your apps over to RTK :)
