### ISSUE TITLE
unsubscribing from listener in useEffect

### ISSUE THREAD

**Issue by JCB-K** [reduxjs/redux-toolkit#2524]
I'm trying out adding/removing listeners to Redux in `useEffect`, and I'm seeing some (for me) unexpected behaviour.

I saw this snippet in the docs:

```js
useEffect(() => {
  // Could also just `return dispatch(addListener())` directly, but showing this
  // as a separate variable to be clear on what's happening
  const unsubscribe = dispatch(
    addListener({
      actionCreator: todoAdded,
      effect: (action, listenerApi) => {
        // do some useful logic here
      },
    })
  )
  return unsubscribe
}, [])
```

But when I run this, `unsubscribe` is actually undefined. Typescript seems to agree with me: it shows an error when I return it from the useEffect handler. Did I miss anything obvious, or are the docs incorrect here? If so, what would be another way to unsubscribe when the effect cleans up?

I've made a repro case here: https://codesandbox.io/s/recursing-easley-5n86vf

**Comment by phryneas** [comment]
That CodeSandbox doesn't seem to exist - but I would guess that you are not using your `AppDispatch` type here?

**Comment by JCB-K** [comment]
Woops, a letter fell off when pasting in the link - corrected now.

>  I would guess that you are not using your AppDispatch type here?

That's correct I'm not, but that shouldn't affect runtime code. The return value of `dispatch(addListener())` is undefined at runtime.

**Comment by markerikson** [comment]
@JCB-K I can confirm that the middleware itself _is_ trying to return the `unsubscribe` callback:

![image](https://user-images.githubusercontent.com/1128784/179532047-827d50ae-f046-49e1-a4e6-961bb1e1a749.png)

_But_, at least in your sandbox, **the "log action" middleware _isn't returning anything_** - it calls `next(action)`, but doesn't return the result:

```ts
const logActionMiddleware = (store) => (next) => (action) => {
  console.log("action: ", action);
  next(action);
};
```

I'm assuming you're seeing some kind of similar behavior in your real app - do you have any kind of a custom middleware that's also failing to return the result?

**Comment by JCB-K** [comment]
Ah that makes sense - I threw that logger middleware together in a second for this repro case 😅. But even if I remove it and run Redux only with the listener middleware then the snippet from the docs doesn't work. [Here's a codesandbox](https://codesandbox.io/s/compassionate-joana-3f7eom) where I replaced the buggy logger with redux-logger, and I call the unsubscribe fn on cleanup of the hook. The `listenerMiddleware/remove` action never shows in the log when the hook is cleaned up.

I've also tried it like this, overly explicit:

```js
const useListener = () => {
  const dispatch = useDispatch();
  React.useEffect(() => {
    const action = {
      predicate: (action) => action.type === "HEJ",
      effect: (action, listenerApi) => {
        // do some useful logic here
      }
    };
    dispatch(addListener(action));
    return () =>
      dispatch(
        removeListener({ predicate: action.predicate, effect: action.effect })
      );
  }, [dispatch]);
};
```

But even then the action is never dispatched. Am I missing something obvious? :) 

> I'm assuming you're seeing some kind of similar behavior in your real app - do you have any kind of a custom middleware that's also failing to return the result?

In my real app I receive the action I just dispatched, i.e. "listenerMiddleware/add".

**Comment by markerikson** [comment]
Oh. You _won't_ see the "remove" action in the Redux actions log, because the listener middleware intercepts it and does not let it reach the reducers.  It's like a message sent just to the listener middleware, and no one else should see it.

I did some fiddling around with that sandbox, and I think there's a few things going on:

- the store setup isn't right for getting the correct TS typings.  You can't pass an array directly like that and get the right types.  It needs to be `middleware: gDM => gDM().concat(something)` or similar
- For TS typings, you need to make sure that `dispatch` is typed properly and includes all the correct types applied to `store.dispatch`
- The listener middleware needs to go _before_ the logger middleware

I updated the sandbox to https://codesandbox.io/s/blazing-cdn-fz8tv1?file=/src/App.tsx, and now I do correctly see the `unsubscribe` function being logged, _and_ the types are matched up okay.

**Comment by JCB-K** [comment]
Awesome, thanks for the detailed explanation as always @markerikson!
