### ISSUE TITLE
Sort Query String Order

### ISSUE THREAD

**Issue by SeanFitzpatrick0** [reduxjs/redux-toolkit#2557]
RTK Query uses [URLSearchParams](https://udn.realityripple.com/docs/Web/API/URLSearchParams) to serialise the query parameters.

[URLSearchParams](https://udn.realityripple.com/docs/Web/API/URLSearchParams) does not serialise these parameters in any specific order. This makes it difficult to sign the request using [sigV4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) as the order that the parameters that are used for the signature may not be the same as the order RTK Query will serialise them in.

This can be resolved by sorting the [URLSearchParams](https://udn.realityripple.com/docs/Web/API/URLSearchParams) before serialising them (see [here](https://udn.realityripple.com/docs/Web/API/URLSearchParams/sort)).

i.e. The change would be to just add `.sort` [here](https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/query/fetchBaseQuery.ts#L229).

**Comment by phryneas** [comment]
`params` is an object there, how would you call `.sort` on that?

To be honest, this is not a very common requirement and as I guess that a simple `.sort` will not do it, but this will require some more code I'd recommend that you use the `paramsSerializer` instead - we would otherwise be adding quite some code that only a very small part of the userbase would have use for - but shipping it to everyone.

**Comment by SeanFitzpatrick0** [comment]
I am referring to sorting this (`new URLSearchParams(stripUndefined(params))`).

I can definitely unblock myself with using  `paramsSerializer` , but IMO I think it would be nice for this package to offer a consistent order that users can expect to have their query params by default.

Feel free to close if you don't think this can offer value. Just a small paper cut issue that I think can offer a slightly better experience.


Thanks for looking into this.
