### ISSUE TITLE
Is there a way to cancel an action in middleware?

### ISSUE THREAD

**Issue by sebpowell** [reduxjs/redux-toolkit#2579]
Here's my use case; I'm using Redux Toolkit to manage the opening and closing of different modals. 

I want to be able to trigger a confirmation modal that shows on top of the other modals to prevent accidental closure. 

The way to do this seems to be to use middleware; I can listen for the 'closeModal' action, intercept that, and then trigger the opening of a confirmation modal within that. 

So my code might look something like this:

```TS

const listenerMiddleware = createListenerMiddleware()

listenerMiddleware.startListening({
  actionCreator: closeModal,
  effect: async (action, listenerApi) => {
    // Somewhere here, I need a way of preventing the triggered action from completing
    listenerApi.dispatch(openModal({ name: "confirmCloseModal" }));
  },
});
```

What I'd like to know is how I can prevent the previous action from completing (and closing the modal). I can see the listenerApi has methods like `pause`, but nothing as far as I can see to cancel the action and prevent it from completing. 

I'm not sure whether I'm going about this the right way either – any pointers would be greatly appreciated. Let me know if my question isn't clear, and I'll add more code examples.

**Comment by markerikson** [comment]
The listener middleware itself cannot do that. It's intentionally designed to _listen_.  Like other "respond to an action" middleware like sagas and observables, it only checks whether listeners should run _after_ the action has already passed through the `dispatch`+middleware chain and reached the reducers.

However, Redux middleware in general _can_ do this. A middleware can do _anything_ it wants to _any_ action it sees going through the pipeline: log it, modify it, delay it, stop it entirely, dispatch something else instead, dispatch more actions, etc.

It's just that the listener middleware was designed to not have all that power, in order to keep usage simpler.

The simplest implementation would be:

```ts
import { Middleware } from "@reduxjs/toolkit";
import { closeModal, openModal } from "../features/someModalSlice";
import

export const modalHandlingMiddleware : Middleware = (storeAPI) => next => action => {
  if (closeModal.match(action)) {
    // dispatch and bail out, _without_ letting the action continue to the reducers
    storeAPI.dispatch(openModal({ name: "confirmCloseModal" }));
    return;
  }

  // otherwise, pass along for normal processing
  return next(action);
}
```

**Comment by sebpowell** [comment]
Amazing, thank you Mark! Really appreciate the detailed example, very helpful – that seems to be working perfectly.
