### ISSUE TITLE
How to prepopulate the redux storage (RTK Query)

### ISSUE THREAD

**Issue by lcorniglione** [reduxjs/redux-toolkit#2625]
Hi everyone,

I have a quick questions about the usage of RTK. I'm developing an ionic app and I need to support offline mode. Therefore I was trying to accomplish the following workflow.

1. I fetch information using RTK (as it is described in the documentation)
2. Every time I received an action type `mainApi/executeQuery/fulfilled` I made some logic to store that information in the ionic storage (to support mobile and web apps). I did this with a middleware.
3. The user refreshes the page, the redux storage gets empty
4. Before launching the app, I would like to check if I have some information already stored in the Ionic Storage to prepopulate (hydrate) the redux api store and keep doing requests to update that information.

Basically I would like to get rid of the spinners if I have stored information for the user. Once I preload that information inside redux, then the workflow should be normal (keep fetching information again, if the user has internet connection)

What I don't see clearly is how to achieve the last step. I tried with redux-persist, but I have read in the documentation that it's strongly discouraged (https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist). 
I also tried to delay the startup of the app until I get all the information from Ionic Storage and then tried to populate the redux storage with this api: `api.util.updateQueryData()`. Sadly it's not working as expected.

Whatever insight in this topic is appreciated. Thanks!

**Comment by phryneas** [comment]
It is generally discouraged as you will oftentimes present your users with outdated data - but if you definitely want to persist data it doesn't matter which method you use for that, so at that point it also doesn't matter if you use `redux-persist`.

`updateQueryData` will not work, since it only updates queryData and does not add new cache Entries. For that we have a PR open for `upsertQueryData`, but it's not merged yet.

So your best bet is probably to either use redux-persist (but see [persistence and rehydration!](https://redux-toolkit.js.org/rtk-query/usage/persistence-and-rehydration) or to manually save that api slice to the side and dispatch an action with that data to be intercepted by `extractRehydrationInfo`)

**Comment by lcorniglione** [comment]
Thanks you for your response and advice. 

My general idea is to present some data on startup (even if it's stale) while revalidating it under the hood in case there is internet connection. If that it's not the case the data couldn't be revalidated but at least the user has something to see until the connection comes back.
I'm gonna try with the options you mentioned.

Thanks again!
