### ISSUE TITLE
Feature Suggestion: `setPropCaseReducer` function for basic updates

### ISSUE THREAD

**Issue by Harris-Miller** [reduxjs/redux-toolkit#2659]
I'm sure that this caseReducer
```typescript
(state: State, action: PayloadAction<T>) => {
  state.propName = action.payload;
};
```
Is common enough that `@reduxjs/toolkit` should supply a function abstraction of it

```typescript
const setPropCaseReducer = <State, Prop extends keyof State>(prop: Prop) => (state: State, action: PayloadAction<State[Prop]>) => {
  state[propName] = action.payload;
};

type UserState = {
  email: string;
};

const initialState: UserState = {
  email: ''
};

const useSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    setEmail: setPropCaseReducer<UserState>('email')
  }
});
```

**Comment by EskiMojo14** [comment]
this pattern is explicitly [discouraged](https://redux.js.org/style-guide#model-actions-as-events-not-setters) - reducers should be events and modify as many properties as is necessary.

**Comment by Harris-Miller** [comment]
¯\_(ツ)_/¯

**Comment by markerikson** [comment]
Yeah, this is similar to the answer I gave in #2658.

We actively _don't_ want users to be writing a bunch of reducers that are all `state.fieldName = action.payload` all the time.

That's not to say you should _never_ do this - I've even written a few of these myself over in the Replay codebase.

But it's a pattern we want users to minimize, rather than one we want to encourage.
