### ISSUE TITLE
Feature Suggestion: Add `createAsyncActions` and allow `createAsyncThunk` to accept it as param instead of string

### ISSUE THREAD

**Issue by oshnix** [reduxjs/redux-toolkit#2665]
Hello, right now I am trying to use redux-thunk with `createAsyncThunk`  wrapper and `createReducer` to actually build my reducers.
It turns out that my application's data actually depends on API calls. I had an issue with circular dependency which I was able to resolve through `import type` instead of `import` but that's not the case.

It looks like using this pattern force us our data flow layer to depend on API communication layer which may lead to maintainability problems and issues during refactoring.

I suggest that both reducers and async thunks would depend on the same actions. I suppose that `createAsyncThunk` already produces it inside of itself.

I think that it's worth keeping both versions of `createAsyncThunk` - with first param as `string` and `AsyncActions` in place.

Moreover, from the TypeScript perspective we will have request\response types inside of actions variable itself which will allow us to not specify them during `createAsyncThunk` call or will provide us an additional safety layer.

P.S. I would like to implement this feature if you think it's worth it

**Comment by markerikson** [comment]
I don't understand what you're actually trying to suggest here. Can you give specific details of what you're trying to describe?

**Comment by oshnix** [comment]
@markerikson 
Sorry for being unclear.
I'll try to explain it via example

`api.ts`
```
export const getTest = createAsyncThunk(
    'test',
    async (id: string, { getState }: { getState: () => StoreState }) => {
        const { data } = await axios.get(`/users/${id}`);
        return data;
    },
);
```
`reducer.ts`
```
export const testReducer = createReducer(null, (builder) => {
    builder.addCase(
        getTest.fulfilled, 
        (state, action) => action.payload,
    );
});
```
`store.ts`
```
const rootReducer = combineReducers({ test: testReducer });

export const store = configureStore({ reducer: rootReducer });

export type StoreState = ReturnType<typeof rootReducer>;
```

1.  Circular dependency is another issue I've been referring too. There is a bypass but it will occur for anyone who starts using `createAsyncThunk`. However, it is resolved and I've mentioned it just for example.
https://github.com/reduxjs/redux-toolkit/issues/1126

2. I was trying to highlight that `reducer.ts` file depends on  `api.ts` file - actual implementation of data fetching.
From my point of view it forces our data flow (reducer) to depend on implementation of API layer.

What I'm trying to propose - move creation of fulfilled, pending and rejected actions
https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/createAsyncThunk.ts#L465

Into the another function with name like `createAsyncActions` and make it available from outside of the library.
Existing implementation of `createAsyncThunk` will call this function and behavior will not change.

Add another interface for `createAsyncThunk` which will get `asyncActions` instead of `typePrefix` as the first param.

**Comment by markerikson** [comment]
I don't think we're going to make any changes to the `createAsyncThunk` API design.

Half the point of `createAsyncThunk` _is_ that it generates those action creators and action types for you, and then `createSlice/createReducer` can listen for those.  Changing `createAsyncThunk` so that it accepts action types as an argument would defeat its purpose.  (Also, the internal implementation is already _incredibly_ complex at both the JS and TS levels, and we're not going to do anything to make that even more complicated.)

We actually recommend defining thunks in slice/reducer files by default anyway, and only moving them into other files if you _really_ need to.

Even if you do want to move those thunks to another file, I personally don't see a real problem architecturally with having that `api.ts` import in `reducer.ts`, although I understand your team may feel differently.
