### ISSUE TITLE
Upload progress for files

### ISSUE THREAD

**Issue by VictorPulzz** [reduxjs/redux-toolkit#2678]
Hello guys!
Will be cool add progress for uploading files. Like onUploadProgress in axois, but not using axios:)

**Comment by phryneas** [comment]
Unfortunately, using `fetch` that is pretty much impossible - you have to use XhrRequest or a library wrapping that (like axios) for that. That said, even if we would support that so far, the base concept of RTK Query is still "something started" -> "something finished". 

I'd recommend doing file uploads in a mutation with a `queryFn` where you manually create an XhrRequest and tracking the file upload itself by dispatching actions during that to track the upload progress in a separate slice.

**Comment by VictorPulzz** [comment]
Okay, thanks!

**Comment by romaelberg** [comment]
why not to use fetch? it's also have a possibility to track upload progress

**Comment by phryneas** [comment]
@romaelberg by now, it's theoretically possible [in newer chrome versions](https://developer.chrome.com/articles/fetch-streaming-requests/) but only http2, and I'm not sure if other browsers even support it yet. This is one of those things that are probably still too early.

**Comment by romaelberg** [comment]
got it, u can close the ticket

**Comment by vladmosienko-unicreo** [comment]
> Unfortunately, using `fetch` that is pretty much impossible - you have to use XhrRequest or a library wrapping that (like axios) for that. That said, even if we would support that so far, the base concept of RTK Query is still "something started" -> "something finished".
> 
> I'd recommend doing file uploads in a mutation with a `queryFn` where you manually create an XhrRequest and tracking the file upload itself by dispatching actions during that to track the upload progress in a separate slice.

Hi. Could you please explain, how can i enchance my **generated** rtk apis with `onUploadProgress`? Cant understand how to bypass `onUploadProgress` callback from react component, as api args type is generated and should not be modified. Seems like i cant even rewrite generated method using `enhanceEndpoints`, because `queryArg` type is generated anyway.. 
```
import { generatedApi } from '../../generated/api';

export const api = generatedApi.enhanceEndpoints({
  endpoints: {
    someGeneratedApiMethod: {
      query: (queryArg) => ({
        url: `/api/v1/someMethod`,
        method: 'POST',
        body: queryArg.methodGeneratedArgs,
        onUploadProgress: queryArg.onUploadProgress // onUploadProgress doesnt exist here :(
      }),
    },
  },
});
```
So.. The first question - is there a way to extend arg type of method (in enchanceEndpoints). Second - maybe there is even more easy way to do all this..?  Thank you!

**Comment by nfjdu** [comment]
> Unfortunately, using `fetch` that is pretty much impossible - you have to use XhrRequest or a library wrapping that (like axios) for that. That said, even if we would support that so far, the base concept of RTK Query is still "something started" -> "something finished".
> 
> I'd recommend doing file uploads in a mutation with a `queryFn` where you manually create an XhrRequest and tracking the file upload itself by dispatching actions during that to track the upload progress in a separate slice.

Hi. Could you please explain, how can i enchance my **generated** rtk apis with `onUploadProgress`? Cant understand how to bypass `onUploadProgress` callback from react component, as api args type is generated and should not be modified. Seems like i cant even rewrite generated method using `enhanceEndpoints`, because `queryArg` type is generated anyway.. ``` import { generatedApi } from '../../generated/api'; export const api = generatedApi.enhanceEndpoints({ endpoints: { someGeneratedApiMethod: { query: (queryArg) => ({ url: `/api/v1/someMethod`, method: 'POST', body: queryArg.methodGeneratedArgs, onUploadProgress: queryArg.onUploadProgress // onUploadProgress doesnt exist here :( }), }, }, }); ``` So.. The first question - is there a way to extend arg type of method (in enchanceEndpoints). Second - maybe there is even more easy way to do all this..?  Thank you!

**Comment by snps-halkoaho** [comment]
What we did was:

```
export const api = generatedApi.enhanceEndpoints({ 
  endpoints: { 
    someGeneratedApiMethod: { 
      query: undefined,
      queryFn: async (arg) => {
        // Do your xhr request here
      },
    },
  },
});
```

You do have to hard-code the endpoint url in the queryFn, I did not find any way to get it from the generatedApi.

We see this as a workaround, and are hoping for better support for progress in RTK Query.

**Comment by nfjdu** [comment]
> What we did was:
> 
> ```
> export const api = generatedApi.enhanceEndpoints({ 
>   endpoints: { 
>     someGeneratedApiMethod: { 
>       query: undefined,
>       queryFn: async (arg) => {
>         // Do your xhr request here
>       },
>     },
>   },
> });
> ```
> 
> You do have to hard-code the endpoint url in the queryFn, I did not find any way to get it from the generatedApi.
> 
> We see this as a workaround, and are hoping for better support for progress in RTK Query.

Thanks for quick answer! But anyway, even in `queryFn` the first param `arg` has type that is generated by api generator. How you bypass `onUploadProgress` callback **from react** component to this code?

**Comment by snps-halkoaho** [comment]
> the first param arg has type that is generated by api generator

No, it actually doesn't. The `query: undefined` overrides the `query` from generatedApi. You can define the `arg` as you wish for the `queryFn`. So we just pass `onUploadProgress` in `arg`.

**Comment by nfjdu** [comment]
> > the first param arg has type that is generated by api generator
> 
> No, it actually doesn't. The `query: undefined` overrides the `query` from generatedApi. You can define the `arg` as you wish for the `queryFn`. So we just pass `onUploadProgress` in `arg`.

![image](https://github.com/reduxjs/redux-toolkit/assets/43147143/0813fd32-02b6-4992-bf23-2fae822dee7e)
![image](https://github.com/reduxjs/redux-toolkit/assets/43147143/36e4349f-2090-452f-aa86-1c01fb91ae8a)
This error appears because of generated api response type:
![image](https://github.com/reduxjs/redux-toolkit/assets/43147143/89d05265-8217-47b7-8edc-9b46960347c9)

So.. the only way i see i to override api absolutely, using `injectEndpoints` + `overrideExisting: true`, specifying own args and response types, instead of using enchanceEndponts. Сorrect me please, if i'm wrong

**Comment by hamzeloudev** [comment]
A utility package for integrating file upload/download with progress tracking into your Redux Toolkit Query API slices:

[rtk-upload-utils](https://www.npmjs.com/package/rtk-upload-utils)
