### ISSUE TITLE
How to access to other state in reducer 

### ISSUE THREAD

**Issue by Victor716** [reduxjs/redux-toolkit#2691]
### Title
how to access to other state in reducer 

### Current Version
1.6.1

### Example

`
const rootState = {
     stateA: {...},
     stateB: {...},
}

const reducerInStateA = (state,action) => { console.log(state)} // it is a proxy and not accessible to stateB
`
### Questions: 
Just wondering: 
1. Why state in a reducer is a proxy object?
2. Any solution to accessing other state in a reducer?

**Comment by markerikson** [comment]
The `state` in the reducer is wrapped in a `Proxy` because we use Immer inside of `createSlice/createReducer` to simplify immutable updates:

- https://redux-toolkit.js.org/usage/immer-reducers

And no, even in original Redux, each "slice reducer" can _only_ see its own slice of state.  So, `reducerA` does not know that `rootState` exists, and it _cannot_ see `rootState.stateB`.  As far as it knows, only its own `state` exists - it's just that that's being combined into the larger `rootState` object:

- https://redux.js.org/faq/reducers#how-do-i-share-state-between-two-reducers-do-i-have-to-use-combinereducers

(also fyi, the current RTK version is 1.8.5, and we're working on 1.9 - I'd recommend upgrading soon!)
