### ISSUE TITLE
Typo issue in RTK Query docs

### ISSUE THREAD

**Issue by barzin144** [reduxjs/redux-toolkit#2704]
In rtk-query/overview page inside "Use Hooks in Components" section, the word "isFetching" has been used instead of "isLoading"

**Comment by markerikson** [comment]
Appreciate the issue and PR, but that's actually intentional.

Per https://redux-toolkit.js.org/rtk-query/usage/queries#frequently-used-query-hook-return-values , `isLoading` is only true the _first_ time the query is running. `isFetching` is true _every_ time, so that's what you should use most of the time.
