### ISSUE TITLE
`transformResponse` and `onCacheEntryAdded`

### ISSUE THREAD

**Issue by sshmaxime** [reduxjs/redux-toolkit#2795]
I found the idea of `transformResponse` pretty brilliant but I don't understand why it isn't being executed before `onCacheEntryAdded`. Is it on purpose ?

Indeed, if I do the initial query with `query` and needs to transform the output of it using `transformResponse`, why wouldn't I need it on `onCacheEntryAdded` ?

Is this the expected behavior or am I doing this wrong ?

**Comment by markerikson** [comment]
I'm not sure I understand the question - can you clarify what you're trying to do?

In general:

- `transformResponse` is meant to reshape the data that was received from the server before it's put into the cache entry.  A typical example might be changing an array of items to be a lookup table keyed by item ID, so that you can access `data[someId]` in a component.
- `onCacheEntryAdded` is a "lifecycle callback" used to trigger additional logic, such as opening up a websocket connection to the server to stream more updates.

**Comment by sshmaxime** [comment]
Sorry for not being precise enough, also I think i got confused and will go through my initial thought for the sake of it.

In my use case, I'm using websocket through `onCacheEntryAdded`. At the root of that, I have an initial query through the `query` field. When I'm receiving the initial data from that initial query, it goes through my `transformResponse` to be parsed and re-arranged. I understand this concept very well.

Now, if my server, on that initial query returns an array that I need to sort with `transformResponse`. When my websocket endpoint gets triggered it adds a new element to my array but it is therefore not anymore to my liking. I was expecting `transformResponse` to be executed again.

Coming to think about that more deeply, I feel like my use case might be a bit too restricted and not made for general context.

**Comment by markerikson** [comment]
If you're saying that your websocket handler does "streaming updates" to update the cache entry, then yeah, it's up to you to _fully_ update that cache entry however you want it to be, like:

https://redux-toolkit.js.org/rtk-query/usage/streaming-updates#websocket-chat-api-with-a-transformed-response-shape

or

```ts
  updateCachedData(draft => {
    draft.push(newItem);
    draft.sort();
  })
```

`transformResponse` only runs when an actual request is made - after all, there has to be a request in order for there to be a response.
