### ISSUE TITLE
RTK Query - `isLoading` defaults to `false` when using `selectFromResult`

### ISSUE THREAD

**Issue by taochu** [reduxjs/redux-toolkit#2827]
Not sure if I should post as an issue or discussion since I'm not sure if this is intentional. Pls lmk if I should post this elsewhere.

Just realized that for the same query hook, the initial `isLoading` value seems to be different based on if `selectFromResult` is used or not, e.g.

```ts
// isLoading is initially true then false
const { isLoading } = useGetPostsQuery();

// isLoading is initially false, then true, then false
// the res => res is just for demonstration, not that I'm really doing that
const { isLoading } = useGetPostsQuery(undefined, { selectFromResult: res => res })
```

Curious if ^ is by design or not 🙏 Thanks in advance 😃

**Comment by phryneas** [comment]
Using `selectFromResult` overrides an internal `selectFromResult` that hides some things for everyday convenience:

In reality, you go `isUninitialized` -> `isLoading` -> `isSuccess`. Since that might be an important distinction if you write your own `selectFromResult`, you get the "real" values there.

**Comment by taochu** [comment]
In that case, is it safe to say that, to mimic the internal `isLoading`, we should probably do 👇 

```ts
const { isLoading } = useGetPostsQuery(undefined, {
  selectFromResult: res => ({
    isLoading: res.isUnitialized || res.isLoading,
  }),
});
```

**Comment by phryneas** [comment]
Yup.
