### ISSUE TITLE
entityAdapter: CRUD callback syntax support

### ISSUE THREAD

**Issue by burtek** [reduxjs/redux-toolkit#2868]
We can update values in reducers with a simple `state.number ++`. But this is not something we can do with `update...` methods from entity adapter. The `update...` methods require plain object of changes. The callback syntax, that is well known from React's `setState`/`useState` methods (i.e. `setState(prev => prev + 1)`) is not available in `update...` methods, but I think it would be a great addition.

```js
const slice = createSlice({
    // ...
    reducers: {
        increment(state, { payload: { rowId } }) {
            entityAdapter.updateOne(state.rows, { id: rowId, update: entity => { entity.value++; } });
        },
        incrementSelected(state) {
            // rather than array of objects, we provide array of ids and a common updater
            entityAdapter.updateMany(state.rows, { ids: state.selectedRows, update: entity => { entity.value++; } });
        },
    }
    // ...
})
```

Of course this is something we can do easily without entity adapter, i.e.

```js
state.selectedRows.forEach(rowId => { state.rows.entities[rowId].value++; });
```

but so is the whole task of managing and updating entities (updating and inserting items is easy without entity adapter) and I feel like the new syntax would be very useful and would fit the entity adapter

**Comment by markerikson** [comment]
The original entity adapter from `@ngrx/entity` _did_ have an "update callback" option.  But, I had to remove it, because I was reworking the adapter to let these CRUD methods be used as reducers, and Redux actions cannot contain non-serializable values like functions inside.  So, I removed that specific option.

It _would_ be possible to re-introduce it as a variation that _only_ works as a "mutating helper method" rather than a reducer... but it would be the _only_ one like that, and I think that would be confusing to users.

Given that, this is not something I think we're going to implement any time soon.
