### ISSUE TITLE
Queries throw away data when skipped

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#2871]
Seems like the changes in #2779 broke some existing behavior:

- https://github.com/reduxjs/redux-toolkit/discussions/2865#discussioncomment-4064743
- https://github.com/reduxjs/redux-toolkit/issues/2870#issuecomment-1304896163

**Comment by phryneas** [comment]
Yeah. It seems that before, the behavior was a bit unpredictable - sometimes going one way, sometimes another.

We should probably add a `{ skip: 'keep' }`/`skipAndKeepToken` to have the behavior always predictable.

**Comment by ivan-jelev** [comment]
I would not expect to have `{skip: 'keep'}` or `skipAndKeepToken`.. it adds unneeded verbosity and confusion.. Instead `{skip: true}` should **only** prevent new requests and should not impact `data` / `currentData` for requests which already has some cached data.

**Comment by phryneas** [comment]
Well, we had tests in place [since the initial release of RTK Query](https://github.com/reduxjs/redux-toolkit/blob/2d787f5c39a6aad0d4dd695faa5f08bc0e0d61fd/packages/toolkit/src/query/tests/buildHooks.test.tsx#L2026) that made sure that `skip: true` should not return any data.  

Honestly, I was unaware that it did return data in some circumstances. Still, now we are in a situation where we know that sometimes it returned data and sometimes it didn't - apparently based on some internal timing.

The best way going forwards seems to ensure that the actual behavior *always* is the behavior we have always been testing for and that was also the intended behavior - and adding a new behavior for those that want the "sometimes accidental" behavior.

**Comment by ivan-jelev** [comment]
Right.. it makes perfect sense for granular/atomic queries. However now there's more cases and with `merge` we actually have ability to see not just granular query state, but accumulated state of query series. `{skip: true}` in context of granular query is expected to behave as designed initially, but in case of accumulated state it's not expected to loose all data because of one skip in a seria.


An option might be to make `skip` behaviour different for queries with `merge` and without. Or to introduce suggested `{ skip: 'keep' }` / `skipAndKeepToken`.. but in any case we need a way to prevent `data` / `currentData` reset  because of `{skip: true}`

**Comment by piotrlubecki** [comment]
I think that current behaviour is inconsistent between `useQuery` and `useLazyQuery`. In `useLazyQuery` `data` always returns latest returned result regardless of trigger arg and `currentData` considers args. `useQuery` behaviour according to documentation should be similar (https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#usequery), however  when `skip: true` `data` is undefined.

When it is necessary to get latest returned result regardless of trigger args and sometimes skip request, now it is necessary to use `useLazyQuery`.  `useLazyQuery` works fine, but it requires more code than `useQuery` (It is necessary to write logic already provided in `useQuery`). 

I personally find it more intuitive when `data` always returned latest result.  I am  happy with achieving it using `{ skip: 'keep' }` / `skipAndKeepToken`, but maybe this should be the default behaviour and returning undefined should be an option (then `useQuery` and `useLazyQuery` will have consistent behaviour)?

**Comment by phryneas** [comment]
@piotrlubecki You can't `skip` a lazy query, so how could the `skip` behavior between a hook that has that functionality and a hook that never knows that concept ever be consistent?

**Comment by piotrlubecki** [comment]
@phryneas Yes, there is no `skip`, but it can be triggered conditionally, which behaves as skip. 
According to documentation `useQuery` and `useLazyQuery` should be similar, so maybe if `useLazyQuery` always returns latest result in `data` then `useQuery` should do the same, even is skip is used (as skip seems like best equivalent of triggering `useLazyQuery` conditionally)?

**Comment by piotrlubecki** [comment]
@phryneas I am thinking about this scenario:

```
const [trigger, result] = useLazyQuery();

if (condition){
   trigger(args);
}
```

I thought that above could be compared to this:

` const { data } = useQuery(args,  { skip: !condition } );`

In this scenario, assuming that point 3 and 4 from your explanation were called at least once, `result.data != data` when condition is false. `useLazyQuery` `result.data` will always return latest result, after it will be called at least once. `useQuery` `data` will return undefined, if condition is false, even if it was called before. 

I might been wrong to use `skip` this way, as it was unintended behaviour, but it has worked really nice for me and it was simpler than using `useLazyQuery`.

**Comment by phryneas** [comment]
Well, in your example, the `trigger` sets the argument and then keeps it forever. There is no `skip` behavior there.

I want to step back a bit and want to ask: why do you even want to use `skip` if you deliberately want to access that data?

**Comment by defaktor** [comment]
As we see in documentation: https://redux-toolkit.js.org/rtk-query/usage/conditional-fetching
"If skip: false is set after the initial load, the cached result will be used" - and this is good way to use skip option.

**Comment by phryneas** [comment]
> As we see in documentation: https://redux-toolkit.js.org/rtk-query/usage/conditional-fetching
> "If skip: false is set after the initial load, the cached result will be used" - and this is good way to use skip option.

That is a very good point - now we do have a problem 🤔 if this was actually documented, we might need to roll it back. 
Thank you very much for pointing that out!

**Comment by jarosik10** [comment]
@phryneas What about the rollback?

**Comment by rubimbura** [comment]
@phryneas is there a problem if I use mutation instead of Query to call a GET end-point? with muation I dont have to deal with  skip.

**Comment by thesteady** [comment]
This has been a **breaking change** for my app, so wanted to add some notes in case its helpful in decision-making here. We were relying on a previously run query that then gets skipped to keep its `data` in several places across our application. Upgrading from 1.7.2 to 1.9.2 caused us to suddenly lose data on skipped queries after it was successfully fetched.
 
We use a combination of `skip` and `pollingInterval`, along with a `React useState` variable to poll an endpoint for a status on a long-running job. When the query response indicates that the job is complete, we don't need further updates and so we were setting React state to `true` / complete, which in turn causes `skip` to become true. Example:

```
const [jobIsComplete, setComplete] = React.useState(false);
const myQuery = useCoolQuery(queryArgs, { 
   skip: missingQueryArg || jobIsComplete,
   pollingInterval: someTime
});
```
Before, this worked because we were still getting `data` on skipped queries. Upgrading, we would suddenly lose data after a successful query. For most cases, it was relatively easy to instead set the `pollingInterval` to 0 when the state updated to true. That feels like the better solution to me for these queries in general, but took a bit of digging to figure out what was happening. For one other query, we've had to _add_ this pollingInterval check as a bit of hack to avoid losing data on a re-render.

A note somewhere (release notes, docs) that behavior has changed would be super helpful for faster troubleshooting, I'd imagine.

_p.s. thank you for your hard work!_

**Comment by markerikson** [comment]
@thesteady : for the record this is a "bug" and not an _intended_ breaking change.  

We do need to fix this, but tbh it's kind of slipped off the radar due to the holidays, personal life, and other priorities.

**Comment by thesteady** [comment]
Cool thank you! I read through the comments and wasn't clear, my bad.

**Comment by rubimbura** [comment]
> 
Many thanks @markerikson.

**Comment by markerikson** [comment]
Could folks try out the CodeSandbox preview build in #3188 and let me know if that fixes the skipping issue?

**Comment by markerikson** [comment]
@kasparkallas : then use `const { currentData } = useQuery()` instead, which reflects "the value for the _current_ args".
