### ISSUE TITLE
Ability to retrieve an endpoint name

### ISSUE THREAD

**Issue by matthieuh** [reduxjs/redux-toolkit#2940]
# Goals

Ability, having an injected endpoint, to retrieve its name.

If you think this is a good idea I would be glad to contribute opening a PR :grinning:

# Background

In redux toolkit endpoints are injected into an RTK API with their names being the keys of `NewEndpointDefinitions` (https://redux-toolkit.js.org/rtk-query/api/created-api/code-splitting#injectendpoints):

```ts
myApi.injectEndpoints({
  endpoints: (builder) => ({
    endpointA: endpointAFactory(builder),
    endpointB: endpointBFactory(builder),
    endpointC: endpointCFactory(builder)
  }),
});
```

It is impossible today, having only access to an injected endpoint, to retrieve its name.

## Example

```ts
const myEndpointA = myApi.endpoints.endpointA
```

How can I get the endpoint name (`endpointA`) from the `myEndpointA` const without having access to the RTK API?

# Proposal

Having assigned my endpoint to a variable:

```ts
const myEndpointA = myApi.endpoints.endpointA
```

I’m able to retrieve the name of the endpoint using the `name` property:

```ts
const myEndpointAName = myEndpointA.name; // 'endpointA'
```

**Comment by markerikson** [comment]
Can you give an example of where/why you would need to do this?

**Comment by matthieuh** [comment]
@markerikson we are storing our endpoints in an array and later on we want to get all those endpoint names. 

```
export const apiEndpoints = [
  api.endpoints. endpointA,
  api.endpoints. endpointB,
  api.endpoints. endpointC,
];
```

Our use case is for displaying names in our tests.

**Comment by markerikson** [comment]
Where and how are you trying to get these names? I would _assume_ (without having checked our code) that iterating over `api.endpoints` after calling `api.injectEndpoints()` would indeed give you all the endpoint names.

**Comment by matthieuh** [comment]
In our case, we don't want to iterate on `api.endpoints`. We build at some points an array of endpoints, and then later we want from this array to find the associated names. Those endpoints can come from several APIs.

```ts
const endpoints = [
  api1.endpoints.endpoint1A,
  api1.endpoints.endpoint1B,
  api2.endpoints.endpoint2A,
  api3.endpoints.endpoint3E
];
```

**Comment by markerikson** [comment]
I'm genuinely confused at both what you're trying to do and what you're asking for :(

I'm going to need you to give me a lot more details, because I have no idea what the goal or issue is here.

To be very clear: **Calling `api.injectEndpoints()` adds each endpoint entry to `api.endpoints` as soon as `injectEndpoints()` is done!**  It does some internal work, then exposes each endpoint entry as a field on `api.endpoints` just as if it was there in the initial `createApi` call.  

As a check, I just tried tweaking one of our tests to try logging the fields on `api.endpoints` before and after a call to `api.injectEndpoints()`:

```ts
  test.only('mutation: query & transformResponse types', () => {
    console.log('API endpoints before: ', Object.keys(api.endpoints))
    api.injectEndpoints({
      endpoints: (build) => ({
        query: build.mutation<'RetVal', 'Arg'>({
          query: (x: 'Arg') => 'From' as const,
        }),
        query1: build.mutation<'RetVal', 'Arg'>({
          query: (x: 'Error') => 'From' as const,
        }),
        query2: build.mutation<'RetVal', 'Arg'>({
          query: (x: 'Arg') => 'Error' as const,
        }),
        query3: build.mutation<'RetVal', 'Arg'>({
          query: (x: 'Arg') => 'From' as const,
        }),
        query4: build.mutation<'RetVal', 'Arg'>({
          query: (x: 'Arg') => 'From' as const,
        }),
        mutationInference1: build.mutation<'RetVal', 'Arg'>({
          query: (x) => {
            return 'From'
          },
        }),
        mutationInference2: (() => {
          const query = build.mutation({
            query: (x: 'Arg') => 'From' as const,
          })
          return query
        })(),
      }),
    })

    console.log('API endpoints: ', Object.keys(api.endpoints))
  })
```

result:

```
API endpoints before:  []

API endpoints:  [
      'query',
      'query1',
      'query2',
      'query3',
      'query4',
      'mutationInference1',
      'mutationInference2'
    ]
```

So, the way to "access endpoint names" _is_ to iterate over the keys in `api.endpoints`.

What about this is not sufficient for you?

**Comment by markerikson** [comment]
Hmm. Are you saying that there is literally no `api.endpoints.myEndpoint.name` field?  Is that all this is about?

**Comment by phryneas** [comment]
I *think* that's the point.

I am still a bit irritated by possible use cases - especially in the case you are describing it seems you are more testing the library and not your code (as you are doing so with an array of stuff and not actual use cases), but adding a property like that is of course a possibility.

**Comment by davidgarry** [comment]
Hello @markerikson @phryneas 

Thank you for your quick answers. I'll take the lead on this request because @matthieuh is not available.
Yes @markerikson you totally understand our request, it's to have a `name` field with the name of the endpoint, nothing more complicated than that 😄 

@phryneas regarding your point, we do not want to test the library of course. What we want to do is to generate some unit tests for reducers we created and we want to do it for a list of endpoints. For each endpoint, we want to generate the action to send in the reducer and our action needs the endpoint name. Instead of writing manually each unit test, we want to iterate on an array of endpoints for which our reducer should work.

I don't know if it's clear enough.

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.1
