### ISSUE TITLE
TS inference is wrong when using selectors with serializeQueryArgs

### ISSUE THREAD

**Issue by rumbogs** [reduxjs/redux-toolkit#2967]
Once `serializeQueryArgs` is used we shouldn't need to pass all the args to the selectors as before, only the cache key.

Note: this works functionally, it's just TS that's complaining

A small example:

```
// Under the `getAllPosts` endpoint I have
...
query: ({ region, pagination }) => ({...})
serializeQueryArgs: ({ queryArgs: { region }, endpointName }) => `${endpointName}("${region}")`,
...

// This causes a TS error because it requires `pagination` as well
// although it works perfectly fine with either signature
const { data } = api.endpoints.getAllPosts.select({ region })(state);
```

**Comment by markerikson** [comment]
Hmm. I sorta see what you're saying, but there's no meaningful way to detect that `serializeQueryArgs` has eliminated the need to pass in a cache key value (or parts of the key) because it always resolves to the same result, either statically or at runtime.  Given that, yeah, you do still need to pass in the entire cache key value to the selectors.

**Comment by rumbogs** [comment]
It isn't required though, just to satisfy TS, passing just the argument used to create the cache key works fine.

**Comment by rumbogs** [comment]
Ok, figured it might not be possible. Thanks!
