### ISSUE TITLE
Feature Request: Initial State Actions

### ISSUE THREAD

**Issue by tquinlan1992** [reduxjs/redux-toolkit#298]
Hey contributors, thanks for this library; it's awesome!

I'd love to make it better by suggesting the following idea and would love to help out on implementing it if people like the idea.

### Why
Many times with React/Redux you'll need to have `setter` actions.  For instance, an input field may be filled from a property on the state; so then you also need an action to change the input to give to `onChange`.

### How it would be used
I imagine it being something like:

```js
const initialState = {
	input1: string;
}

const nameOfReducer = 'state1';

/*
	returns:
	actions = { input1: (newValue: string;) => {type: 'state1/update_input1' }
	reducers = { 'state1/update_input1': (state, payload) => { state.input1 = payload } } 
*/
const { actions, reducers } = createActionsReducersFromInitialState(nameOfReducer, initialState);

const customAction = createAction('customAction')

createReducer(initialState, {
  [customAction]: (state, action) => { state.input1 = state.input1 + 'custom' },
  ...reducers
})
```

I wrote a redux tools library as well that has this implemented that could inspire ideas. 

https://www.npmjs.com/package/tquinlan92-typescript-redux-utils

**Comment by phryneas** [comment]
Hi there, sorry that this is gonna be a little short, but I'm on mobile and far away from my PC 🙂

This pattern of "one setter per property" (if I'm interpreting your suggestion correctly) is something we generally do not want to encourage, as it leads to people using redux in a way that is not really the intended way (like people dispatching multiple "setters" actions instead of one "event" action.)

There is a great talk on this topic that might be out interest to you: https://www.reddit.com/r/reactjs/comments/e384bm/redux_most_common_anti_pattern/

Also, please take a look at our style guide: https://redux.js.org/style-guide/style-guide/

That said, of course there are legitimate uses for "setter-like" actions, but we'd rather try to not make that am officially supported pattern in rtk as these vapid cases are more sparse than one might think.
-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by markerikson** [comment]
Yep.  It's both something we don't want to encourage, and not something that's widespread enough that it would be worth having specific APIs in RTK to support it.  Thanks for the suggestion, though!

**Comment by tquinlan1992** [comment]
Thanks for the consideration at least @phryneas and @markerikson!  Definitely agree it can encourage bad behavior.  No reason someone, like me, can't combine it with this `redux-tools` package too 🤷‍♂

**Comment by phryneas** [comment]
Yup, you can totally add your own abstractions on top, we just don't see it in the core 👍
-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
