### ISSUE TITLE
selector for entity based on selected id in store

### ISSUE THREAD

**Issue by orenklein** [reduxjs/redux-toolkit#2996]
Is it possible to use a selector's output as another selector argument?
Assuming we use entity adapter to create our state, and in addition we have `activeBookId`, meaning the chosen book id is not in component level but in redux state level.

we have the `selectById` selector from entity adapter, and `selectActiveBookId` selector

How can you create a selector to get `activeBook`? (selectActiveBook)
would you use `createSelector`?
I read in previous issues that `SelectById` is not memoized, does it have any impact on the needed solution?

The current options I got to:

```typescript
const activeBookId = useSelector(selectActiveBookId);
const activeBook = useSelector(state=>selectById(state,activeBookId))
```

or

```typescript
const activeBook = useSelector((state)=> {
  const id = selectActiveBookId(state)
  return selectById(state, id);
})
```

I assume the second one is better as it won't cause the component to rerender twice on activeId change, right?

Following is the slice

```typescript
import {
  createEntityAdapter,
  createSlice,
  configureStore,
  createSelector,
} from '@reduxjs/toolkit'

type Book = { bookId: string; title: string }

const booksAdapter = createEntityAdapter<Book>({
  // Assume IDs are stored in a field other than `book.id`
  selectId: (book) => book.bookId,
  // Keep the "all IDs" array sorted based on book titles
  sortComparer: (a, b) => a.title.localeCompare(b.title),
})

const booksSlice = createSlice({
  name: 'books',
  initialState: booksAdapter.getInitialState({
    activeBookId: undefined
  }),
  reducers: {
    // Can pass adapter functions directly as case reducers.  Because we're passing this
    // as a value, `createSlice` will auto-generate the `bookAdded` action type / creator
    bookAdded: booksAdapter.addOne,
    booksReceived(state, action) {
      // Or, call them as "mutating" helpers in a case reducer
      booksAdapter.setAll(state, action.payload.books)
    },
  },
})

const store = configureStore({
  reducer: {
    books: booksSlice.reducer,
  },
})

type RootState = ReturnType<typeof store.getState>


const {selectById} = booksAdapter.getSelectors<RootState>(
  (state) => state.books
)

const selectActiveBookId = (state: RootState) => state.books.activeBookId

const selectActiveBook = ??? 
```

**Comment by markerikson** [comment]
_Technically_ `selectById` is memoized in that it's made with Reselect's `createSelector`, but that's an implementation detail that doesn't matter. Per https://redux.js.org/usage/deriving-data-selectors#balance-selector-usage , any selector that just looks up and immediately returns a value without _deriving_ anything doesn't actually need to be memoized in the first place.

Both of the `useSelector` snippets you showed will work.  I would assume they would _both_ end up causing the component to re-render, because any change to `activeId` will end up returning a different reference from `selectById`.  However, both will only cause the component to render once, because React-Redux batches React updates (and React batches them anyway as of React 18).

**Comment by orenklein** [comment]
Perfect. Really appreciate the quick response, thank you!
