### ISSUE TITLE
[Question] Getting type error when mutating state in reducer

### ISSUE THREAD

**Issue by Hektar90** [reduxjs/redux-toolkit#3005]
Hello,

i hope someone can tell me what i am doing wrong. I created a slice and defined a reducer with one action in it. When i try to assign a new value i get an error. 

I did a minimal sandbox of my concern: 
https://codesandbox.io/s/ecstatic-parm-efx98q?file=/src/redux/slices/globalSlice.ts

The error is: Type 'Socket | null' is not assignable to type 'WritableDraft<Socket | null'>.

For primitive types like boolean or number I have no issues. 

Thank you in advance

**Comment by markerikson** [comment]
Sockets are not "state", and don't belong in the Redux store:

- https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions

(The actual error here is likely due to TS complexities around how the `Socket` type is defined, but the real answer is "don't put socket instances into Redux".)
