### ISSUE TITLE
Redux action is sometimes an anonymous function

### ISSUE THREAD

**Issue by OmgImAlexis** [reduxjs/redux-toolkit#3018]
Using v1.8.5 of `@reduxjs/toolkit'`.

Not sure if I'm missing something here or if this is a bug. I was expecting to always get an action object from the `action` argument but it seems like I get `pending`, `anonymous function` and then `fulfilled`.

Just incase it's something todo with typescript I've included the compiled code at the bottom.

```ts
import { createListenerMiddleware, createAsyncThunk, configureStore, createSlice } from '@reduxjs/toolkit';
const listeningMiddleware = createListenerMiddleware();

const initialState = {};

const config = createSlice({
	name: 'config',
	initialState,
	reducers: {}
});

const store = configureStore({
	reducer: {
		config: config.reducer
	},
	middleware: defaultMiddleware => defaultMiddleware({}).prepend(listeningMiddleware.middleware)
});

const enableConfigListener = () => listeningMiddleware.startListening({
	predicate(action) {
		console.log(action);
		return false;
	},
	effect() {}
});

enableConfigListener();

const fakeThunk = createAsyncThunk('config/fakeThunk', () => 1);

store.dispatch(fakeThunk());

setInterval(() => {
	console.log(new Date());
}, 1000);
```
```
root@fa1bf889ac4c:/app# node ./dist/x.cjs
{
  type: 'config/fakeThunk/pending',
  payload: undefined,
  meta: {
    arg: undefined,
    requestId: 'cPSUY0KPdy1Hnh3H-dJpI',
    requestStatus: 'pending'
  }
}
[Function (anonymous)]
{
  type: 'config/fakeThunk/fulfilled',
  payload: 1,
  meta: {
    arg: undefined,
    requestId: 'cPSUY0KPdy1Hnh3H-dJpI',
    requestStatus: 'fulfilled'
  }
}
2022-12-20T04:58:29.705Z
```

```js
root@fa1bf889ac4c:/app# cat dist/x.cjs
"use strict";
var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

// x.ts
var import_toolkit = require("@reduxjs/toolkit");
var listeningMiddleware = (0, import_toolkit.createListenerMiddleware)();
var initialState = {};
var config = (0, import_toolkit.createSlice)({
  name: "config",
  initialState,
  reducers: {}
});
var store = (0, import_toolkit.configureStore)({
  reducer: {
    config: config.reducer
  },
  middleware: (defaultMiddleware) => defaultMiddleware({}).prepend(listeningMiddleware.middleware)
});
var enableConfigListener = /* @__PURE__ */ __name(() => listeningMiddleware.startListening({
  predicate(action) {
    console.log(action);
    return false;
  },
  effect() {
  }
}), "enableConfigListener");
enableConfigListener();
var fakeThunk = (0, import_toolkit.createAsyncThunk)("config/fakeThunk", () => 1);
store.dispatch(fakeThunk());
setInterval(() => {
  console.log(new Date());
}, 1e3);
//# sourceMappingURL=x.cjs.map
```

**Comment by markerikson** [comment]
If you've put the listener middleware in front of the thunk middleware, then yes, that's to be expected any time you dispatch a thunk (which is indeed a function: https://redux.js.org/usage/writing-logic-thunks ).  Middleware run in sequence, passing whatever the current "action" is from one middleware to the next in the pipeline.  If the listener middleware runs before the thunk middleware, it will see those thunk functions before the thunk middleware has a chance to intercept and stop them from continuing.

**Comment by OmgImAlexis** [comment]
Okay that makes sense, thanks for the explanation. 👍 

Is there a better recommended way to attach the listener middleware before all others but after the thunk middleware?

**Comment by markerikson** [comment]
In a dev build, the default middleware order is `[thunk, immutability, serializability]`.  In prod, it's just `[thunk]`. 

Looking at the docs, looks like I specifically showed prepending it because it _can_ receive actions with functions inside (ie, `dispatch(addListener({effect: someFunction}))`, so putting the listener middleware first avoids the "non-serializable value detected" warning:

https://redux-toolkit.js.org/api/createListenerMiddleware#basic-usage

So, in general, the options are:

- Put the listener middleware first via `.prepend()` and be aware that the `action` may sometimes _not_ be a plain action object.  Most of the time this is fine, especially if you're checking `action.type === "some/action"` (which would run okay because `action.type` on a thunk function is undefined).
- Put the listener middleware at the end via `.concat()`, and _if_ you ever do `dispatch(addListener())`, just ignore the serialization warning.  the listener middleware will intercept that action and it never reaches the reducers anyway

**Comment by OmgImAlexis** [comment]
Thank you so much for you help. 🙏
