### ISSUE TITLE
How to test initial state?

### ISSUE THREAD

**Issue by janhesters** [reduxjs/redux-toolkit#306]
I always thought that every reducer should return its initial state when called without arguments.

Today, I tried out Redux Toolkit. Suddenly, all my tests for initial state broke. They look like this:

```js
const createState = ({ displayName = 'Anonymous', roomName = '' } = {}) => ({
  displayName,
  roomName,
});

describe('join reducer', async assert => {
  assert({
    given: 'no arguments',
    should: 'return the valid initial state',
    actual: reducer(),
    expected: createState(),
  });
});
``` 

The error message was:

```js
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
```

which is caused by [this code](https://github.com/reduxjs/redux-toolkit/blob/master/src/createReducer.ts#L107):

```ts
return function(state = initialState, action): S {
  // @ts-ignore createNextState() produces an Immutable<Draft<S>> rather
  // than an Immutable<S>, and TypeScript cannot find out how to reconcile
  // these two types.
  return createNextState(state, (draft: Draft<S>) => {
    const caseReducer = actionsMap[action.type]
    return caseReducer ? caseReducer(draft, action) : undefined
  })
}
```

The quick fix would be to change the function signature to have a default value for action:

```ts
return function(state = initialState, { type, ...actionRest } = {}): S {
  // @ts-ignore createNextState() produces an Immutable<Draft<S>> rather
  // than an Immutable<S>, and TypeScript cannot find out how to reconcile
  // these two types.
  return createNextState(state, (draft: Draft<S>) => {
    const caseReducer = actionsMap[type]
    return caseReducer ? caseReducer(draft, { type, ...actionRest }) : state
  })
}
```

Then I found out, that maybe [Redux reducers aren't supposed to work without an action](https://github.com/reduxjs/redux-toolkit/issues/171#issuecomment-520236466). To me this doesn't make sense because why would you avoid a sane default? Why provoke the crash? If I'm wrong, I'll gladly make a PR and fix this bug.

Anyways, my question is how do you test that the reducer has the correct initial state, if you can't call the reducer without an action? Do you have to do something like this (arguably a lot less pretty)?

```js
reducer(undefined, { type: undefined });
```

**Comment by phryneas** [comment]
A reducer is meant to be always called with two arguments - just because outside of a test, a reducer is not meant to be called manually at any given time, and `redux` always calls reducers with two arguments.

In the case of the intial state, redux would always be calling `currentReducer(currentState, action)`, with `currentState` being `undefined` and `action` being a valid action, in most cases of type `@@redux/INIT${randomString()}`.

If you are calling a reducer without arguments, you might be testing *something*, but definitely **not** the actual behaviour of redux calling the reducer with a yet-unknown state.

So I'd rather not encourage people testing for *something else* by providing a default argument there.

Also, this current behaviour is consistent with what [the redux docs on reducers](https://redux.js.org/basics/reducers#handling-more-actions) are saying: `action` is never optional (`action.type` is being used right in the switch statement without a default value or testing if `action` is `undefined`).
I don't think it would be a good idea to intransparently introduce different behaviour here.

**Comment by janhesters** [comment]
@phryneas Thank you for the explanation, Lenz 🙏 

I saw many code basis, including mine, which use reducers frequently without arguments.

For [Next.js you need to know the `initialState`](https://github.com/zeit/next.js/blob/canary/examples/with-redux/lib/redux.js). Or for the `useReducer` hook:

```js
import React, { useReducer } from 'react';
import Counter from './click-counter-component';
import { reducer, click } from './click-counter-reducer';
export default () => {
  const [clicks, dispatch] = useReducer(reducer, reducer());
  return <Counter
    clicks={ clicks }
    onClick={() => dispatch(click())}
  />;
};
```

But I guess, since this is opinionated there is no debating 🤷‍♂ 
I think [`autodux`](https://github.com/ericelliott/autodux) features sane state defaults, so I might just use that instead 😊

**Comment by phryneas** [comment]
I'd just export the `initialState` honestly. 

Testing the RTK-generated reducer for the correct initialState would be something that I personally would avoid as I personally try to avoid testing external dependencies and concentrate on my own code. In the end, if you have at least one integration test, you test the library behaviour *enough* in my eyes - for everything else, the library itself should have tests.
(We do have one test that tests the initialState, but only in combination with something else - if you want to do a PR and add a test that explicitly tests the `initialState` functionality, that would be very welcome.)

As for your `useReducer` example: why don't you just create a hook for that, like this:
```js
function useSliceReducer(slice) {
  return useReducer(slice.reducer, slice.reducer(undefined, {type: 'init'});
}
```
In the long run, this will save you even some code - and you could apply some optimizations that might be unweildy to write other ways .
For example, your code, as well as my example would be running the reducer at every render - this would probably be better:
```js
function useSliceReducer(slice) {
  return useReducer(slice.reducer, undefined, () => slice.reducer(undefined, {type: 'init'});
}
```

And as for next.js, looking at the code I see that they have some preloaded state, but from what I read there should not be any requirement for every reducer's state to be pre-initialized. I might be wrong though, I haven't used next yet. Have you tried using it without specifying an initialized state?

**Comment by markerikson** [comment]
To clarify the original question:

A reducer should always return its original state _when it is called with an undefined `state` argument_.

When used with Redux, a reducer will _always_ be called with a valid action argument that has a `.type` field.

So the answer here is that the original test code was buggy, because reducers are not supposed to be called without an action argument.
