### ISSUE TITLE
[IE] Spread operator usage inside createReducer

### ISSUE THREAD

**Issue by belliAndrea** [reduxjs/redux-toolkit#309]
Have a problem concerning the usage of the spread operator inside createReducer.
I love reduxToolkit but i don't like immer, so i use the old way for modify the objects.

BUG:
My application works fine on Chrome/Firefox bui i get a blank page in IE and Edge (not the chromium one).  After struggling a lot i found that the usage of the spread operator inside the reducer cause the bug. 

SOLUTION:
I changed the reducers that use the spread operator back into the old way (without createReducer) and now my application runs fine on all browsers

I tried all the polyfill. i don't think it is a polyfill problem. I think it is related to immer.

**Comment by markerikson** [comment]
That doesn't sound like anything that's actually a problem in Redux Toolkit or Immer.  Can you put together a CodeSandbox that actually demonstrates the issue?

**Comment by phryneas** [comment]
Our build output does not contain spread operators, I just validated that.

Are you talking about the spread operator in *your own code*? Then you will have to transpile your code for IE & Edge before bundline/delivering it, because those two [do not support the spread operator](https://caniuse.com/#feat=mdn-javascript_operators_spread_spread_in_object_literals)

**Comment by markerikson** [comment]
Yep.  As I said, not an issue in our own code, so closing this.
