### ISSUE TITLE
Explicitly type redux thunk extras in RTK Query endpoints

### ISSUE THREAD

**Issue by dbartholomae** [reduxjs/redux-toolkit#3125]
Is there an appetite for typing the `extra` argument provided to `onQueryStarted`? Currently it is [typed as `unknown`](https://github.com/reduxjs/redux-toolkit/blob/d2d0f708abe3c51ae68bd5a96d83826f8897c355/packages/toolkit/src/query/core/buildMiddleware/cacheLifecycle.ts#L76). Allowing to type it would require adding a few more generics, as it needs to be passed through from `createApi`.
Maybe you already looked into it and decided against it (I remember reading about decisions for Redux like this due to cyclic dependencies)? If you have the appetite for this kind of change, I could try my hand on a PR.

**Comment by phryneas** [comment]
From the back of my mind, there are multiple problems:
* it cannot be manually specified as that would break inference for the `createApi`
* it cannot be inferred because it is not part of any input - the thunk middleware exists in parallel to the RTKQ 
* even if we would find a way to add it, it would probably add a *ton* of type complexity throughout all layers

So from that: if you have a good idea, let's hear it, but back then, I just decided that it's probably not worth it.

**Comment by dbartholomae** [comment]
There would be a workaround with defining this type in a higher-order function, I think, but that would create even more complexity.
Another alternative that would only partially solve the problem, but is used already in redux itself, would be to use a type from a globally declared namespace and then allow users to overwrite the global namespace type.

**Comment by phryneas** [comment]
We have deprecated and removed those global declarations as they can cause all kinds of problems like poisoning through 3rd-party-packages that are installed but unused or generally conflicts in monorepos.

**Comment by dbartholomae** [comment]
Thanks! I think then this might have to wait until TypeScript figures out how to do partial generics :/
