### ISSUE TITLE
Upgrade Immer version

### ISSUE THREAD

**Issue by yoshicarroll** [reduxjs/redux-toolkit#313]
Hello,

Loving what you're doing with the Toolkit, it greatly cleans up the Redux boilerplate.

I'm bringing the Toolkit into a project where I already have Immer@^5.0.0 and since the Toolkit is using Immer@^4.0.1 I'm getting it installed twice.

Do you have plans to update Immer soon?

Thanks!

**Comment by phryneas** [comment]
As it stands, `immer` v5 is 50% bigger than v4 and has no features that are useful for RTK, so until some tree-shaking issues on their side is resolved, we'd prefer not to. 

If you're using `yarn`, you can use [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) to tell it to only install one version of `immer`. RTK should run perfectly fine with v5, we just don't want to make it the default because of above reasons for now.

**Comment by yoshicarroll** [comment]
Got it. Thank you!

I tried using Immer via the RTK export, which would remove the extra version management, but I need Immer's `setAutoFreeze` which RTK does not export.

**Comment by phryneas** [comment]
You should be able to directly import it from `immer` though - after all, that should be installed when RTK is installed ;)
We're only re-exporting what's relevant for actual RTK use.

**Comment by yoshicarroll** [comment]
Now that I think about it, are Maps and Sets not valid for use in Redux stores? Because they're not serializable?

**Comment by phryneas** [comment]
Exactly.

**Comment by yoshicarroll** [comment]
Cool. Thanks a lot for your help! :)

**Comment by markerikson** [comment]
Note that I filed https://github.com/immerjs/immer/issues/500 yesterday to see if they can maybe make some improvements to tree shaking on their end.
