### ISSUE TITLE
Support: grpc-web codegen

### ISSUE THREAD

**Issue by kahirokunn** [reduxjs/redux-toolkit#3190]
connect and others are becoming popular.
What about adding grpc-web code generation to RTK Query?

**Comment by markerikson** [comment]
@kahirokunn : Probably not something we'd plan to do ourselves, for several reasons:

- Lenz is the only one who's really worked on the codegen packages, and he's been very busy with work changes and other personal things going on, so he hasn't even had time to work on those lately
- We really don't have time to maintain another codegen package
- We see a lot of OpenAPI and GraphQL usage in the ecosystem, but tbh I don't see use of gRPC being discussed publicly.  It's possible it's being used internally in companies, but if so that usage isn't being publicized very much.

**Comment by kahirokunn** [comment]
@markerikson 
I see. 👀 
By the way, I am considering contributing, would that be acceptable?

**Comment by markerikson** [comment]
We're definitely interested in contributions to RTK in general :) The big question is whether we'd specifically want to have another codegen in this repo. @phryneas , thoughts?

**Comment by kahirokunn** [comment]
As you say, I don't see any discussion at all.
However, I live in Japan and more and more companies are implementing gRPC-Web in CONNECT.
If we could integrate gRPC-Web code generation into RTK Query and use gRPC-Web with RTK Query, I believe more organizations would use RTK Query.

**Comment by phryneas** [comment]
I would want to see this as a separate package. We can pull it into the `@rtk-query` namespace once it is stable, but for now I'd like to keep it outside of the RTK repository.

**Comment by kahirokunn** [comment]
Understood. I will write the code.

**Comment by LeVadim** [comment]
Hi @kahirokunn ! Did you end up creating a package that would integrate gRPC?

**Comment by kahirokunn** [comment]
Sorry, I am thinking of leaving gRPC web adoption and I am not currently working on this
