### ISSUE TITLE
When I use createAsyncAction with condition that return false it throws ConditionError if I call unwrap

### ISSUE THREAD

**Issue by burya4ok** [reduxjs/redux-toolkit#3204]

**Comment by markerikson** [comment]
Yes, that's an expected part of the implementation.

**Comment by markerikson** [comment]
@burya4ok : I'm not sure what you're asking, or why.

`createAsyncThunk` uses `ConditionError` to indicate that "this thunk did _not_ run, because the bailout check said not to run it".  

The logic that _dispatched_ the thunk may or may not care about any of that.

What are you actually trying to accomplish?
