### ISSUE TITLE
TypeScript Docs in "Defining the Initial State Type" can improve 

### ISSUE THREAD

**Issue by dMarin178** [reduxjs/redux-toolkit#3219]
I've been learning redux-toolkit using the docs by creating a pokemon app, but when i want to use an action to change the State it gave an error due to the SliceState. The docs show this:
```
type SliceState = { state: 'loading' } | { state: 'finished'; data: string }

// First approach: define the initial state using that type
const initialState: SliceState = { state: 'loading' }

createSlice({
  name: 'test1',
  initialState, // type SliceState is inferred for the state of the slice
  reducers: {},
})

// Or, cast the initial state as necessary
createSlice({
  name: 'test2',
  initialState: { state: 'loading' } as SliceState,
  reducers: {},
})
```

**Mi code **

```
import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { Pokemon } from "../../../types";

type SliceState =  { status: 'loading'} | { status: 'finished'; pokemons: Pokemon[]};

const initialState = {
    status: 'loading',
} as SliceState;

const pokemonSlice = createSlice({
  name: "pokemons",
  initialState,
  reducers: {
    setPokemons: (state , action : PayloadAction<Pokemon[]>) => {
        state.status = 'finished';
        state.pokemons = action.payload;
    }
  }
})

export default pokemonSlice;
```

And gave me this error 
`Property 'pokemons' does not exist on type 'WritableDraft<{ status: "loading"; }> | WritableDraft<{ status: "finished"; pokemons: Pokemon[]; }>'.
Property 'pokemons' does not exist on type 'WritableDraft<{ status: "loading"; }>'.ts(2339)`

so i've had to change the SliceState to 
` { status: 'loading' ; pokemons: Pokemon[]} | { status: 'finished'; pokemons: Pokemon[]};`
so the error disappears.

In the docs don't explicit this, so maybe it can be added.

Sorry for my English :( , hope you undestand me.

**Comment by markerikson** [comment]
Yeah, the problem here is that you defined `SliceState` as a union.  `state.pokemons` only exists in _one_ of the possible options, so TS is (correctly) telling you that you can't assign to it.  You'd have to narrow it down, like `if (state.status === "finished") { state.pokemons = action.payload }`.

I don't immediately see a lot of use for trying to define the _entire_ slice state as a union.  Having `state.status` be a union itself is fine, but typically you want to have all known fields exist in the slice state type.  In other words, either just do `{status: 'loading' | 'finished", pokemons: Pokemon[] | null}`, or do `{status: 'loading', pokemons: null} | {status: 'finished', pokemons: Pokemon[]}`, so at least TS acknowledges that the field is there.

**Comment by dMarin178** [comment]
I understand, thanks for the quick response.
