### ISSUE TITLE
Failed types with createSlice

### ISSUE THREAD

**Issue by sreetamdas** [reduxjs/redux-toolkit#323]
I'm relatively new to typescript, so please do correct me if I'm making some anti-patterns. Anyway, in my reducer I am constructing a union type for the auth slice. I followed the tutorials in the docs here and was able to correctly type the `action` as well. However, with the following code, I've got typescript telling me that:

```
type TAuthState =
	| false
	| {
			username: string;
	  };

const authSlice = createSlice({
	name: "auth",
	initialState: false as TAuthState,
	reducers: {
		login(state, action: PayloadAction<TAuthState>) {
			const { username } = action.payload;
			state.username = username;
		},
	},
});
```

> src/features/auth/index.ts:14:12 - error TS2339: Property 'username' does not exist on type 'TAuthState'.
>               const { username } = action.payload;
>                         ~~~~~~~~
> src/features/auth/index.ts:15:10 - error TS2339: Property 'username' does not exist on type 'false | { username: string; }'.
>   Property 'username' does not exist on type 'false'.
>               state.username = username;
>                       ~~~~~~~~
> 

What am I doing wrong? Again, sorry if this is just me being bad at typescript and not anything to do with RTK.

**Comment by markerikson** [comment]
I'm pretty sure it's because your state type is declared to be _either_ a boolean or an object, but inside the reducer you haven't told the TS compiler that it really _is_ an object at that point in time.  And, given your current code, the line `state.username = username` _is_ a bug - the initial state is `false`, and so that's not an object.

I'd strongly encourage you to just make the state an object that looks like `{username: string, loggedIn: boolean}`.

**Comment by sreetamdas** [comment]
Ah, makes sense. Thanks a lot :D

**Comment by pumuckelo** [comment]
@markerikson  I have a similar problem 
```

export interface Profile {
  username: string;
  createdAt: Date;
  verified: boolean;
}
export interface FetchedProfileState {
  fetching: boolean;
  fetched: true;
  data: Profile;
}

export interface PendingProfileState {
  fetching: boolean;
  fetched: false;
}

export type ProfileState = FetchedProfileState | PendingProfileState;
```

I have this as a profile state so when I try to access the data in my components I am forced to check if the data is fetched, the problem is that I cannot change fetched to true in my reducer, or set the data

I think it has something to do with the WritableDraft of immer. I'm not that good in typescript

Do you have an idea?

**Comment by p6h6di** [comment]
### 
efwefef
- >  `@ewfref
`errrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr`
- [ ]****`
