### ISSUE TITLE
Is there any way to cache the Mutations. 

### ISSUE THREAD

**Issue by Vansh-k** [reduxjs/redux-toolkit#3265]
I am building an application and using many mutations so making the redundant request is giving a toll at the response time.

**Comment by Vansh-k** [comment]
I want that when a mutation with the same params is called it shall use the same result as it got before stored in cache so it will avoid 300ms of loading time or extra request that goes to backend if we already have the response.

**Comment by phryneas** [comment]
Generally, no.
The conceptual point of mutations is to change something on the server, not to retrieve data from the server. Their responses are meant to only be short-lived.

That said, 300ms is a very long loading time. I guess by tweaking your server, you could likely get that into the sub-100-region and overall have far more performance benefits.

**Comment by Vansh-k** [comment]
Okay.. I get that.. Could you tell me then.. What exactly fixedCacheKey does in the mutation.. As the mutation is storing the data to cache and is able to share the data among different components

Reference to shared mutation result (fixedCacheKey) docs -> https://redux-toolkit.js.org/rtk-query/usage/mutations#shared-mutation-results

**Comment by phryneas** [comment]
`fixedCacheKey` is a way of storing a mutation result in a pre-known place and disables automatic removal on unsubscribe, so that result will stay around in the cache for a long time.

The intent of it is not to store a lot of data, but so you can have a button that triggers a mutation on one end of your application, while displaying a status bar/spinner/loading indicator in a completely different component tree. It's purpose is not really the attached `data`, that's more there as a side effect.

**Comment by phryneas** [comment]
Closing this now as it doesn't seem actionable on our part.
