### ISSUE TITLE
Dispatching an action creator should result in an error

### ISSUE THREAD

**Issue by thSoft** [reduxjs/redux-toolkit#3299]
[This example](https://codesandbox.io/s/counter-typescript-redux-toolkit-forked-oe2snk?file=/src/App.tsx) contains a subtle bug: in line 15, the action _creator_ is dispatched instead of the action itself.

If you click on the increment button, nothing happens and the programmer might be confused why, so I think this should be an error either at compile-time (I'm aware of https://github.com/reduxjs/redux-toolkit/issues/2896 but it doesn't explicitly mention this case) or at runtime (maybe a warning should be printed when an action is not handled by any reducer?).

**Comment by markerikson** [comment]
It is subtle, but I don't think there's much we we can do about it.

Passing a function to `dispatch` is legal, _if_ you have the thunk middleware installed (and RTK's `configureStore` sets that up by default).  It's just that in this case, the function is an action creator, and not a thunk.

Note that this example will _not_ result in an action being dispatched.  Instead, the thunk middleware will see "hey, it's a function", call it, and _not_ pass anything onwards:

- https://redux.js.org/usage/writing-logic-thunks#how-does-the-middleware-work

so what happens is "nothing at all", rather than "some action gets dispatched".

Also, it's actually entirely legal and fine to have an action dispatched that does not result in any state updates, which goes along with our recommendation to [model actions as "events"](https://redux.js.org/style-guide/#model-actions-as-events-not-setters).

The only potential improvement we could make here would be to somehow improve the TS types to indicate that functions resembling action creators are not allowed even when you have the thunk middleware added to the store... but that wouldn't help in this specific case because the example is plain JS.

**Comment by EskiMojo14** [comment]
if you're using a thunk middleware, it's valid to dispatch functions and you wouldn't get a runtime error (the thunk middleware would just call it with dispatch)

```ts
dispatch(increment) === increment(dispatch, getState)
```

if you're not, then the final dispatch in the redux store would throw a [runtime error](https://github.com/reduxjs/redux/blob/master/src/createStore.ts#L269).

type-wise, this is actually unrelated to the thunk middleware - RTK action creators have a static .type property, meaning they're assignable to Action and therefore AnyAction.
