### ISSUE TITLE
Bind dispatch to actions on creation.

### ISSUE THREAD

**Issue by webmikey1337** [reduxjs/redux-toolkit#330]
I thought it would reduce some boilerplate and be a little easier to work with actions if we could just call them without using dispatch every time
Like for example
```jsx
// component with just action
import { action } from '~actions'
import React from 'react'
import { useDispatch } from 'react-redux'
import { bindActionCreators } from '@reduxjs/toolkit'

export const Foo = () => {
  const dispatch = useDispatch()
  const handleAction = bindActionCreators(action, dispatch)

  return <div onClick={()=>{handleAction()}}></div>
}
```
and
```jsx
// component with (action+dispatch)
import { action } from '~actions'
import React from 'react'

export const Foo = () => {
  return <div onClick={()=>{action()}}></div>
}
```
Also for thunks
```jsx
// thunk with just action
export const fooThunk = () => async dispatch => {
  //...
  dispatch(actionFoo())
  //...
  dispatch(actionBar())
  //...
  dispatch(actionFooBar())
}
```
and
```jsx
// thunk with (action+dispatch) 
export const fooThunk= async () => {
  //...
  actionFoo()
  //...
  actionBar()
  //...
  actionFooBar()
}
```

Implemented with some map function when you make a slice
```jsx
import {bindWithDispatch} from "@reduxjs/toolkit"
//...
export const {
  foo,
  bar,
  baz
} = bindWithDispatch(mySlice.actions)
```
What do you think?

**Comment by markerikson** [comment]
We're definitely not going to auto-bind action creators at definition time, if that's what you're asking.  If you want to pre-bind them in your own app code, you can, but that's up to you.

In general, though, we recommend either [using the "object shorthand" form of `mapDispatch` with `connect`](https://react-redux.js.org/using-react-redux/connect-mapdispatch#defining-mapdispatchtoprops-as-an-object) to bind action creators, or `[_not_ binding action creators and calling `dispatch(someAction())` with `useDispatch`](https://react-redux.js.org/api/hooks#usedispatch).

**Comment by oleole90** [comment]
For any future visitors; this is how I end up binding actions:

**VideoSlice.js**
```
export default videoSlice;
```

**Page.js**
```
import { bindActionCreators } from 'redux';
import VideoSlice from '../../redux/VideoSlice';
const Player = () => {
    const { play, pause, stop } = bindActionCreators(VideoSlice.actions, dispatch);
    return (...);
};
```

**Comment by bobsmits** [comment]
I had the same idea actually. I wanted to make a feature request but then i saw this issue. I made my own idea about createSlice about a year and a half ago that also binded dispatch. The only downside that I found, it needs access to the store. I bet it can be handled smarter by passing the store to the reducer in the createStore method.

Here is my version of it.
redux/createReducer.js:
```
import { createAction, handleActions } from 'redux-actions';
import { getStore } from './store';

/*
  This creates a reducer without all the boi the actions.
  And this maps dispatch to all the actions.

  @returns {
    reducer: reducer to pass to create store
    actions: methods for all the reducer methods with dispatsch bind to it.
  }

  Adds an RESET action to reset to the default state
*/

function createMappedAction(name) {
  const action = createAction(name);

  return (payload) => {
    getStore().dispatch(action(payload));
  };
}

export default function createReducer(reducerName, actions, defaultValues) {
  const nameSpacedActions = {};
  const mappedActions = {};

  Object.keys(actions).forEach((action) => {
    const reducerActionName = `${reducerName}/${action}`.toUpperCase();

    nameSpacedActions[reducerActionName] = actions[action];
    mappedActions[action] = createMappedAction(reducerActionName);
  });

  nameSpacedActions.RESET = () => {
    return defaultValues;
  };

  return {
    reducer: handleActions(nameSpacedActions, defaultValues),
    actions: mappedActions,
  };
}
```

Then you can create a reducer this way.
reducers/user.js:
```
import Immutable from 'immutable';
import createReducer from 'lib/redux/createReducer';

const defaultState = Immutable.fromJS({
  name: 0,
  email: 'email@example.com',
});

export const { actions, reducer } = createReducer('user', {
  setName: (state, action) => {
    return state.set('name', action.payload);
  },

  setEmail: (state, action) => {
    return state.set('email', action.payload);
  },
}, defaultState);
```

And the createRecucer needs acces so to the store i handled that with an getStore method because we do some aSyncStorage loading.
simplified version of store.js:
```
const store = createStore(...);

export function getStore() {
  return store;
}
```

I can access my actions anywhere by importing them: 
```
import { actions } from 'reducers/user'  
actions.setEmail('bob@example.com')

```
And i have access to my store with getStore which is rather handy.

@markerikson what is the reason you do not want to auto bind dispatch? Seems like a lot of boiler plate that is exactly the same for everyone.

**Comment by markerikson** [comment]
Because "it needs access to the store" is exactly the issue.  You're not only creating circular import references, you're _forcing_ that code to _only_ work with the real app store, which makes it not easily testable.

We have _always_ advised to [not import the store directly into the rest of your codebase](https://redux.js.org/faq/store-setup#can-or-should-i-create-multiple-stores-can-i-import-my-store-directly-and-use-it-in-components-myself).
