### ISSUE TITLE
2.0 alpha 6: Change in behavior for redux saga subscriptions (due to removal of .toString() probably)

### ISSUE THREAD

**Issue by einarq** [reduxjs/redux-toolkit#3471]
Previously this worked fine:

`yield takeEvery(cAT.fulfilled, saga);`

Now we have to do this instead:
`yield takeEvery(cAT.fulfilled.type, saga);`

**Comment by EskiMojo14** [comment]
you can use .match instead for better typing than .type can achieve: 
`yield takeEvery(cAT.fulfilled.match, saga);`

but yes, this is because the toString override was removed in https://github.com/reduxjs/redux-toolkit/pull/3425.

essentially there aren't any use cases that shouldn't be able to be covered with .match or .type. it's neat that redux-saga included support for stringifiable action creators, but using .match is much less implicit and fragile (toString wouldn't work properly for non-string action types, though to be fair you're not allowed those in Redux 5 anyway)

we may consider adding the toString override back to avoid breaking things unnecessarily, but better options have existed for a good while and we want to encourage using those instead going forward.

**Comment by einarq** [comment]
I don't have a strong opinion on this, except to say that the removal of
toString also causes issues in reducers etc, where a cAT action is used in
extraReducers. I now need to use .type everywhere, otherwise the state
won't update.
So if you do go ahead with this change, then perhaps consider releasing a
codemod? Personally I'm fine with adapting my code, but others might not be
too happy with it, and could cause some friction perhaps.

**Comment by EskiMojo14** [comment]
could you make a replication of extraReducers not working? the map builder specifically looks for a .type property, so it should be fine.

https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/src/mapBuilders.ts#L158

**Comment by einarq** [comment]
So this works fine it seems, it was related to some workaround I had put in place after the deprecation of the dictionary style reducer syntax of extraReducers.

I still had a dictionary of the reducers, and then this code to  register them.

    Object.entries(actionHandlers).forEach((entry) => {
      builder.addCase(entry[0], entry[1]);
    });

This no longer works unless its cAT.pending.type, only works when doing builder.addCase(cAT.pending) directly.
This is fine of course, so never mind :)

**Comment by markerikson** [comment]
Seems like there's nothing we need to do here, then?
