### ISSUE TITLE
How can mock unwrap() in dispatch(asyncThunckFunc()).unwrap() using React Testing Library

### ISSUE THREAD

**Issue by hvallu1** [reduxjs/redux-toolkit#3489]
Hi Team, I am unable to mock unwrap() in dispatch(asyncThunckFunc()).unwrap() using React Testing Library.

**Sample Code:**
appDispatch(validatePageComponents())
      .unwrap()
      .then((validatePageComponentsResponse: IValidatePageComponentsResponse) => {
        // Logic
      });

**Test Case Example:** 
it("should call validate form method", async () => {
    render(setupBorrowerComponent());
    const continueButton = screen.getByTestId("borrower-component__group-continue--button");
    await userEvent.click(continueButton);
    //Need to assert
  });

**Issue:**
TypeError: Cannot read properties of undefined (reading 'unwrap')

Please suggest, How can I mock unwrap() and let me know If I need to provide any information. Thank in advance :)

**Comment by oleksandr-p-wl** [comment]
Hi @hvallu1 !
I had the similar problem. In my particular case I found this workaround (in test code):

`jest.spyOn(sessionThunks, 'resetPassword').mockImplementation(createAppAsyncThunk('session/resetPassword', () => {}));`

Code above resolved **TypeError: Cannot read properties of undefined (reading 'unwrap')** caused inside a component I was testing.

I'm not sure that this is a good approach. But in my case I couldn’t use requests interception approach because of some complicated internal SDK logic I had to use. I needed to mock the whole asyncThunckFunc, but with unwrap in component I faced the same issue. I'm just curious @markerikson is this a valid workaround?

**Comment by stasguma** [comment]
I've just faced with the same problem. I have an `unwrap()` function in my async thunk and test fails.

![image](https://github.com/reduxjs/redux-toolkit/assets/15160733/4a60973d-6140-4910-a801-997e401dfd57)

![image](https://github.com/reduxjs/redux-toolkit/assets/15160733/dc0e1f7d-e755-4584-b3c8-9f2654d82f70)
