### ISSUE TITLE
Fix all uses of `/dist/` in type imports

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#3516]
Per Andrew Branch, these are bad and breaking things:

```ts

import type { Api } from '@reduxjs/toolkit/dist/query/apiTypes'

import type {
  QuerySubState,
  SubscriptionOptions,
  QueryKeys,
  RootState,
} from '@reduxjs/toolkit/dist/query/core/apiState'

// etc
```

They should just import from the packages instead, like `@reduxjs/toolkit/query`.

**Comment by eric-crowell** [comment]
Would it be preferred to use relative pathing to these types instead of from the package's main export?
Otherwise, all those types would also have to be publicly exported and supported? (I think, maybe I'm wrong)

Wanted to ask since I was already patching a lot of this to fix my projects using 2.0. Hoping I can put out a PR for this issue.

**Comment by phryneas** [comment]
@eric-crowell  That would lead the packages to merge into each other at bundling, which you definitely don't want to happen.

**Comment by eric-crowell** [comment]
> @eric-crowell  That would lead the packages to merge into each other at bundling, which you definitely don't want to happen.

Ah, okay. I agree, I definitely don't want that to happen. Will keep with the suggested fix if I can make a PR.

**Comment by markerikson** [comment]
Done in #3672 .
