### ISSUE TITLE
Missleading vscode code suggestion

### ISSUE THREAD

**Issue by vikyw89** [reduxjs/redux-toolkit#3613]
Rtk query gives a missleading code suggestion on vscode (while pressing ctrl space).

**Comment by phryneas** [comment]
Not even a screenshot? That really helps us diagnose the problem!

**Comment by vikyw89** [comment]
> Not even a screenshot? That really helps us diagnose the problem!

Will add tomorrow, currently away from vscode. Thank you for the fast response :)

**Comment by vikyw89** [comment]
Under the fetchBaseQuery object, it suggested methods that are not available in the documentation
The doc only has these methods available, 
![image](https://github.com/reduxjs/redux-toolkit/assets/112059651/e67c00af-cb3b-4cbc-a9bf-0898531162af)
src= https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery
But on vs code, here's what is suggested:
![Screenshot from 2023-07-24 11-45-24](https://github.com/reduxjs/redux-toolkit/assets/112059651/5029abd7-6768-43dd-8507-9dac6946867e)
![Screenshot from 2023-07-24 11-45-43](https://github.com/reduxjs/redux-toolkit/assets/112059651/b4bbce0f-891a-43e6-9963-120d9e9bf19d)
![Screenshot from 2023-07-24 11-45-52](https://github.com/reduxjs/redux-toolkit/assets/112059651/679f3d47-c9e6-4ed3-9c7d-dce0bf65240d)


-------------------------------------------------------------------------------------------------------------------------------------------------------

Also on endpoints:
based on the doc, here are the available methods :
![image](https://github.com/reduxjs/redux-toolkit/assets/112059651/1f733a58-d14f-4d5e-a17a-f1086e079729)
src=https://redux-toolkit.js.org/rtk-query/api/createApi#anatomy-of-an-endpoint
but here's what is suggested in vs code:
![image](https://github.com/reduxjs/redux-toolkit/assets/112059651/6462d0ae-def1-4e2d-afc8-dd346f46a5bd)

![image](https://github.com/reduxjs/redux-toolkit/assets/112059651/1f3460d4-20bc-41be-b1ad-ce01df38fa2e)

**Comment by phryneas** [comment]
For `fetchBaseQuery`, the docs write
> **It takes all standard options from fetch's [RequestInit](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch) interface**, as well as baseUrl, a prepareHeaders function, an optional fetch function, a paramsSerializer function, and a timeout.

That's exactly what you see there - the explicitly documented stuff plus everything `fetch` can take as an option.

With the mutation example, I'm not exactly sure what you are aiming for. `Types` is just a readonly property on `api.endpoint.myMutation.foo`, so that one should probably not appear there (but also probably doesn't hurt - if you focus it it tells you "All of these are undefined at runtime, purely to be used in TypeScript declarations!") - apart from that, what are you seeing that's not in the docs?

Usually, you can assume that your TypeScript types reflect the library code, so they are probably more up-to-date than the docs.

**Comment by vikyw89** [comment]
Alright, thank you for the time and clarification. :)
