### ISSUE TITLE
createSlice does not check reducers return type

### ISSUE THREAD

**Issue by zeuslocker** [reduxjs/redux-toolkit#365]
I have reducer:
```
import { currencyReducerState, Currency } from 'routes/OrderConfiguration/types'
import { createSlice, PayloadAction } from '@reduxjs/toolkit'

const initialState = {
  currency: Currency.UAH,
  rates: {
    EUR: 1,
    USD: 1
  },
  loading: false
}

export interface currencyReducerState {
  currency: Currency
  rates: Rates
  loading: boolean
}

const slice = createSlice({
  name: 'currency',
  initialState: initialState as currencyReducerState,
  reducers: {
    setCurrency: (state, action: PayloadAction<Currency>) =>
      ({ ...state, currency: action.payload, ExtraProp: 10 })
  }
})

export default slice
```
Why I don't receive an error about `ExtraProp` that does not exist in `currencyReducerState` ?

**Comment by phryneas** [comment]
Because additional return value properties are fair game in TypeScript if you validate something against a function type, which is the case here.
[See this playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgEoTMg3sgUMg5ABygHsjowBPAQQC5kBnMKUAc1wF9ddqLkAYiAAqVfgF5kACgCUycQD40GANw8EpEM2SRmDIaInIYAVxAIwwTTojNZ2PIWRQMJqCGz4nhEuUq0GACJdMECAGi9vYjIKKGoAISC4ABNkwMjkbk4gA)

If you don't want to be tripped by this, you might want to consider the "mutable assignment" approach that is possible because we internally use the `immer` library:

```ts
const slice = createSlice({
  name: 'currency',
  initialState: initialState as currencyReducerState,
  reducers: {
    setCurrency: (state, action: PayloadAction<Currency>) => {
      state.currency = action.payload;
      // this would be an error
      state.ExtraProp = 10;
    }
  }
})
```
