### ISSUE TITLE
🐣 Gradual adoption strategy to existing (traditional) reducer

### ISSUE THREAD

**Issue by dwiyatci** [reduxjs/redux-toolkit#375]
Hello! 🙂 

Recently I jumped into a React/Redux project where we have a super-big reducer for `data` slice with almost 1000 actions (okay, I might be exaggerating here 😄 ), and we would really love to bring this toolkit into the project. We want to "adopt it gradually", as in, we want to write new logic with the toolkit while maintaining the old good `switch` cases in the existing reducer (we're probably gonna rewrite it little-by-little). Do you have any suggestions on how to best approach this?

```javascript
/*
 * We want to add new logic cases in RTK's way, 
 * while maintaining (and possibly rewriting) the existing ones.
 */
function aHumongousSliceReducer(state = initialState, action) {
  switch (action.type) {
    case 'domain/action1': {
      // ...
    }
    case 'domain/action2': {
      // ...
    }
    ...
    case 'domain/action42': {
      // ...
    }
    default:
      return state;
  }
}

```

**Comment by markerikson** [comment]
The most immediate solution would probably be to just wrap this in Immer's `produce`, which we re-export from RTK as `createNextState`.  Then, rewrite each case one-by-one to start using "mutating" update logic.

From there, use `createReducer`, paste the action names in the cases into the `reducers` object, and paste the bodies of each case into separate functions passed to `createReducer`.

Finally, cut the `reducers` object out of `createReducer`, pass it as an argument to `createSlice`, export the now-generated action creators, and use those everywhere instead of the original hand-written ones.

Then, delete your now-unneeded hand-written action types and action creators, and celebrate! :)

**Comment by julioxavierr** [comment]
One "must" is having unit tests as well, to make sure you won't break anything along the way

**Comment by dwiyatci** [comment]
@markerikson All right, I guess they can kinda live side-by-side (https://codesandbox.io/s/react-redux-minimalist-dzuce?file=/src/slices.js). Thank you! :)
