### ISSUE TITLE
PayloadAction with meta does not work

### ISSUE THREAD

**Issue by karlmarxlopez** [reduxjs/redux-toolkit#376]
`v1.3.0-alpha.8`

Please check my example [here](https://stackoverflow.com/questions/60320668/how-to-properly-use-payloadaction-with-meta-type-in-redux-toolkit)

**Comment by phryneas** [comment]
The default behaviour of RTK is to create an action creator with only one argument and only a payload property. This behaviour cannot be modified by TS annotations, because TS annotations have no effect on runtime behaviour.

You can use [the `prepare` notation](https://redux-toolkit.js.org/api/createSlice#examples) to define a function that 
This function has the same signature & behaviour as the [`prepare` argument for createAction](https://redux-toolkit.js.org/api/createAction#using-prepare-callbacks-to-customize-action-contents), so you can find most of the relevant documentation there.

In your specific case, you'd want something along the lines of 
```ts
const cakeSlice = createSlice({
  name: 'cake',
  initialState,
  reducers: {
    fetchAll: {
      reducer(
        state,
        action: PayloadAction<Cake[], string, { currentPage: number }>
      ) {
        state.all = action.payload
        state.meta = action.meta
      },
      prepare(payload: Cake[], currentPage: number) {
        return { payload, meta: { currentPage } }
      }
    }
  }
})

```

PRs to make this more clear in the docs are always welcome!

**Comment by karlmarxlopez** [comment]
My tsconfig

```json
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "target": "esnext",
    "module": "commonjs",
    "lib": [
      "es6"
    ],
    "allowJs": true,
    "jsx": "react-native",
    "noEmit": true,
    "incremental": true,
    "isolatedModules": true,
    "strict": true,
    "moduleResolution": "node",
    "baseUrl": "./src",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true

  },
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js"
  ]
}
```

**Comment by karlmarxlopez** [comment]
My tsconfig

```json
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "target": "esnext",
    "module": "commonjs",
    "lib": [
      "es6"
    ],
    "allowJs": true,
    "jsx": "react-native",
    "noEmit": true,
    "incremental": true,
    "isolatedModules": true,
    "strict": true,
    "moduleResolution": "node",
    "baseUrl": "./src",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true

  },
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js"
  ]
}
```

**Comment by phryneas** [comment]
Unfortunately, there's nothing wrong with that as well. Could you try to reproduce the problem in a codesandbox? Without something we can both access, it's just guesswork :/

**Comment by karlmarxlopez** [comment]
@phryneas #350 fixed the problem. Thanks for your time!

**Comment by phryneas** [comment]
Please make sure to report accurate version information in the future. 
I could have told you that from the beginning, but #350 was already a part of `v1.3.0-alpha.8`...
