### ISSUE TITLE
dispatch inside createAsyncThunk calls causes rendering twice

### ISSUE THREAD

**Issue by Z-Hayk** [reduxjs/redux-toolkit#3783]
Hello everyone.

I found this problem in all my applications. I create an action and call this action inside createAsyncThunk and see twice rendering.

I have been using redux and had no such problems, but when I switched to Redux Toolkit, problems arose. I created this example for you, using only the redux toolkit, the initial application shell. A small application is not difficult to look at the code.

To view behavior [Video](https://drive.google.com/file/d/1Cu7wyz7ZQQHL5R0jkgLLvCXRIgJU5oh4/view?usp=sharingl)

[Code](https://github.com/Z-Hayk/redux-toolkit-twice-rerender)

Debugging [here](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/AppContainer.tsx#L9)
Changing this [reducer](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/features/user/slice.ts#L7)
Calling this [createAsyncThunk](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/features/user/actions.ts#L23)
Change the value [here](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/views/screens/HomeStack/HomeScreen/index.tsx#L15)

```
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@react-navigation/bottom-tabs": "^6.5.9",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.14",
    "@reduxjs/toolkit": "^1.9.7",
    "axios": "^1.5.1",
    "lodash": "^4.17.21",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-native-gesture-handler": "^2.13.1",
    "react-native-indicators": "^0.17.0",
    "react-native-reanimated": "^3.5.4",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-svg": "^13.14.0",
    "react-redux": "^8.1.3",
    "redux-persist": "^6.0.0"
```

It doesn't matter whether the persister is connected or not, the behavior is the same!

**Comment by markerikson** [comment]
My first observation is that both `addFavorite` and `deleteFavorite` appear to a misuse of `createAsyncThunk`.  Neither of them is doing any async work at all, and they're just dispatching more Redux actions.  `createAsyncThunk` is specifically intended for the use case of "make an async request, and dispatch actions before and after so we can keep track of the request status and results".

I'll also note that `addFavorite` is doing work to clone an existing user object and overwrite one field, then putting the entire new user object into the action.  That's an anti-pattern. Instead, we recommend doing that work in the reducer, which will significantly simplify the logic.

**Comment by Z-Hayk** [comment]
@markerikson Thanks for the answer.

This error twice rendering is even if there is an async request in the createAsyncThunk.
Please don't look at addFavorite, the problem here is twice rendering.

Sorry but to prove you wrong, I rewrote everything.

[Video](https://drive.google.com/file/d/1cGqJJ1VVAqTSf4_WBMB6Vm5yOi5z3xAw/view?usp=sharing)

**Comment by Z-Hayk** [comment]
@markerikson 
[Code](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/commit/b0252289fc3336465b7878d701205e6e80574004)

**Comment by phryneas** [comment]
You are still abusing `CAT`.

Fulwilling with success is completely useless, because the whole point of `cAT` is that it dispatches a "success" action in the end anyways.

You should not `dispatch(changeDriversInfo({ key: 'value', value: payload }));` here, you should just `return payload` from that thunk, which then results in the dispatch of a fulfilled action, and the reducer that is currently handling your `changeDriversInfo` should handle that fulfilled action instead.

**Comment by phryneas** [comment]
Apart from that, that double-render can at this point anything, but doesn't seem to be caused by that. Is your application maybe running in `StrictMode`?

**Comment by Z-Hayk** [comment]
Deleted StrictMode but the same behavior is visible.

**Comment by Z-Hayk** [comment]
I ask for your attention [here](https://stackoverflow.com/questions/68871562/dispatch-action-on-the-createasyncthunk)

**Comment by Z-Hayk** [comment]
@phryneas 

Your comments have been [corrected](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/commit/fe736f2f029d1ec749c5e635080e6631a6802706)

To view behavior [Video](https://drive.google.com/file/d/1cGqJJ1VVAqTSf4_WBMB6Vm5yOi5z3xAw/view?usp=sharing)

Unfortunately there are no changes. Twice rendering again. ))

**Comment by phryneas** [comment]
> I ask for your attention [here](https://stackoverflow.com/questions/68871562/dispatch-action-on-the-createasyncthunk)

Yes, you can dispatch another action. If that other action should happen at the same time as the "final" action, it's still useless.

Not everything that is technically possible is a good practice.

**Comment by phryneas** [comment]
Please read the Redux style guide, especially the parts about treating actions as events and avoiding to dispatch multiple actions in sequence.

https://redux.js.org/style-guide/#avoid-dispatching-many-actions-sequentially


Generally: there is no technical difference at all between dispatching in an asyncThunk or dispatching anywhere else in your application.

The difference is that an asyncThunk dispatches a pending and a fulfilled action automatically, so if you don't need those, you don't need an asyncThink, and if you need those, you should use those to handle most of your logic.

**Comment by Z-Hayk** [comment]
Thank you for your answer, I will definitely read the documentation that you sent.

But will think about this statement 'asyncThunk dispatches a pending and a fulfilled action automatically', ok then I will call my dispatch(action) at the end of the asynchronous action.

```
    try {
      await delay(2000);
      return fulfillWithValue(AsyncStatus.SUCCESS);
    } catch (e) {
      console.log(e);
    } finally {
      dispatch(changeDriversInfo({ key: 'value', value: payload }));
    }
```

https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/features/user/actions.ts#L22

It should be called once at the end, but it still renders twice.

**Comment by Z-Hayk** [comment]
I also noticed that this bug occurs only on React Native. React doesn't have this error. I really wanted to use the redux toolkit, but unfortunately this is a problem for me 'twice rendering'.

**Comment by markerikson** [comment]
@z-hayk: I think you're still kind of missing the point on the `createAsyncThunk` part.

I'm also not sure I understand what the actual _problem_ is to start with. React rendering is not a problem in and of itself - [rendering is how React does updates](https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#standard-render-behavior).  That's normal.  There are times you _may_ need to optimize the behavior, but "React renders twice" is not necessarily a "bug" to be fixed.  

Where and how are you seeing "rendering twice"?  Is there an actual _bug_ that is occurring in your app because of this?  Or are you just seeing a couple renders and _assuming_ that this is bad?

**Comment by Z-Hayk** [comment]
@markerikson Thanks for your reply.

I apologize, but I think yes, twice rendering, which essentially no one needs and should not be, this is a mistake.

Yes, I understand what you mean, but if the project only initially does double rendering, can you imagine what will happen to a large project?

In my opinion if you look at it in terms of React Native this is a big mistake and if know how react native works, how JavaScript and the native part are interconnected, then of course unnecessary rendering is a problem.

The developers wrote a new engine to increase the efficiency, and here the redux toolkit calls unnecessary renders.

https://reactnative.dev/docs/hermes

**Comment by markerikson** [comment]
@z-hayk: I'd agree that we want rendering to be predictable.  I _don't_ agree that this is a "mistake". There's a reason why each render happens.  

I'm honestly pretty busy right now and don't have time to investigate into your code further (especially since I'm not an RN user myself).  But A) I know how RTK and React-Redux work, and B) I know that they would only be triggering re-renders _if_ something has actually changed in your Redux store.  So, whatever's going on is going to be specific to _your_ app code (and not a bug in the libraries).  Your best bet is to look more closely at your own code and see what's being dispatched and what's updating in the state.  

I don't know if the React DevTools profiler works for React Native, but that would be a good tool to use here to see what's rendering and get an idea why.  You might also want to look at https://github.com/welldone-software/why-did-you-render .

I would also honestly suggest _not_ worrying about this until you see that there _are_ specific perf problems in the app. 1 extra render is not going to be a perf problem.  Dozens of extra renders, _maybe_ an issue.

**Comment by phryneas** [comment]
Just for giggles, you might want to remove `redux-persist` and see if that fixes it.

Generally, I'm gonna repeat my further statement: `dispatch` in `cAT` calls `store.dispatch`. It's not technically any different from calling `dispatch` anywhere else, so this is 100% not a `createAsyncThunk` problem. You might have all other kinds of problems in there, like another library modifying your state multiple times, or a rerender because of your `SafeAreaProvider`, or *anything* else.

It could even be dispatching your async thunk twice, but it is 100% definitely not a problem of `createAsyncThunk`.

**Comment by Z-Hayk** [comment]
I deleted all unnecessary providers and disabled everything, but unfortunately the same behavior.

You can see my commit [here](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/commit/a517919ede6a9475595379f5ee0479d89dd7a5ee)

To view behavior https://drive.google.com/file/d/16AnswHork28aXj-8Fj0btdUYwRmS6c2c/view?usp=sharing

**Comment by Z-Hayk** [comment]
@markerikson @phryneas Thank you very much.
Sorry for wasting your time. If you have time in the future, please look at my code and you will see what I mean. I'm sure the problem is redux toolkit. I do the same thing through redux / redux-thunk and I don't see any problems.

I wrote everything according to the redux toolkit documents.

I always follow the updates of what you do and thank you for such a package that you wrote, I appreciate your work.

**Comment by markerikson** [comment]
@z-hayk: I can _assure_ you that there is _no_ difference between writing a couple dispatches with Redux, and writing a couple dispatches with Redux Toolkit, that would cause a difference in re-rendering behavior.

React-Redux re-renders when it sees the selected state change. That is true whether you wrote the dispatching logic and the reducers with original vanilla Redux, or Redux Toolkit.

So, either the code you wrote with RTK is doing _more_ dispatches than the original Redux code, or there is something _else_ going on that is not specific to RTK.

**Comment by Z-Hayk** [comment]
@markerikson @phryneas  Sorry, but to prove you wrong, I rewrote everything into redux / redux-thunk. You just need to watch the video and two files to understand that I'm right. Sorry but this is really worth your attention.

https://drive.google.com/file/d/1Xqs1w2A1dspRjM1q4ndl9IYMLwrGMVyh/view

Essentially the same actions. [redux-thunk action](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/store/user/actions.ts) - [reduxjs-toolkit createAsyncThunk](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/features/user/actions.ts#L13)

And essentially the same reducers. [redux reducer](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/store/user/reducer.ts#L11) - [reduxjs-toolkit createSlice](https://github.com/Z-Hayk/redux-toolkit-twice-rerender/blob/main/app/features/user/slice.ts#L13C31-L13C47)

But the difference is clearly visible in the video, twice rendering, the reduxjs-toolkit reducer changes the value twice

**Comment by markerikson** [comment]
I'm sorry, but looking at that video, I don't know what specific thing you're trying to show me as an indicator that "this is rendering twice".

I will also point out that your use of `createAsyncThunk` still seems very confusing:

```ts
export const deleteFavorite = createAsyncThunk(
  'user/DELETE_FAVORITE',
  async (payload: string, { dispatch, fulfillWithValue }) => {
    try {
      await delay(2000);
      return fulfillWithValue(AsyncStatus.SUCCESS);
    } catch (e) {
      // eslint-disable-next-line no-console
      console.log(e);
    } finally {
      dispatch(changeDriversInfo({ key: 'value', value: payload }));
    }
  },
  {
    condition: (_, { getState }) => {
      const user = (getState() as RootState).user;
      if (user.deleteFavoriteRequestStatus === AsyncStatus.LOADING) {
        return false;
      }
    },
  },
);
```

I would _not_ expect to see this using `fulfillWithValue` at all, and I would not expect it to be returning a "success status" value.  Instead, I _would_ expect to have it simply returning whatever the desired result payload is.  (For that matter, the handwritten thunk also seems to be dispatching a "success" value with no real _data_, and then dispatching a follow-up `changeDriversInfo` action.  This also seems like a wrong approach to writing a thunk as well.)

Honestly, looking at the code you've got in that project, there's some very odd patterns in there (like exporting `dispatch` and `getState` separately from the store file, etc).

I don't have a specific answer to what you think you're seeing. But I can _guarantee_ you that, _when used the right way_, there is no actual difference with Redux Toolkit that would randomly cause extra renders. Period. (And _especially_ not in a way that would only manifest in React Native.)

I appreciate the time you've put into trying to report this, but you've got _both_ primary Redux maintainers telling you that whatever you think you're seeing is not actually a real problem in the Redux Toolkit library, that whatever _might_ be happening is almost definitely something about the way you've written your app code, and that this much time spent focusing on a single _possible_ extra render is not worth the worry at this point.  I'm not trying to yell at you or make you go away, but could you please consider that we do probably know what we're talking about here? :)

**Comment by Z-Hayk** [comment]
I'm trying to understand why double rendering is happening and I think it will have a bad effect on my project.
I want to understand what's wrong. I wrote everything according to the redux toolkit documentation.

I understand that you say that it’s normal that 1 additional render does not change anything, but now 1 additional render in large projects becomes, for example, 20 - 30 or more additional renders, in my opinion this is not acceptable.

I'm sorry, if I wrote it wrong then how can I call another action inside createAsyncThunk?
So that everything works correctly according to you.

Corrected your comments https://github.com/Z-Hayk/redux-toolkit-twice-rerender/commit/9e962c62c587ad026bf8188985fc7888c51b0d54

**Comment by Z-Hayk** [comment]
> @Z-Hayk: I can _assure_ you that there is _no_ difference between writing a couple dispatches with Redux, and writing a couple dispatches with Redux Toolkit, that would cause a difference in re-rendering behavior.
> 
> React-Redux re-renders when it sees the selected state change. That is true whether you wrote the dispatching logic and the reducers with original vanilla Redux, or Redux Toolkit.
> 
> So, either the code you wrote with RTK is doing _more_ dispatches than the original Redux code, or there is something _else_ going on that is not specific to RTK.

After you said `no difference between writing a couple dispatches with Redux, and writing a couple dispatches with Redux Toolkit` I made a video to show you, sorry you are wrong there is a difference.

reduxjs-toolkit reducer changes the value twice.

**Comment by phryneas** [comment]
I could reproduce the issue, but I still don't agree that this has anything to do with `createAsyncThunk`.

![image](https://github.com/reduxjs/redux-toolkit/assets/4282439/0dfbbb1d-a878-4ce9-9533-73b637645fff)

As you can see, the second rerender occurs after the `fulfilled` action, which should never be the case. But that said: `cAT` doesn't contain any code that can even cause a rerender, so it has to be something else.

This seems to generally be caused by the specific order and timing of actions flying here. To me this looks like a bug either in `react-redux`, or in `react` itself, more specifically the `useSyncExternalStore` implementation used by React Native.

I'll see if I can spend some more time with this these days.

**Comment by awreese** [comment]
@Z-Hayk I'm not going to dig through your entire repo.... but.... are you using some event listeners/handlers by any chance, adding them and not clearing up previous handlers?

**Comment by Z-Hayk** [comment]
@awreese No, everything is disabled.

**Comment by Z-Hayk** [comment]
@phryneas Hello.
Have you looked at this issue?

**Comment by Z-Hayk** [comment]
@markerikson @phryneas
