### ISSUE TITLE
Argument of type 'unknown' is not assignable to parameter of type 'Action<string>'.

### ISSUE THREAD

**Issue by andreisocaciu** [reduxjs/redux-toolkit#3895]
When trying to match an action in a middleware, I get this Typescript error: `Argument of type 'unknown' is not assignable to parameter of type 'Action<string>'. typescript(2345)`

Version: `@redux/toolkit@2.0.0-rc.0`

Codesandbox link: https://codesandbox.io/p/sandbox/kind-fog-7nxp6k?file=%2Fshared%2Fcounter.middleware.ts%3A5%2C31-5%2C37

**Comment by EskiMojo14** [comment]
yep - you need to check it's an action first. Redux now exports an `isAction` type predicate that can do this for you:
```ts
import { isAction, Middleware } from "@reduxjs/toolkit";
import { incrementByAmount } from "./counter.slice";

export const counterMiddleware: Middleware = (store) => (next) => (action) => {
  if (isAction(action) && incrementByAmount.match(action)) {
    console.log("action dispatched", action);
  }
  return next(action);
};
```

**Comment by EskiMojo14** [comment]
fyi we're now planning to move the `isAction` call inside .match so you won't have to do this yourself (https://github.com/reduxjs/redux-toolkit/pull/3897) - we're also gonna move `isAction` to the core package and re-export it from RTK, since it's likely useful for people using handwritten redux patterns too
