### ISSUE TITLE
`onCacheEntryAdded` not called after invalidating query

### ISSUE THREAD

**Issue by sem4phor** [reduxjs/redux-toolkit#3912]
Hello,

I am handeling a websocket connection in a quer's onCacheEntryAdded function. To benefit from a fresh auth token I want to invalidate the query when the token expires to regain a valid auth token for the websocket.

Unfortunately the only method to re-enter the onCacheEntryAdded method is to `resetApiState` from what I see.
I tried `update/upsertQueryData`, `endpoints.myQuery.instantiate('arg', { forceRefetch:true })`, `utils.invalidateTags(['myQueryTag'])` all of those invalidate the query but do not re enter the onCacheEntryAdded function which I find strange as from my understanding the cache entries get purged at least b the invalidateTags function right?

**Comment by rjgotten** [comment]
> `onCacheEntryAdded` only runs when there _isn't_ a cache entry for a key, and a new one gets added.

But then; how would you reset e.g. a web socket stream, following the example for streaming updates as given in the manual?
`onCacheEntryAdded` has seemingly _no way_ in its API to be notified of a refetch and do the reset manually.

It makes sense that when you force a refetch and the fetch is finished it expunges the existing cache entry and recreates it. It can keep the stale cache while the request is running, but from the perspective of a sound mental model it should imho evict the entry and replace it wholesale as soon as the request finishes.

A colleague of mine actually came across this very same issue a few hours ago, and we had to move off of `onCacheEntryAdded` and started using `onQueryStarted`. As that also has an `updateCachedData`, we were able to make our particular use case work, mainly because ours is not reliant on e.g. a web sockset stream that keeps receiving updates indefinitely, but is just a scenario of executing multiple end points and combining (partial) results in a non-blocking manner.

For the indefinitely running case, you really _do_ need to know when the lifetime subscription ends, which is what the `cacheEntryRemoved` promise does for `onCacheEntryAdded` and which `onQueryStarted` _doesn't have_.

**Comment by markerikson** [comment]
> It makes sense that when you force a refetch and the fetch is finished it expunges the existing cache entry and recreates it

As far as I know, that's not how RTKQ works internally. I don't have all the code paths locked in my head, but I'm pretty sure it tracks both the loading status and the existing data at the same time, _without_ removing the actual cache entry object for that key.

**Comment by rjgotten** [comment]
If upon a refetch, when the fetching actually finishes, a new cache entry would be created to supplant the old one; why would that not work? The `cacheEntryRemoved` could complete on the old entry; `onCacheEntryAdded` could be executed on the new one; and then the new one could be registered as the current cache object and all subscribed queries should update to it.

Why wouldn't that work? Swapping the cache entry _should_ be fully transparant to outside observers.
If not, you've written some very gnarly (and subjectively speaking: very _wrong_ ) code.

Note that I'm not talking about deleting the cache entry while the refetch query is still in-flight.
I'm talking about swapping the cache entry out in an observably atomic way once the refetch's underlying query fullfills.

**Comment by sem4phor** [comment]
Thank you for your input! That kind of forces us to also move away from the websocket handling via `onCacheEntryAdded` Very unfortunate I liked the approach very much. I might be able to work around it via a listenerMiddleware (if i am able to listen for rtk actions & cache invalidations  👀 ).

**Comment by rjgotten** [comment]
> @markerikson  
> That is the definition of the intended logic.

I would argue that as `refetch` is meant to _invalidate_ a cache entry, it means that the entry corresponding to that key should actually be disposed of and recreated. Which means there would, in fact, be a new cache entry created.

I would also posit that if you're going to look at this from the limited and exclusive perspective of 'zero-or-any subscriber(s)', you still have a feature gap in the API. Because `onCacheEntryAdded` has no way to know when the cache entry was invalidated and no way to respond to that.

So either way; something's going to have to give, no?
Either the callback re-runs or there's some kind of evented listener thing that needs happening. I would personally go for the callback re-run, since it fits the actual mental model of an invalidated cache entry being removed and re-created. And also because adding a listener into what is essentially a start-to-end running asynchronous callback with an await on `cacheRemoved` separating the setup from the teardown, is just going to lead to terrible; terrible spaghet.

**Comment by phryneas** [comment]
I believe you really just look at the wrong lifecycle api.

`onCacheEntryAdded` is for the moment when something that wasn't in cache before is added to the cache. That's obviously not the thing you want, since **we hold things in cache from the first time it entered the cache until nobody uses it any more + some extra time**.

I believe you are just looking for `onQueryStarted`.

**Comment by nevnein** [comment]
Some middle ground between `onQueryStarted` (I know the query has started but I still have no data to work with) and `transformResponse` (Now I have the fresh data but I am limited in what I can do) could be useful anyway.

**Comment by markerikson** [comment]
Could folks leave some suggestions (preferably with notional pseudo-code-y usage examples) over in the "RTK Query API Pain Points" thread?  https://github.com/reduxjs/redux-toolkit/issues/3692

That would help collect some of these suggestions in one place.

**Comment by phryneas** [comment]
> Could folks leave some suggestions (preferably with notional pseudo-code-y usage examples, and use case descriptions) over in the "RTK Query API Pain Points" thread.

They could also just read the docs instead of arguing here. Honestly, at this point I'm seriously getting frustrated.

> Some middle ground between onQueryStarted (I know the query has started but I still have no data to work with) and transformResponse (Now I have the fresh data but I am limited in what I can do) could be useful anyway.

[`onQueryStarted`](https://redux-toolkit.js.org/rtk-query/api/createApi#onquerystarted) covers both of those cases, with exactly the same mental model as `onCacheEntryAdded`. 

`onQueryStarted -> await queryFulfilled`
`onCacheEntryAdded -> await cacheDataLoaded`

**Comment by sem4phor** [comment]
I will close this issue in the sense of what @phryneas said

**Comment by qd-corp-sonu** [comment]
use onQueryStarted like this to get some of the functionality  of onCacheEntryAdded 
      async onQueryStarted(
        _,
        {
          dispatch,
          queryFulfilled,
        }
      ){
        const res=await queryFulfilled
        dispatch(updateSchooldetail(res.data.data))
      }

    }),
