### ISSUE TITLE
Update Redux templates

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-toolkit#3940]
- [x] Update the Redux templates
- [x] Update Next's `with-redux` example to match the new Next usage guide

**Comment by aryaemami59** [comment]
I'll start working on the `with-redux` example. Do you think the examples I have for #3984 and #3985 are good candidates (or at least somewhat on the right track) for updated redux templates?

**Comment by markerikson** [comment]
The issue is that Next's setup is much more complicated.

Go through the new "Setup with Next" page, and try to convert the guidance there into code :)

**Comment by aryaemami59** [comment]
@markerikson oh I meant I'm going to work on the `with-redux` example app, as in I'm going to make something somewhat similar to what Jack Harrington initally provided and make sure we create a unique store instance per request etc. But I was thinking about creating a more updated redux template for React Native and Expo and maybe a plain react app with vite with some of the new API (`createSlice.selectors`, `create.asyncThunk`, etc) included in order to get people up to speed with RTK 2.0 and encourage them to try out all the new goodies you guys worked so hard to create. Do you think this would be something worth looking into?

**Comment by markerikson** [comment]
Yeah, definitely worth having actual RN templates too

**Comment by aryaemami59** [comment]
Wonderful! It would be good to finally have official templates for RN and Expo :)

**Comment by EskiMojo14** [comment]
for with-redux: https://github.com/vercel/next.js/pull/59864

**Comment by aryaemami59** [comment]
I believe this one can be closed now that [`with-redux`](https://github.com/vercel/next.js/pull/59864) has been merged.

**Comment by markerikson** [comment]
Yep!
