### ISSUE TITLE
updating redux-thunk from 3.0.1 to 3.1.0 causing errors ...is not assignable to parameter of type 'UnknownAction'.

### ISSUE THREAD

**Issue by JustFly1984** [reduxjs/redux-toolkit#3976]
I have a hundred thunks dispatch erroring out "is not assignable to parameter of type 'UnknownAction'."

dispatch(thunk)

redux-thunk/extend-redux import is not available.

It is requires a ton of work to refactor 100% working code to @redux/toolkit style of thunks. Please bring back dispatching old style thunks `(args) => ({ dispatch, getState }) => void`

reverting back to redux-thunk@3.0.1 solves an issue

**Comment by phryneas** [comment]
This is not about switching between old-style thunks and `createAsyncThunk`, it's that you are using the global `Dispatch` type instead of a `Dispatch` type that doesn't contain information about the middleware you are actually using.

Take a look at the TypeScript quickstart, especially the [defining typed hooks](https://redux-toolkit.js.org/tutorials/typescript#define-typed-hooks) section.

We don't do the global enhancement anymore because it causes a lot of confusion in bigger projects and monorepos. If you insist on using it, you can still copy-paste over the old type augmentation from `redux-thunk/extend-redux` into your code base, but replacing the type-indifferent `useDispatch` hook with a `useAppDispatch` hook containing the right information for your project would be preferrable - and it's only one search & replace away.

**Comment by markerikson** [comment]
Yep, the best answer here is to follow the guidelines for correctly inferring an `AppDispatch` type from your store type, which will have the knowledge of the thunk middleware baked in. Then, use that across the app:

- https://redux-toolkit.js.org/tutorials/typescript#define-root-state-and-dispatch-types

**Comment by JustFly1984** [comment]
Thank you, It did help to setup useAppDispatch and useAppSelector. It was a lot of work to refactor an app anyway, unexpected work, counting that release is minor.
