### ISSUE TITLE
The inferred type of [...] cannot be named without a reference to [...] buildHooks.js

### ISSUE THREAD

**Issue by thovden** [reduxjs/redux-toolkit#3983]
Porting from RTK Toolkit 1.9.7 to 2.0.1 I get the following problem for my RTK Query endpoints when exporting the generated hooks. 

E.g., 
```
The inferred type of 'useLazyGetNlpQuery' cannot be named without a reference to '../../../../node_modules/@reduxjs/toolkit/dist/query/react/buildHooks.js'. This is likely not portable. A type annotation is necessary.ts(2742)
```

This error occurs on all endpoints, not just this one. I do not import or use buildHooks anywhere in my code.

**Comment by shermify** [comment]
I have this same problem after updating to reduxjs/toolkit 2.0. The problem here seems to happen if you're creating a library that emits TS definitions. Typescript is looking for types that are not actually exported directly from redux-toolkit at all. I am only able to solve it by adding `export * from './buildHooks` to `reduxjs/toolkit/query/react/index.d.ts`. Obviously just for testing purposes.

Not sure if this is purely a typescript problem (very possible), a problem with the redux/toolkit library, or maybe a sprinkling of both. Either way, I'm currently unable to update my project to 2.0.

<img width="797" alt="Screenshot 2024-01-11 at 2 17 38 PM" src="https://github.com/reduxjs/redux-toolkit/assets/12567037/17a45b3b-cd0d-4094-bcf7-81f5ba9d9a31">

**Comment by shermify** [comment]
Here is an extremely simple reproduction of the issue

https://github.com/shermify/redux-toolkit-ts-repro

**Comment by thovden** [comment]
I refactored my code today and got around this problem. The two things I did was: 

1. Don't export the RTKQuery generated hooks, export the API instead and use e.g., `nlpApi.useLazyGetNlpQuery` 
2. I had some exports where I spread a slices onto another object - e.g., ` const features = { ...slice, ...}`. This caused "cannot be named" issues. 

I'm going to close this issue now. Keep up the good work!

**Comment by shermify** [comment]
This is still valid ECMAScript, so there is a typescript problem here. I'm not sure exactly where the responsibility falls but I've opened an issue here with more detail and it's in the bugfix queue. https://github.com/reduxjs/redux-toolkit/issues/4066

**Comment by Romanmed2000** [comment]
i have same problem/ i use official example by redux https://github.com/reduxjs/redux-templates/blob/master/packages/vite-template-redux/src/features/quotes/quotesApiSlice.ts and have error 
The inferred type of useGetQuotesQuery cannot be named without a reference to
../../../../node_modules/@reduxjs/toolkit/dist/query/react/buildHooks
. This is likely not portable. A type annotation is necessary.
after 6 mons fix not apply? need correct example?

**Comment by EskiMojo14** [comment]
@Romanmed2000 if you install the build from [here](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/4467/builds/522566), does that fix the issue?

> after 6 mons fix not apply? 

We have a PR #4467 open from @aryaemami59 aiming to fix it, but as the size of the PR may tell you, it's not an easy fix. It's taken him months of work so far.

**Comment by markerikson** [comment]
Fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.7 !
