### ISSUE TITLE
Question About RTK Query Usage

### ISSUE THREAD

**Issue by emreakdas** [reduxjs/redux-toolkit#4165]
When using RTK Query, I capture the successful request returned from the API in my slice file with matchFulfilled and write this information to my slice file, but is this the correct use? Should I select and use it with select to use this value in sub-components?

**Comment by markerikson** [comment]
You shouldn't need to use `matchFulfilled` or a separate slice at all. RTK Query already has its own caching slice reducer that does all the default caching work for you.

You _can_ listen to those actions via `matchFulfilled` and write the data to a separate slice reducer _if you want to_, and that's something we intentionally made possible... but you should not _need_ to do this.  It's only for very rare use cases.

Normally, you just add the API slice caching reducer to the store and it does all the actual caching work for you automatically, and you use the query hooks in components to trigger the requests and read the data:

- https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics

Is there some specific problem you're trying to solve here?

**Comment by emreakdas** [comment]
@markerikson thanks for your comment. Should I get the return value of the query I triggered from the parent component using select() and selector or should I call the related query again?

Is there a difference between these two usages (selection with select or running the query again, which will eventually bring the cache)? and why do they do isLoading check etc. when selecting with select(), isn't the data already in the cache in the example?

**Comment by markerikson** [comment]
@emreakdas : the `useSomeQuery()` hook _already_ does the selection for you - it subscribes to the Redux store with `useSelector`, and will re-render when the data is updated.  So you don't need to do that yourself.

You _can_ use the same query hook with the same arguments in multiple components, or you can read the data in a parent component and pass it down. That's up to you.

**Comment by emreakdas** [comment]
@markerikson As my last question, do I need to check isLoading and isError again when using the query that I use in the upper component and check isLoading and isError in the lower component? The data will already come if there is no error at that stage.

**Comment by markerikson** [comment]
@emreakdas first thing to note is that `isLoading` is only true the _first_ time _any_ data gets fetched for that query argument. Most of the time you probably want to check `isFetching` instead.

Where you check the loading booleans is up to you - it's about where you need to use the data in the app.  That said, if you're using TS, you may also want to check them because something like `if (isSuccess)` will tell TS that `data` must be a real value at the types level.

**Comment by emreakdas** [comment]
@markerikson I understand that when I call the same query again with the same parameters, I will not need to check isFetcing because it already comes as "fulfilled". am I right?

**Comment by markerikson** [comment]
All depends on the timing.

If your parent component _immediately_ renders the child, then the child will also render before the response has come back.  If the parent waits until has the actual data and _then_ renders the child, then sure, you've already made that check.

**Comment by emreakdas** [comment]
@markerikson evet veri geldikten sonra yani isLoading false ve isError false ise child component'i oluşturuyorum o zaman her şey doğru görünüyor teşekkürler yorumlarınız için 😊

**Comment by thoughtworks-tcaceres** [comment]
> You shouldn't need to use `matchFulfilled` or a separate slice at all. RTK Query already has its own caching slice reducer that does all the default caching work for you.
> 
> You _can_ listen to those actions via `matchFulfilled` and write the data to a separate slice reducer _if you want to_, and that's something we intentionally made possible... but you should not _need_ to do this. It's only for very rare use cases.
> 
> Normally, you just add the API slice caching reducer to the store and it does all the actual caching work for you automatically, and you use the query hooks in components to trigger the requests and read the data:
> 
> * https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics
> 
> Is there some specific problem you're trying to solve here?

Old question - sorry for bringing this back up and not sure if this is the right place.
But is there a way to listen to matchFulfilled when it only accesses the cached data?
In my case I have a user that can toggle an option that would perform a useQuery hook. Click "1" --> get data for "1". Click "2" --> get data for "2". Click "1" again use the cached data. On the second click of "1" I wouldn't be able to use the matchFulfilled and not able to perform some side effect, and since it doesn't look like there's an action dispatched at all, I don't think I could also do this via middleware?
Similar point as to this post: https://stackoverflow.com/questions/74720674/rtk-query-get-cached-data-in-extrareducers

**Comment by markerikson** [comment]
@thoughtworks-tcaceres : no, there's not, because no action was dispatched and no request was made. It's just a straight selection from the store.
