### ISSUE TITLE
Unexpected behaviour of isSuccess on second refetch

### ISSUE THREAD

**Issue by rusnick31** [reduxjs/redux-toolkit#4240]
I have a simple endpoint `getData`
https://stackblitz.com/edit/react-ts-7vwdac?file=App.tsx

```ts
const delay = () => {
  return new Promise((resolve) => {
    setTimeout(resolve, 500);
  });
};

let count = 0;

const api = createApi({
  reducerPath: 'api',
  endpoints: (builder) => ({
    getData: builder.query<number, void>({
      queryFn: async () => {
        count += 1;

        await delay();

        if (count > 1) {
          return { error: true };
        }

        return { data: 123 };
      },
    }),
  }),
  baseQuery: fakeBaseQuery(),
});

const { useGetDataQuery } = api;
```

which is used like that

```tsx
function Component() {
  const { refetch, data, isError, isSuccess } = useGetDataQuery();

  console.log({ isError, isSuccess });

  return (
    <div>
      <button onClick={refetch}>refetch</button>
      <span>{data}</span>
    </div>
  );
}

export default function App() {
  return (
    <Provider store={store}>
      <Component />
    </Provider>
  );
}
```

output on mount is:
```ts
{ isError: false, isSuccess: false }
{ isError: false, isSuccess: false }
{ isError: false, isSuccess: true }
```

after calling `refetch` for the first time:
```ts
{ isError: false, isSuccess: true }
{ isError: true, isSuccess: false }
```

but if I call `refetch` one more time, I'll get
```ts
{ isError: false, isSuccess: true }
{ isError: true, isSuccess: false }
```

RTK switches `isSuccess` back to true for some reason while the request is loading

Is it the correct behaviour? Shouldn't `isSuccess` stay false?

**Comment by EskiMojo14** [comment]
This appears to be intentional behaviour - `useQuery` holds onto the last successful request's `data`, and `isSuccess` is true if it has data and is currently fetching.

I don't fully understand the motivation behind this, though - hopefully somebody else can explain.

https://github.com/reduxjs/redux-toolkit/blob/ed9fc19027a31afee2234dea54fb36c8beef46ad/packages/toolkit/src/query/react/buildHooks.ts#L684-L695

**Comment by markerikson** [comment]
Until the in-flight request returns, we _do_ have valid data from the _last completed_ request, so the _current_ status is still "successful".

**Comment by markerikson** [comment]
Storing the value in a Redux slice is the right approach. Tracking it at the component level won't give you a correct or consistent number of all possible errors that occurred.

**Comment by markerikson** [comment]
At a minimum, you could genericize the matcher logic:

```ts
const isMyApiError = (action) => {
  return action.type.startsWith("myapi/") && isRejected(action);
}
```

**Comment by phryneas** [comment]
> This appears to be intentional behaviour - useQuery holds onto the last successful request's data, and isSuccess is true if it has data and is currently fetching.
> 
> I don't fully understand the motivation behind this, though - hopefully somebody else can explain.

The data that's currently available in `data` is the data returned from a successful fetch. You probably don't want that to flicker away just because a new fetch starts.  
At the same time, another fetch is going on -> both of these states are hit at the same time.

It's an attempt at simulating "suspense-like" behaviour, where you'd have the component in the last successfully rendered state, but at the same time had something like `pending` available to gray parts of the UI out or show a spinner.

**Comment by markerikson** [comment]
@rusnick31 not immediately likely. This is the first time anyone's ever asked for something like an error count that I know of.  Individual feature requests are always a possibility, but we generally try to avoid adding things unless it feels like there's enough usefulness _and_ a wide enough audience to justify adding something.  (After all, any feature we ship adds bytes to bundle size for everyone.)

In the React-Query case, it looks like that error count was something they were already tracking internally for some reason and exposed it publicly.  We don't keep track of error counts ourselves that I know of.

So, I'm not saying "no" permanently, but given that this seems doable in userland and this is the first time the question of "counting errors" has ever come up, I don't see an immediate reason to add this.

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.4.0 !
