### ISSUE TITLE
Error when using rollup: can't find variable: process 

### ISSUE THREAD

**Issue by svdo** [reduxjs/redux-toolkit#425]
I think I may be experiencing the same problem as #124. I have setup this repo to reproduce it: https://github.com/svdo/redux-toolkit-with-rollup-issue. Basically, it contains a lib and an app. The lib has redux-toolkit as a dependency, the app uses it. Both are built using rollup. After setting things up and opening the test page in the browser, I get this error:

> ReferenceError: can't find variable: process

I may be doing something wrong myself, not sure; any help is much appreciated!

**Comment by phryneas** [comment]
Hmm... 
It's using the ESM build and has no `process` variable set. We remove that from the CommonJS and UMD build, because for those we provide each a production as well as a development build.
The ESM build contains both, so the bundler has to provide the value using `rollup-plugin-replace` or similar.

This should also be happening with react builds (which also check for `process.env.NODE_ENV`), and a solution is described here:
https://github.com/rollup/rollup/issues/487#issuecomment-177596512

We *could* add a check for `typeof process !== "undefined"` to our ESM build, but then you'd always get a production build - so I believe the current behaviour should work out better in the end

**Comment by svdo** [comment]
I see. So indeed after adding this to `app/rollup.config.js`, the error is gone:

```js
  plugins: [
    ...,
    replace({
      'process.env.NODE_ENV': JSON.stringify( 'production' )
    })
  ]
```
