### ISSUE TITLE
Query entries aren't removed from state if arg changes while query is pending

### ISSUE THREAD

**Issue by bromanazzi** [reduxjs/redux-toolkit#4267]
Hey, I'm encountering a problem where queries never unsubscribe if arg changes while its pending. Here's a codesandbox to reproduce:

[https://codesandbox.io/p/sandbox/distracted-easley-6vnn6x](https://codesandbox.io/p/sandbox/distracted-easley-6vnn6x)

- The test query does nothing but resolve after 3 seconds. `keepUnusedDataFor` is set at zero (i also tested 1 with same results)

- The two buttons fast and slow change the speed at which the arg changes; 1 and 5 seconds respectively

Looking at the redux devtools: 

While the arg changes slowly everything works as intended: the last cached query is removed from state, keeping only one entry active.

However once the query starts changing args faster than its resolve period, a memory leak seems to appear where entries get added indefinietly and never get removed.

As a consequence, it's messing a bit with `onCacheEntryAdded`, since `cacheEntryRemoved` never resolves.

**Comment by phryneas** [comment]
This seems to be related to #3709.

We remove the subscription here:
https://github.com/riqts/redux-toolkit/blob/9b2990a1115ced9fb11cd9d95418610b171fb3fb/packages/toolkit/src/query/core/buildMiddleware/batchActions.ts#L58-L66

But the problem is that for a subscription removal triggred through `fulfilled` or `rejected`, we don't start the timer in 
https://github.com/riqts/redux-toolkit/blob/9b2990a1115ced9fb11cd9d95418610b171fb3fb/packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts#L69-L79

**Comment by phryneas** [comment]
That said, I had a bit of time to analyze this and (probably?) find the root cause, but I don't really have the time to put up a fixing PR right now - a PR would be very welcome :)

**Comment by riqts** [comment]
I'll try do a PR for this now seeing as @phryneas has already done all the thinking work for me by the looks of it.

**Comment by bromanazzi** [comment]
thank you so much @phryneas and @riqts for the quick fix!
