### ISSUE TITLE
Add SWR comparison

### ISSUE THREAD

**Issue by charlieforward9** [reduxjs/redux-toolkit#4341]
I am learning about best-practice for data fetching to decide which direction to take our applications data processes. It would be helpful to see how SWR compares to the rest of these fetchers [here](https://github.com/reduxjs/redux-toolkit/blob/master/docs/rtk-query/comparison.md).

**Comment by phryneas** [comment]
Honestly, we should probably take that comparison down since it's extremely outdated - we haven't even updated it with our own features that we added in the last few years.

As for your request:
At this point, I have no idea what SWR can actually do or not, so I don't have the knowledge to add that to the comparison. Afaik it has been abandoned for a few years and recently development has been taken up again, but I have no idea where they stand.

**Comment by charlieforward9** [comment]
@phryneas makes sense. These projects update so frequently that maintaining a comparison is a project in itself.

This one is pretty good: https://tanstack.com/query/latest/docs/framework/react/comparison

If its inaccurate, it would be helpful to point it out!

Thank you for your OS contributions.
