### ISSUE TITLE
Some Types Not Exported(RetryOptions and RetryConditionFunction)

### ISSUE THREAD

**Issue by thoughtworks-tcaceres** [reduxjs/redux-toolkit#4384]
This is most likely a silly question.
But I was wondering why some types are not exported from the @reduxjs/toolkit package such as "RetryOptions" and "RetryConditionFunction", etc.

**Comment by EskiMojo14** [comment]
We don't export everything, just the ones we think would be useful for users. Exporting more things makes it harder to make changes, because it's more likely to be breaking for users. When things remain implementation details, we have the freedom to change them more easily.

Is there any particular reason you'd want those specific types exported?

**Comment by thoughtworks-tcaceres** [comment]
In my case, Just trying to create separate functions for retryCondition and prepareHeaders.
