### ISSUE TITLE
Any way to remove middleware after it's added then use createDynamicMiddleware? 

### ISSUE THREAD

**Issue by smff** [reduxjs/redux-toolkit#4385]
I need to load and unload some middleware dynamically.

const dynamicMiddleware = createDynamicMiddleware();

dynamicMiddleware.add(someMiddleware)

So, any way to remove someMiddleware now?

**Comment by EskiMojo14** [comment]
no, there's no way to remove middleware once added.

as a reminder though, middleware can always choose not to run:
```ts
const myDisableableMiddleware = (api) => {
  let enabled = true
  return (next) => (action) => {
    if (enableMiddleware.match(action)) {
      enabled = true
    } else if (disableMiddleware.match(action)) {
      enabled = false
    }
    if (!enabled) return next(action)
    // middleware logic here
  }
}
```

**Comment by smff** [comment]
@EskiMojo14 Are there any plans for building delete function into createDynamicMiddleware?

**Comment by EskiMojo14** [comment]
no, it's an intentional design decision - the main reason we think you'd want to add a middleware after store setup is for bundle size/lazy loading reasons, and in that case there's no size benefit to unloading the middleware.

it also makes the types for dispatch inaccurate, as there would be no way of knowing that the overloads you've added are still there.
