### ISSUE TITLE
[createEntityAdapter] React doesn't re-render when removeOne is called

### ISSUE THREAD

**Issue by tranceyos2419** [reduxjs/redux-toolkit#450]
Hi, I'm new to redux and redux-tool kit and facing a problem which is related to createEntityAdapter.

The problem is that when I trigger the removeOne function, React doesn't re-render the component which I've defined .selectAll(store.getState()) inside even though the state in the redux store has been changed. 

Here is my code

Books.tsx
```typescript
const Books = (props: Props) => {
  const [count, setCount] = useState(0);
  const allBooks = booksSelectors.selectAll(store.getState());
  console.log("allBooks:", allBooks);
  const dispatch = useDispatch();
  return (
    <div>
      <h3>Books</h3>
      <button
        onClick={() => {
          setCount(count + 1);
          dispatch(
            bookAdded({ id: `${count}`, title: `book ${count.toString()}` })
          );
        }}
      >
        Add a book
      </button>
      <h4>Book Title</h4>
      {allBooks &&
        allBooks.map((book, index) => {
          return (
            <div key={index}>
              <h5
                onClick={() => {
                  dispatch(bookRemoved(book.id));
                }}
              >
                {book.title}
              </h5>
            </div>
          );
        })}
    </div>
  );
};
```

booksSlice.tsx
```typescript
export interface Book {
  id: string,
  title: string
}

const booksAdapter = createEntityAdapter({
  selectId: (book: Book) => book.id,
  sortComparer: (a, b) => parseInt(b.id) - parseInt(a.id)
});

const booksSlice = createSlice({
  name: 'books',
  initialState: booksAdapter.getInitialState(),
  reducers: {
    bookAdded: booksAdapter.addOne,
    bookRemoved: booksAdapter.removeOne,
  }
})

export const booksSelectors = booksAdapter.getSelectors((state: State) => state.books);

export const { bookAdded, bookRemoved } = booksSlice.actions;

export default booksSlice.reducer;

```

This is the screen
![issue](https://user-images.githubusercontent.com/31304661/77811996-bda6d000-70e1-11ea-845b-d336102ca337.gif)

**Comment by markerikson** [comment]
@tranceyos2419 : it looks like it's because you're not reading from the store correctly.

Short answer is, you need to use the React-Redux `useSelector()` hook, instead of trying to call `store.getState()` yourself:

```js
const allBooks = useSelector(booksSelectors.selectAll);
```

That way, the component will actually be notified when the store state changes, and try to re-run your selector to get the new data.

The [RTK Advanced Tutorial](https://redux-toolkit.js.org/tutorials/advanced-tutorial) shows some use of the hooks, and also look at [the React-Redux hooks API reference](https://react-redux.js.org/api/hooks).
