### ISSUE TITLE
It's difficult to override return type of selectors for entity adapters with union types

### ISSUE THREAD

**Issue by smajl** [reduxjs/redux-toolkit#451]
Consider this example:
```typescript
const tabsAdapter = createEntityAdapter<ListTab | DetailTab>();
const tabsSelectors = tabsAdapter.getSelectors<MyState>(
  (state) => state.tabs,
);

function MyComponent(props) {
  const tab = useSelector((state: MyState) => tabsSelectors.selectById(state, props.id));
  // here I need to do unnecessary checks if tab is List or Detail
  ...
}
```
I can guarantee that getting tab by specific ID will return only one specific type, therefore I need to have something like `selectById<T>` to override returned type to `T | undefined`, or `getSelectors<S, T>` for factoring all selectors with `T` override.

I was hoping to use `EntitySelectors<T, V>` interface but it's not exported.

**Comment by phryneas** [comment]
From our perspective, it can be a footgun to offer an easy way of overriding those values. 
Many people - especially when they are new to TypeScript - do assume that Generic Arguments might implicate some kind of run-time check, which they clearly don't. So if we were to offer something like `selectById<T>`, people might assume that `T` might actually return that return type instead of seeing it as the unchecked cast that it would be. 
In any case, as we cannot give such a guarantee, we shouldn't encourage that.

In addition to that, not exporting those internal types allows us to tweak them further in the future without breaking changes, so we generally try to reduce that to a minimum. 

You could always do a cast on the entityAdapter itself to get what you want:
```ts
const tabsSelectors = (tabsAdapter as EntityAdapter<ListTab>).getSelectors<MyState>(
  (state) => state.tabs,
);
```

**Comment by smajl** [comment]
@phryneas Thanks, I was trying to cast it in the selector function, you hinted me to cast the adapter as well (which is not enough), but the combination of both finally works:
```typescript
export const listTabsSelectors = (tabsAdapter as EntityAdapter<ListTab>).getSelectors<
  MyState
>((state) => state.tabs as EntityState<ListTab>); // EntitySelectors<ListTab, MyState>
```
