### ISSUE TITLE
updateQueryData returns an auto-batched action by default

### ISSUE THREAD

**Issue by HHK1** [reduxjs/redux-toolkit#4525]
It looks like `updateQueryData` will return an action that is auto-batched by default.

I'm not finding any trace of that in the documentation, is that missing? I'd love to understand why this one is batched.

Also, how can I opt-out of the auto-batch in that case?

**Comment by HHK1** [comment]
Sure, I'm running a mutation followed by a pessimistic update (which uses the `updateQueryData`).

In the handler executing the mutation, I'm awaiting for it to return, and toggle an internal component state afterwards.
It seems that the batch behaviour sometimes leave me in an undesired state where my component has re-rendered with the internal state already toggled but without the data coming from the store, making it flicker for just a RAF tick.

I understand you won't document which internal actions are batched and which are not, but in that specific case I was a bit surprised to see it was the default.

On the other hand I think the documentation could be improved on how to opt-out. Right now besides dispatching a "mock" action immediately after that doesn't have the `SHOULD_AUTOBATCH` set to true, I don't see how I can prevent that action from being batched.

**Comment by phryneas** [comment]
Even if we remove the autobatching here, you will have a lot of problems getting a synchronization between local React component state and Redux state - React 18 batches both internal state updates and Redux updates differently, so there will always be one render between them.

This supposedly will change in React 19, but the general sentiment probably stays the same: the same way Redux does batching here, React will do batching, too. It's very unlikely you'll manage to synchronize those, unfortunately.

What we can guarantee is that Redux state is always in sync with Redux state. So while I'm generally not a big fan of pulling local state into globl state, in your case that might be a solution.

**Comment by HHK1** [comment]
>So while I'm generally not a big fan of pulling local state into globl state, in your case that might be a solution.

Yes that would work of course, but that's not ideal ☺️

If I may insist, could you explain why the `updateQueryData` is batched by default? I'm not sure to understand why it would be desirable.

Also, can you confirm that there is no way to opt-out of the batch besides dispatching a non-batched action?

**Comment by markerikson** [comment]
We updated _all_ RTKQ-related actions to be batched by default, with the assumption that will ultimately improve rendering perf for apps.

Internally, `updateQueryData` is a thunk that dispatches another thunk, `patchQueryData`.  That in turn finally dispatches the `queryResultPatched` action, which is what's actually batched.

The thunk internals are not exposed to the user, so there's no way to intercept that action or anything from userland code.  The only possible technique I can think of would involve a custom middleware that specifically watches for that action, but then you'd somehow have to distinguish between this _one_ case and all the other potential times you might want to use it.

As Lenz said, I think the real issue here is probably more about timing between React state updates and externally-triggered state updates, than with the autobatching specifically.

**Comment by phryneas** [comment]
One addition here, too:

Only notifying the React component about new content is batched here. If your React component rerenders for a different reason, the new store content *will* already be available.

**Comment by HHK1** [comment]
In the end I used a derived state computed from my react internal state and my redux data. In the short interval when my react state is updated, but the redux store has not yet notified the component of the changes, that was enough to fix my issue.

Also for reference, I was able to force a flush of the store by dispatching a dummy action that was explicitly not batched. It did solve the issue but was not super elegant, hence the derived state solution which seems more appropriate
