### ISSUE TITLE
createAsyncThunk cannot pass non-serializable arg

### ISSUE THREAD

**Issue by terrierscript** [reduxjs/redux-toolkit#453]
I try to use `createAsyncThunk` with non-serializable object like:

```ts
export const roundAsync = createAsyncThunk(
  "someAsync",
  ({ api }: { api: ApiClient }) => {
    return api.apiAction()
  }
)
```

and I got error

```
index.js:1 A non-serializable value was detected in an action, in the path: `meta.arg.api`. Value: ApiClient {} 
Take a look at the logic that dispatched this action:
```

I found this issue ignored `meta.args` by default
https://github.com/reduxjs/redux-toolkit/pull/410

but maybe `createAsyncThunk` fire `meta.arg`

Additionaly, I try  customize `serializableCheck.ignoredPaths` option, I cannot resolve this too.
This maybe not passed `ignorePaths` params  to `findNonSerializableValue`
https://github.com/reduxjs/redux-toolkit/blob/a1e8becbb2e4653d721bdc1d2363a45562c526a2/src/serializableStateInvariantMiddleware.ts#L157-L162

**Comment by markerikson** [comment]
Eep.  Yeah, we originally called that `meta.args`, but it looks like at some point in the development process that got renamed to `meta.arg` instead.

@phryneas , which way do we want to call it?  We either need to either keep `meta.arg` and change the serialization ignore field to match, or rename to `meta.args`.

**Comment by phryneas** [comment]
@markerikson I think the renaming to `meta.arg` was done as the asyncThunk takes only one arg, not multiple ones. So by that logic I'd opt for keeping `meta.arg` and changing the field match.

**Comment by markerikson** [comment]
Okay.  You got time to make that edit and fix whatever tests aren't catching this?

We should probably use `createAsyncThunk` in the test - without looking at it, I bet it's a hand-written action, so this change didn't get caught.

**Comment by phryneas** [comment]
I can take a look tomorrow.

**Comment by phryneas** [comment]
Okay, looking at the code I have questions.

Right now, it looks like we are using `ignoredPaths` only for state paths and then use the default value to put in `meta.args` (or in the future, arg) for action paths.
Which means, ignored action paths are not overridable. Also, there's just no test for action paths, since those weren't overridable and I believe we just patched that in somehow a while ago.

While I'm at it: Want to make it possible to override action paths by doing an ignoredPath like `["action.meta.arg"]`?

**Comment by phryneas** [comment]
Let's move that discussion into the PR (if there's any reason for discussion :) )
