### ISSUE TITLE
Best pattern for reused `selectFromResult`?

### ISSUE THREAD

**Issue by acolchagoff** [reduxjs/redux-toolkit#4538]
I've got an implementation that looks like this:

```javascript
// The usual RTK query api declaration above here ^^^
// Export the generated hooks and the API service 
export const {
  useGetModelQuery,
  useGetModelByIdQuery,
  useCreateModelMutation,
  useUpdateModelMutation,
  useDeleteModelMutation,
} = modelApi;

export const useGetModelByPathnameQuery = (pathname) => {
  return useGetModelQuery(undefined, {
    selectFromResult: ({ data }) => {
      return data?.find(({ path }) => path === pathname) || {};
    },
  });
};
```

I feel like I'm off the map, All the examples I've found in the documentation declare `selectFromResult` in the component, but I don't want to redefine the same `selectFromResult` in every one of the dozen or so components that pull this data. What is the prescribed pattern??

**Comment by markerikson** [comment]
Yes, you can define it outside the component (and reuse it if you want).  There's nothing specifically special about defining it inline, we've mostly done that because it's more obvious what's going on.

**Comment by acolchagoff** [comment]
@markerikson does reading a variable from the outer scope interfere with `selectFromResult`'s ability to memoize?

**Comment by markerikson** [comment]
Not sure what you're asking, exactly.

`selectFromResult` is not memoized in any way by itself.  Instead, it's kind of like the old `connect / mapStateToProps` API.  You are expected to return an object, and if the _contents_ of the object have changed (based on a "shallow equality" comparison) have changed, it will force a re-render.

That's why you might want to use a memoized selector _inside_ of a `selectFromResult` function in order to keep the particular field you're defining as a consistent reference.

**Comment by acolchagoff** [comment]
thank you, Despite my poor question you've answered it. Good catch on the empty object.
