### ISSUE TITLE
How to use RTK on js engines that do not support Proxy and Reflect

### ISSUE THREAD

**Issue by ahaoboy** [reduxjs/redux-toolkit#4609]
Is it possible to provide configuration like mobx so as not to use Proxy?

```ts
const createStateProxy = <State extends object>(
  state: State,
  reducerMap: Partial<Record<string, Reducer>>,
) =>
  emplace(stateProxyMap, state, {
    insert: () =>
      new Proxy(state, {
        get: (target, prop, receiver) => {
          if (prop === ORIGINAL_STATE) return target
          const result = Reflect.get(target, prop, receiver)
```

**Comment by EskiMojo14** [comment]
no, it's not possible - Proxy is required for the features of RTK to function.

What environments are you trying to use that don't support Proxy? it's been supported in all major browsers for about 8 years from what I can tell.

**Comment by ahaoboy** [comment]
> What environments are you trying to use that don't support Proxy? i

https://github.com/ccxvii/mujs

Both mobx and solidjs support the use of configuration to remove Proxy dependencies so that they can run in similar embedded engines, even if it will cause some functional limitations

**Comment by markerikson** [comment]
Immer specifically dropped proxy support by default several years ago.

We _had_ that optional Immer proxy support still enabled from within RTK up through 1.9.  But in RTK 2.0, we turned off that optional support because it always added to the bundle size.

So yes, as of RTK 2.0, Proxy support is absolutely required because we use Immer 10 and it requires Proxies.
