### ISSUE TITLE
How are we to handle multiple calls of the same thunk actions on the same slice?

### ISSUE THREAD

**Issue by dorsharon** [reduxjs/redux-toolkit#468]
In one of the examples of `createAsyncThunk` you put in the fetching action:
```
   if (loading !== 'pending' || requestId !== currentRequestId) {
      return
    }
```

First, what if I, for example, wants to perform two different actions, on the same slice, and add this check to both action to make sure that each of them doesn't accidently run twice in a row.
What is a good solution to handle this? The "loading" key is common on the slice, are we to make a "loading" key per action on the slice?

Second, what is the reason behind pushing for enums for "loading" values instead of booleans?

**Comment by markerikson** [comment]
We generate a unique `requestId` for every time the generated thunk is dispatched.  If you want to be able to distinguish between, say, `"thunkA"` being called twice in a row and `"thunkB"` being called twice, your best option is probably passing in some consistent string as part of the thunk args and referencing that in your reducer logic.

Per the enums thing, yeah, that goes along with [our recommendation to try to treat reducers as state machines if possible](https://redux.js.org/style-guide/style-guide#treat-reducers-as-state-machines).

**Comment by dorsharon** [comment]
Is there a way to prevent this even before the pending action gets dispatched in `createAsyncThunk`?
I'd rather my logs not getting confusing with a few 'pending' actions and one 'fulfilled' later.

I've tried doing it at the component level, but that's tricky, because sometimes, I have two components at different locations in the tree trying to fetch the same data, and the selectors can't seem to by synced in time sometimes to prevent it...

**Comment by markerikson** [comment]
The generated thunks dispatch the `pending` action immediately, before your payload creator callback is executed.  There's no way to skip that.  

Best suggestion I have atm is to have the reducers store whatever "name" you give the thunk + the `requestId`, ignore the `pending` action if there's one already going, and have the payload creator bail out of the actual request immediately, and then have the reducer ignore the ensuing `fulfilled/rejected` action because it's the right "name" but the wrong `requestId`.  They'll still show up in the logs, though, unless you were to add a custom middleware that blocked them from reaching the reducers and the devtools.

It's the tradeoff between using an abstraction and hand-written logic.  The abstraction saves you from writing some code, but at the cost of assumptions and flexibility.

I suppose you could write your own actual thunk function and use the generated action types from `createAsyncThunk` to at least save you the work of writing those if this is a serious concern for you.

**Comment by phryneas** [comment]
@dorsharon you might be interested in https://github.com/reduxjs/redux-toolkit/pull/513
