### ISSUE TITLE
Missing type re exports in the latest versions

### ISSUE THREAD

**Issue by itwaze** [reduxjs/redux-toolkit#4764]
In the version `2.2.6` I was able to import these types:
```
import { Middlewares } from "@reduxjs/toolkit/dist/configureStore"
import { GetDefaultEnhancers } from "@reduxjs/toolkit/dist/getDefaultEnhancers"
import { GetDefaultMiddleware } from "@reduxjs/toolkit/dist/getDefaultMiddleware"
```

In the latest versions I'm not able to import them at all. 

I need these types in order to prepare `middleware` and `enhancers` for `configureStore` like:
```
const enhancers = condition ? (getDefaultEnhancers: GetDefaultEnhancers) => getDefaultEnhancers().contact(...extraEnhancers) : undefined;
const middleware = condition ? (getDefaultMiddleware: GetDefaultMiddleware ) => getDefaultMiddleware().contact(...extraMiddlewares) : undefined;

confugureStore({ reducer, enhancers, middleware })
```

Can these types also be re exported?

**Comment by EskiMojo14** [comment]
We don't recommend handling your enhancers and middleware like this because you'll lose type information - getDefaultMiddleware gets its types from your state, and getDefaultEnhancers gets its types from your middleware. Similarly, I'm pretty sure conditionally disabling your middleware will result in further loss of type information.

What condition would you want your enhancers and middleware to be disabled for?

**Comment by itwaze** [comment]
@EskiMojo14 the application has complex flow with multiple stores but about computed types you are right, probably need to choose a different approach. Thanks.
