### ISSUE TITLE
How can we create a generic-case handling reducer?

### ISSUE THREAD

**Issue by dorsharon** [reduxjs/redux-toolkit#480]
So far, I've handled all loading status with the method shown here:
https://medium.com/stashaway-engineering/react-redux-tips-better-way-to-handle-loading-flags-in-your-reducers-afda42a804c6

It was easy and saved a lot of work, but when using `redux-toolkit`, there seems to be no way to creating a reducer that handles in some way every action that comes through it.
`createSlice` and `createReducer` both only accept an object of specific action types.

Is there a way to recreate the method used there?
Is there an otherwise alternative, good-practice way to handling loading states with the toolkit?

**Comment by markerikson** [comment]
Yeah, you can't do that with either `createReducer` or `createSlice`, because they're both predicated on explicitly matching exact action type strings vs doing string contents checks.

The good news is that the reducer shown in that article will work just fine in an app that uses RTK - just add it as another slice of the state.

While we don't have any specific recommendations regarding loading state as a whole, yet, we're trying to start suggesting use of state-machine-style enums rather than boolean `isLoading` flags.  See https://redux.js.org/style-guide/style-guide#treat-reducers-as-state-machines as an example.
