### ISSUE TITLE
Using slices within components, without Redux, possibly with `useReducer`

### ISSUE THREAD

**Issue by vlopp** [reduxjs/redux-toolkit#484]
How about using `createSlice` locally, within components, possibly with `useReducer` to alleviate prop drilling issues? I reckon it'd work much like `useReducer` itself, except with all the goodness the Toolkit provides. Has somebody thought of such a use case? Are there any reasons why I should not do so?

```ts
// This is not needed, but with a factory function we get to export the type
const createContactsBrowserSlice = () => createSlice(/* code here */);
export type ContactsBrowserSlice = ReturnType<createContactsBrowserSlice>;

const ContactsBrowser = () => {
    
    // we can extract this into a hook
    const slice = useLazyRef(createContactsBrowserSlice);
    const [state, dispatch] = useReducer(slice.current.reducer);
    
    return <SomeComponent contactsBrowserDispatch={disaptch} contactsBrowserState={state}></SomeComponent>
}
```

**Comment by markerikson** [comment]
Yep, you can absolutely use reducers generated by `createReducer` and `createSlice` with React's `useReducer` hook.  I've done it several times myself.  

That's one of the nice things about reducer functions.  They don't have any direct dependency on Redux in and of themselves, they're just functions.  Even when using something like RTK, you could use a reducer with both a Redux store and `useReducer`.

I am a bit confused what you're doing there with the `createContactsBrowserSlice` bit.  Why does that need to be lazily?  Creating a slice should be a one-time thing.  If you really need its type, I _think_ you can just do:

```js
const createContactsBrowserSlice = createSlice({/* */});
export type ContactsBrowserSlice = typeof createContactsBrowserSlice;
```

**Comment by vlopp** [comment]
@markerikson 

Your solution will make the slice global (so, basically, we're back to using Redux, I think?). The one I provided will allow every *instance* of the component to have its own slice, while also keeping it typed.

**Comment by markerikson** [comment]
There's no such thing as a "global slice".  A slice is an object containing a set of functions.  There's no "instances".  You only need to call `createSlice` once for any given reducer function + actions that you're trying to define.

You can pass the exact same `someSlice.reducer` function to as many `useReducer` hooks as you want, in as many components as you want.  Each component will have its own copy of the state from each `useReducer` hook, because that's how React already handles state.  But, they can all use the same reducer function reference.

**Comment by vlopp** [comment]
@markerikson
 
Ah, correct. Awesome. For whatever reason, I had the idea slices do something to keep their state.

Thanks!

**Comment by markerikson** [comment]
Yeah, that's the whole point of reducer functions in the first place :)  They're "stateless", in the "not like a class instance" sense.  That's why `state` is the first arg.

**Comment by markerikson** [comment]
@tkambler : see https://github.com/reduxjs/redux-toolkit/issues/485 (but also note that that really has nothing to do with this closed issue).

**Comment by phryneas** [comment]
Of course you can use `reselect`. A reselect selector is just a function.

**Comment by markerikson** [comment]
@maksnester : Reselect is actually completely unrelated to Redux at the API level :)  It's a 100% standalone library that can be used with _any_ JS data.

It's just that it was originally written for use with Redux apps, and has been commonly associated with Redux since then.

But yeah, you can totally use `createSelector` in literally _any_ JS code, regardless of whether or not you're using Redux.

See https://redux.js.org/usage/deriving-data-selectors for some related thoughts.

**Comment by maksnester** [comment]
@markerikson @phryneas ah, sure... thanks for pointing it out guys.
