### ISSUE TITLE
Solution offered by the documentation about circular deps in createSlices doesn't work

### ISSUE THREAD

**Issue by cluk3** [reduxjs/redux-toolkit#501]
In the last part of [this section](https://redux-toolkit.js.org/usage/usage-guide#exporting-and-using-slices) of the documentation it states:

> In this case, you might define some common action types in a separate file using createAction, import those action creators into each slice file, and handle them using the extraReducers argument.

I tried this approach in my app and it doesn't work, I reproduced [the issue in codesandbox](https://codesandbox.io/s/falling-star-swnr3?file=/src/list.js)

As you can see the problem is that by default when creating a reducer with createSlice, it appends the the name of slice to the action type. So the action created in `commonActions` while return an object with type `lists/addList`, but the reducer created by createSlice will listen to actions of type `lists/lists/addList`...

 ## Solutions not involving a patch:

In my app what I'm actually doing is to not have common actions and just use a string as key of the extra reducers which is not a best practice at all but it's the only solution I can think of at the moment.

Another solution could be to create an action like: `createAction('addList')`, and then in the extraReducers of the item slice use `['lists/' + addList]` as a key, but I don't see it much cleaner of the previous.
 
## Solutions involving a patch:

Probably what can be done is to use the builder API and then check if what we are passing as a first argument is function or a string. in case it is function we should not create a new action. Also we could check if the action name has already the `${sliceName}/` prefix in front of it, in that case it should not be added.

**Comment by markerikson** [comment]
The use of `extraReducers` is the important thing here.  You're trying to pass `addList` to `reducers`, which is not what the instructions said.  The `addItem` usage looks correct.  So, in plain JS, all you should need is:

```js
const slice = createSlice({
  name: 'lists',
  initialState,
  reducers: {},
  extraReducers: {
    [addItem]: (state, action) => {
        // logic here
    },
    [addList]: (state, action) => {
        // logic here
    }
  }
})
```

In fact, if you _only_ are using `extraReducers` and no actual `reducers`, this devolves down to just [use of `createReducer` by itself](https://redux-toolkit.js.org/api/createReducer).

Also, as a side note, [our new `createEntityAdapter` API](https://redux-toolkit.js.org/api/createEntityAdapter) is specifically meant to help with the process of storing and updating data in a normalized state structure, and should be able to replace the update logic you've got in that sandbox.

Finally, adding a prepare callback like `createAction("someType", a => a)` doesn't do anything useful, because that's effectively what `createAction` already does.

**Comment by cluk3** [comment]
Hey Mark, thanks a lot for the extra quick answer. I actually feel stupid for not having figured it out myself, it makes totally sense!
And yeah, I'll take a look at createEntityAdapter for sure

**Comment by markerikson** [comment]
Sure.

If the lists state doesn't have any further custom logic besides the basic "add/load"-type behavior shown in the sandbox, this could be as simple as:

```js
const myListAdapter = createEntityAdapter();

const listsReducer = createReducer(
  myListAdapter.getInitialState(),
  {
    [addItem]: myListAdapter.addOne,
    [addList]: myListAdapter.addMany
  }
)
```

It's likely that your actual app is more complicated than that, so `createSlice` would be needed if you do have any logic that's "custom" to this reducer vs just listening to action types that are defined elsewhere, but hopefully that illustrates both my point about `createReducer` and how `createEntityAdapter` might fit in here.
