### ISSUE TITLE
Immer only proxies plain objects and arrays

### ISSUE THREAD

**Issue by mradenovic** [reduxjs/redux-toolkit#515]
One can mutate state only if it is a plain object or an array.

This should be explained in the documentation, and probably in the default template. For someone who is just starting with redux toolkit (like myself :blush:), it is not obvious why the example from the documentation works:

```js
const counterReducer = createReducer(0, {
  increment: (state, action) => state + action.payload,
  decrement: (state, action) => state - action.payload
})
```

and it doesn't work if changed:

```js
const counterReducer = createReducer(0, {
  increment: (state, action) => { state += action.payload },
  decrement: (state, action) => { state -= action.payload }
})

**Comment by markerikson** [comment]
There's a couple different issues in that snippet, but they aren't actually a problem with Immer - it's really understanding how JS works:

- Even if `state` were an object or an array, assigning to `state` by itself only changes what the local variable name in this function points to.  Immer works by tracking mutations _inside_ objects and arrays.  If I do `state = {}`, Immer has no way to track that.
- Similarly, since `state` in this case is a primitive (a number), incrementing the local variable doesn't do anything.

We do have plans to rework the tutorials over in #371 .  I'll close this for now, but maybe we can try to clarify that aspect over there.
