### ISSUE TITLE
Suggestion: adapter.updateOne should throw if id unknown

### ISSUE THREAD

**Issue by tkrotoff** [reduxjs/redux-toolkit#532]
`booksAdapter.updateOne(state, { id: 'unknown', changes: { ... } })` should throw if id cannot be found instead of silently do nothing.

Same for updateMany, removeOne and removeMany.

In development / test only?

**Comment by markerikson** [comment]
I see the point of the suggestion, but I would generally say that reducers shouldn't throw any errors because that's a side effect.  See https://github.com/reduxjs/redux/issues/1960#issuecomment-248025505 for a related discussion.

In this specific example, doing nothing _is_ a correct response, and goes along with the suggestion to [model actions as "events", not "setters"](https://redux.js.org/style-guide/style-guide#model-actions-as-events-not-setters).  Reducers should decide whether it's appropriate to make any state updates at all, and that decision can be based on more than just the action type.  In this case, even though the type matched, the reducer effectively sees that there's nothing relevant to do, and no-ops out.

**Comment by tkrotoff** [comment]
Humm What about a console.warn in dev mode to prevent mistakes?

**Comment by markerikson** [comment]
I don't feel this is a sufficient enough issue to warn about.  After all, nothing's actually _breaking_ here.  If a reducer needs specific data in the action to work right, it's up to you handle that when you dispatch it, and there's nothing different about these reducers in that respect.
