### ISSUE TITLE
Thanks :)

### ISSUE THREAD

**Issue by clenemt** [reduxjs/redux-toolkit#534]
First, let me thank you for the time all of you put in this toolkit.

The doc is well put and really takes you on a good tour of Redux. Sadly we had a hard time migrating out of our custom setup. I would say our knowledge of Typescript is at fault here. Below are some of our pain points.

* Could not figure out how to type the dispatch for `createAsyncThunk` so that we could use `dispatch(myActionCreator).then()` inside an effect without ts errors. We were using the `connect()` components and not the `useDispatch`. We found out later that it was not in favor anymore.
* Hard to migrate from using a promise middleware to `createAsyncThunk`. Previously it allowed us to pass a meta field that was used by some of our custom middlewares.
* Moving from ducks to slices might deserve a very light tutorial in the section
* Three websites (redux, react-redux, redux-toolkit) that all have a piece of the knowledge, look kind of similar and have the same favicon 😄 

Thanks again (you can close this issue, just wanted to let you know of those pain points)

**Comment by markerikson** [comment]
Hey, appreciate the feedback.  Some quick thoughts:

I think there's two different potential issues with the thunk typing.  First, the standard `Dispatch` types doesn't know anything about thunks.  The Redux-Thunk `ThunkDispatch` type _does_, but both `connect` and `useDispatch` assume you're using the standard `Dispatch` type by default.  With `useDispatch`, it's fairly straightforward to tell it you're using a customized version of `dispatch`, like `const dispatch : MyCustomAppDispatch = useDispatch()`.  For `connect`... I'm not sure, and it likely depends on how you're using `mapDispatch` + `connect` and declaring types for your own component.  (Either way, that's technically a React-Redux question, not an RTK question.)  

Also, `createAsyncThunk` thunks do return a promise, but not for the actual value - they return the final action object, which you can then "unwrap" to get the desired value.

@phryneas might be able to give a bit more detail on both those aspects.

Along that line, there's definitely overlap between the three sites, but that's because they _are_ three different libraries with different APIs and different responsibilities.  I've occasionally thought about trying to combine the docs sites together, but that would likely be very difficult with our current multi-repo setup.  I don't have time to look into trying to migrate things to a monorepo any time soon, so we'll have to stick with the current sites as they are.

`createAsyncThunk` is an abstraction layer, and like most of the APIs in RTK, it's aimed for the 80% common use case of data fetching.  The tradeoff of using an abstraction layer like `createAsyncThunk` is that it does limit flexibility.  While we give you the tools to customize the payload and error values in the dispatched actions, it doesn't give you any way to add anything to `action.meta` right now, and I'm not sure if there's really a good way to allow that.  You can certainly keep using your existing promise middleware if you want to, or write thunks by hand that do the same thing.  

"Slices" are basically ducks already.  A "duck" is defined as a single file with your Redux action types, action creators, and reducer, with the reducer as the default export and your action creators as named exports.  Given that, there shouldn't be any real obstacle to migrating an existing duck file to use `createSlice` - it's basically replace the existing reducer and delete the action creators + types.

**Comment by phryneas** [comment]
Yeah, the "three websites" thing might seem counter-intuitive, but realisticly, it's also "three projects". It gets even more complicated as the `react-redux` typings are community-maintained so that stuff is always moving and I personally don't really notice when that happens.

On that specific point: using `connect` with TypeScript might seem a bit weird at first, but it isn't really that bad once you got the hang of it. If you still want to use it, I've added a small example sandbox here:
https://codesandbox.io/s/dry-surf-zd12g?file=/src/App.tsx


Also see the docs on typing react-redux: https://react-redux.js.org/using-react-redux/static-typing#typing-the-connect-higher-order-component
