### ISSUE TITLE
Question about size of slices

### ISSUE THREAD

**Issue by potty** [reduxjs/redux-toolkit#540]
We are trying to adopt redux-toolkit in our project and the idea of slices. The recommended approach is to put everything into one slice file (reducer, thunks, selectors).

The problem is we have some core business entities, that are really big and app is basically built mostly around them. Currently, we have Redux stuff split into modules that contain separate files for actions, reducer and selector. For example one of our core modules has reducer about 600 lines long, actions are about 800 lines and selectors about 200 lines. If we put this together into one file, it would be a mess.

What approach are you using for such cases? Should we try to rethink our reducer structure and split it into smaller pieces?

**Comment by markerikson** [comment]
[File structure is ultimately always up to you](https://redux.js.org/faq/code-structure#what-should-my-file-structure-look-like-how-should-i-group-my-action-creators-and-reducers-in-my-project-where-should-my-selectors-go) - Redux itself doesn't care how you organize your files.

The point of [recommending "ducks"-style files](https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-or-ducks) is that:

- Many people have complained about "needing to touch a dozen files to edit one feature"
- `createSlice` basically [gives you "ducks" files for free](https://redux-toolkit.js.org/usage/usage-guide#exporting-and-using-slices)
- In general, the community has converged on trying to co-locate related code, rather than splitting things up by type

So, yes, as a general suggestion, we encourage people to put all Redux logic for a feature in a single "ducks/slice" file.  If your code is too large, feel free to split it up in whatever way makes sense for your team.

(Also, there's a good chance that `createSlice` will reduce the size of the code you already have in the codebase.)
