### ISSUE TITLE
removeAll method of entity is not working.

### ISSUE THREAD

**Issue by JYPark88** [reduxjs/redux-toolkit#541]
https://github.com/reduxjs/redux-toolkit/blob/c89d5e2c6d3a4c1cc14a96db94d823314c4624e4/src/entities/unsorted_state_adapter.ts#L67-L72

Hi, teams.
I tested removeAll method, but it didn't work.
It looks incorrect usage of Object.assign.

```javascript
function removeAll(state: R): any { 
   return Object.assign(state, { 
     ids: [], 
     entities: {} 
   }) 
 } 
```

`state` parameter should be placed at first of params

can you check it?

**Comment by phryneas** [comment]
This might be a bug, but it's more complicated.

Usually, the functions of the entityAdapter are conceptualized to be non-modifying and return a modified copy.
This is ensured by this line: https://github.com/reduxjs/redux-toolkit/blob/c89d5e2c6d3a4c1cc14a96db94d823314c4624e4/src/entities/state_adapter.ts#L38

The function in question does that.

There is one exception to that though: if an `immer`ized  object is passed into an entityAdapter function, it usually is modified instead, because it is a draft state and in the end of the wrapping invocation, a new copy will be returned anyways.

This is what you found: removeAll does not do that - it's always non-mutating. And when you use it as "mutating" within an immer-wrapped reducer function, you will encounter that error.

So I guess we'll have to make that one mutating and wrap it into `createStateOperator` as well. Do you want to open a PR for that?

**Comment by JYPark88** [comment]
Hi, @phryneas, thanks for answering quickly.

Glad for your suggestion, but I just wanted to raise the issue, and I'll wait for it to be revised.
