### ISSUE TITLE
Improve packaging: webpack uses UMD build, inlines immer, selectorator, etc.

### ISSUE THREAD

**Issue by exogen** [reduxjs/redux-toolkit#55]
**The goal:** Ideally, if I only import `createAction` then I wouldn't expect `immer` or `selectorator` to be pulled into my bundle. This is the intention behind the ESM build pointed to by the `module` field in this library's current `package.json`.

Unfortunately, webpack in its default configuration (including how it's configured in frameworks like Next.js) prefers the `browser` field to `module`, so the entire 103KB UMD build is pulled in no matter what you import. Instead of requiring people to fiddle with a non-default webpack config, it would be better to behave nicely with the defaults.

If you check out the `package.json` for `redux` and `react-redux`, they don't specify the `browser` field at all – instead, the UMD build is linked in the `unpkg` field. That way, webpack will prefer the `module` build but there's still a UMD build included.

[This comment](https://github.com/webpack/webpack/issues/4674#issuecomment-355853969) also suggests a potential way that these fields could behave together, by providing `browser` alternatives to both the ESM and CJS entry points. I'm not sure how that works exactly, but might be worth exploring.

**Comment by markerikson** [comment]
This should be resolved in https://github.com/reduxjs/redux-starter-kit/releases/tag/v0.3.2 .

**Comment by markerikson** [comment]
Hmm.  I take that back - the fix in 0.3.2 resolved the UMD build issue, but I also see the rest of the libs getting pulled into the output.

Per the example from #68 , `import {getDefaultMiddleware} from "redux-starter-kit"` in a CRA project and building it results in folders like `redux/es`, `redux-thunk/es`, `immer/dist`, and `redux-immutable-state-invariant` showing up in the sourcemap, indicating they got pulled in.

I assume this is because we're pulling it from the RSK index file, and that's causing things to not get tree-shaken.  

I don't even pretend to understand what contortions you have to go through these days to get tree shaking to work properly.  Open to suggestions :)

**Comment by markerikson** [comment]
Based on what I'm seeing in the 1.3 alphas, pretty sure this is fixed by now.
