### ISSUE TITLE
Custom action type resolution

### ISSUE THREAD

**Issue by arctouch-danielbastos** [reduxjs/redux-toolkit#561]
Our team has been looking into adding RTK to our project, but we have found a very minor nuisance: our action names use `CONSTANT_CASING`, while RTK enforces `/` as separators and favors (at least from `createSlice`) `another/letter/casing`. We believe fixing this in RTK, rather than renaming hundreds of actions in our app, would help us in gradual adoption.

While this is very minor, I believe fixing from RTK would be extremely simple. All we'd have to do is allow clients to pass an optional `getType` function to `createSlice` and `createAsyncThunk` that we could call from [places](https://github.com/reduxjs/redux-toolkit/blob/master/src/createSlice.ts#L202) [like](https://github.com/reduxjs/redux-toolkit/blob/master/src/createAsyncThunk.ts#L244) [these](https://github.com/reduxjs/redux-toolkit/blob/master/src/createAsyncThunk.ts#L254).

I'd be glad to create a PR to implement this, but I thought I should run the ideia by the RTK team first. Let me know what you think.

**Comment by markerikson** [comment]
Appreciate the suggestion, but:

RTK is deliberately meant to be opinionated about most things.  One of those opinions is [structuring action types as `"domain/eventName"`](https://redux.js.org/style-guide/style-guide#write-action-types-as-domaineventname).  I don't intend to change that, and I don't see a need to make it configurable.

I understand that that may make it a bit more difficult to adopt in your case, and if so, I'm sorry.

Is there any specific technical reason why you need to stick with the `CONSTANT_CASING` convention, or is it just a matter of familiarity?

**Comment by arctouch-danielbastos** [comment]
Hey Mark, thanks for taking the time to answer.

I think this part of the doc threw me off:

> Where multiple, equally good options exist, an arbitrary choice can be made to ensure consistency. In these rules, we describe each acceptable option and suggest a default choice.

I read this as meaning that, while `sliceName/actionName` was the arbitrary choice, other options would also be acceptable and RTK would be fine with `SLICE_NAME.ACTION_NAME`.

That said, there's no technical reason forcing us to use the latter, and we could also change this from our side. The only reason I wanted to make the change here was so we didn't need educate the whole company in using the new format, which could be a hassle in deciding for RTK. 

If there's no value for RTK in adding this change, let's close this issue.

Thanks for your time!

**Comment by markerikson** [comment]
Yeah, the intent of that phrasing was:

There's nothing different from a technical perspective between `"ADD_TODO"`, `"todos/addTodo"`, `"[Todos] Todo Added"`, and `"todos/todoAdded"`.

So, _for the purposes of the style guide and our official recommendations_, we picked a reasonable choice and went with it.

But, having picked that as a choice for the style guide in general, and having _specifically_ set up RTK to use that, I don't see sufficient benefit in making that configurable.

FWIW, I settled on that choice for a few reasons:

- It helps disambiguate action types, so that there's less likelihood of name clashes
- It goes along nicely with `createSlice` having a "name" field to it that gets prefixed with the reducer names to generate the action type strings
- It clarifies which slice the action relates to
- I've seen folks complain about the use of `CONSTANT_CASING` being less readable
