### ISSUE TITLE
Missing 'error' field after handling thunk

### ISSUE THREAD

**Issue by nikitakost** [reduxjs/redux-toolkit#568]
I need to check if the error present in response after dispatching event and if it is do some work like go to another page. But for now when I get response from promise typescript says that it does not have `error` field (but acctualy it exitsts).

```typescript
asyncIncrease().then(value => {
  console.log(value.error) // ts error here while trying to get error
})
```

Checking that I need could be done by `unwrapResult`, but in this case I must use `catch` method to prevent throwing error and error type in catch is `any`.

```typescript
asyncIncrease()
  .then(unwrapResult)
  .catch(err => console.log(err)); // err is any type here
```

[CodeSandbox example](https://codesandbox.io/s/condescending-https-rky1d?file=/src/App.tsx)

**Comment by phryneas** [comment]
`value` in your `then` case can either be a `fulfilled` action, or a `rejected` action - TypeScript knows that it is one of both, but doesn't know which one yet. And if it is a `fulfilled` action, it has no `error` property, which is why TypeScript doesn't allow you to access that property yet.

So you have to test, which one of these it is. Usually, `asyncIncrease` would contain the `fulfilled` and `rejected` actions as properties - but since you are shadowing those variables with `props.asyncIncrease`, those are not accessible the way you are writing it. So let's assume the imported `asyncIncrease` is renamed to `origAsyncIncrease` somewhere.

Then you can do either
```ts

      if (origAsyncIncrease.fulfilled.match(value)) {
         // fulfilled action
      } else {
        // rejected action
        // value.error is accessible here
      }
```
or if you are just interested in the error:
```
      if (origAsyncIncrease.rejected.match(value)) {
        // value.error is accessible here
      }
```

**Comment by nikitakost** [comment]
Thanks, this solved the problem.
