### ISSUE TITLE
Confirm createAsyncThunk's condition return type?

### ISSUE THREAD

**Issue by melanieseltzer** [reduxjs/redux-toolkit#594]
Hi all - encountering an issue with the return type of `condition` method. [The docs state](https://redux-toolkit.js.org/api/createAsyncThunk#canceling-before-execution) that you only need to return false if the condition is met. There isn't any info about also having to return something outside of that condition.

So I'm getting the following type error when only returning false:
`Type 'false | undefined' is not assignable to type 'boolean'.`

The solution is either return something outside of the condition...

```js
condition: (userId, { getState, extra }) => {
  if (someCondition) {
    return false;
  }
  return true;
}
```

Or update the typings to set the return type as `boolean | undefined` so you don't need to return something. 

I can contribute a fix to the types or add some clarification to the docs, just not sure what's the intended behavior 🙂  For now I'm returning true outside the condition.

**Comment by markerikson** [comment]
Good question. So we've clearly got the actual return type defined as `boolean` in the source, and we are doing a check of:

```ts
options.condition(arg, { getState, extra }) === false
```

so that we only bail out if a literal `false` value gets returned.

In theory, that comparison means it shouldn't matter what else you might want to return, boolean or otherwise.

On the other hand, the example in the docs is:

```js
    condition: (userId, { getState, extra }) => {
      const { users } = getState()
      const fetchStatus = users.requests[userId]
      if (fetchStatus === 'fulfilled' || fetchStatus === 'loading') {
        // Already fetched or in progress, don't need to re-fetch
        return false
      }
    }
```

Which is legal JS, and works right, but doesn't mesh with the TS types.

Mmm...I'm gonna say we oughta update the return type to be `boolean | undefined`. Seems like the simplest fix here.

**Comment by melanieseltzer** [comment]
> Mmm...I'm gonna say we oughta update the return type to be boolean | undefined. Seems like the simplest fix here.

Agreed 👍 Fix incoming!
