### ISSUE TITLE
Suggestion: createSlice action -> { payload }

### ISSUE THREAD

**Issue by riwu** [reduxjs/redux-toolkit#607]
```
createSlice({
  reducers: {
    actionType(state, action) {
      return action.payload;
    },
  },
  ...
});
```

Since the only useful attribute in `action` is `payload`, why not simplify this API to pass in `payload` as the second argument? Eg.
```
actionType(state, payload) {
  return payload;
}
```
This function signature is different from the conventional reducer but it is more convenient in the context of `createSlice` since `action.type` will never be used within the function body.

**Comment by phryneas** [comment]
Because actions can also contain `meta` and `error` when using the `prepare` notation - as they are [Flux Standard Actions](https://github.com/redux-utilities/flux-standard-action)

**Comment by riwu** [comment]
How do we dispatch an action created from `createSlice` with `meta` and `error`? 
Can you give an example?

**Comment by phryneas** [comment]
https://redux-toolkit.js.org/api/createSlice#customizing-generateprepared-action-creators

```js
createSlice({
// ...
  reducers: {
    foo: {
      reducer: (state, action) => { /*...*/ },
      prepare: (something, somethingElse) => ({ 
        payload: something, 
        meta: { foo: somehingElse }
      })
    }
  }
})
```

**Comment by riwu** [comment]
That is for defining the reducers.
How do you dispatch the action that will results in `action` being populated with `{ type, payload, meta, error}`?

**Comment by phryneas** [comment]
No, `prepare' is for defining the action creator.

It will result in an action creator with a signature of
```js
(something, somethingElse) => ({ 
        type: sliceName + "foo",         // automatically filled in:
        payload: something, 
        meta: { foo: somehingElse }
      })
```

**Comment by riwu** [comment]
I see, thanks!

**Comment by markerikson** [comment]
More reasons:

- the `extraReducers` field is for handling actions that were defined outside the slice, and those may not even be written using the FSA convention at all.  Having one set of reducers just take `payload` and the other set needing the entire action would be weird.
- Given that `(state,  action)` is the standard reducer signature, people may want to supply a prebuilt reducer function as the argument rather than defining the reducer function inline, like `addTodo: somePrebuiltAddTodoReducer`.  If we only passed in `payload`, it would be impossible to reuse existing reducers.
