### ISSUE TITLE
Abstracting away action payloads

### ISSUE THREAD

**Issue by ra50** [reduxjs/redux-toolkit#626]
Hi, thanks for making Redux Toolkit, it has gotten me to finally adopt Redux after avoiding it for a long time, I think the `createSlice` method is excellent in that it lets me directly create methods that mutate my state instead of manually creating action creators and using switch statements.  This is really close to boilerplate-free.  The one remaining issue is `PayloadAction` in TypeScript.

In the tutorials, most of the action payloads are a simple type like `number`.  In real life, they're usually objects, such as `{ propA: string; propB: boolean; propC: number }`.  Because of the forced "payload" concept, this results in a lot of repeating yourself in TypeScript, with `action: PayloadAction<{ propA: string; propB: boolean; propC: number }>` immediately followed by a destructuring statement like `const { propA, propB, propC } = action.payload`, or having `action.payload.propA` etc. throughout your function.

If I was using regular methods outside of Redux, these would be plain arguments such as `myReducer(state, propA: string, propB: boolean)`, and wouldn't be forced into a "payload" object at all.  I don't understand why action arguments need to be part of a single payload object instead of being separate, but since they do, it creates this annoying issue of repeating yourself in TypeScript.  It would be really great if Redux Toolkit had some kind of helper function to abstract away the payload concept entirely, so that I could write:

```
reducers: {
  myReducer(state, propA: string, propB: boolean) => {
    state.propA = propA
    state.propB = propB
  }
}

dispatch(myReducer(propA, propB))
```
This would remove the last bit of boilerplate using Redux Toolkit.

**Comment by markerikson** [comment]
The thing we have that _sorta_ does that is the "prepare callback" syntax:

```js
reducers: {
  addTodo: {
    reducer(state, action ) {
      state.push(action.payload);
    },
    prepare(text) {
      const id = uuid();
      return {payload: {id, text}};
    }
  }
}
```

I realize that that is also kinda the opposite of what you're asking for, because that ends up being _more_ code rather than less.

It feels like you're expressing concern about two things:

- Having to read relevant values out of nested fields in the action object
- Trying to express TS types for those fields

The issues here are:

- Redux revolves around dispatching individual action objects, not passing along multiple parameters
- Given a signature like `(state, propA: string, propB: boolean)`, we have no way of knowing how those individual fields should be organized in the action object
- The standard reducer signature is `(state, action)`, and folks do frequently write separate reducer functions that are passed as fields here.  So, that pattern has to be consistently used.
- The `payload` bit comes from [the "Flux Standard Action" convention](https://github.com/redux-utilities/flux-standard-action).  It's never been a hard requirement for using Redux, but it _is_ widely adopted throughout the Redux ecosystem.  Part of the point of RTK is to be opinionated and provide consistency in how you use Redux, and so forcing adherence to the FSA convention helps with that.
- The action creators generated by RTK already default to taking whatever you passed in to the action creator and using it as `action.payload`.  So, you can do `dispatch(addTodo({id, text}))`, and that object becomes the payload.

For the typing aspect, I've found that a lot of my actions involve dispatching complete or partial sections of my domain data types, like `PayloadAction<MyDataObject[]>`.  In that case, I've already defined a type for `MyDataObject` separately, so it's reusable.  I don't generally like writing inline object types, so if it _is_ a one-off object type, I'll go ahead and define a separate interface for that.  (Personal choice there.)

I also tend to destructure `action.payload` as the first line of a reducer if I need a few fields out of it.  I don't like doing nested destructuring (especially in function arguments), and it mirrors how I destructure state/props in components.

Ultimately, I don't see any real way we could design an API that looks like your example there.  It doesn't match how Redux is actually used or works conceptually.

I'll go ahead and close this.  If you or anyone else _does_ have an idea of how such a thing might be implemented, we can take a look at it, but tbh I don't see it happening.
