### ISSUE TITLE
TS2339: Property does not exist on type 'unknown'.

### ISSUE THREAD

**Issue by Edward-Fedoruk** [reduxjs/redux-toolkit#640]
**I've extracted type of store as described in** https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-state-type

![image](https://user-images.githubusercontent.com/31627098/85944904-6f040e80-b93a-11ea-8fb7-aabebc0d9367.png)
![image](https://user-images.githubusercontent.com/31627098/85944917-83e0a200-b93a-11ea-8860-3d5cfd59b56a.png)

**but got an error only on production webpack mode, dev mode works fine :**

![image](https://user-images.githubusercontent.com/31627098/85944933-96f37200-b93a-11ea-88e3-9ff3fb39975c.png)

**Comment by phryneas** [comment]
That & your other issue sounds like you have serious problems with your project setup and your webpack configuration. What works in one configuration between your IDE, dev and prod setup should work in all three the same.

The RTK issues are probably not the best place to ask those questions as we are not webpack experts and you will sooner rather than later will encounter the same problems with other libraries - as it is not a RTK-specific problem.

If you do not feel comfortable configuring webpack, I'd recommend you to use create-react-app, otherwise maybe someone on the #webpack channel on the [Reactiflux discord chat](https://www.reactiflux.com/) might be able to help you - or go the official support route there.

As we can't really help you with that, I'll close this.
