### ISSUE TITLE
Idea: updateAll crud method for EntityAdapter

### ISSUE THREAD

**Issue by mjwvb** [reduxjs/redux-toolkit#679]
First of all, thank you for making redux-toolkit! I really like the way it works, and I'm in the process of implementing this toolkit into my existing projects.

When implementing createEntityAdapter I found some cases where an updateAll crud method was needed. The existing updateOne/updateMany methods are already very useful. However it would be nice to have an additional updateAll method, which simply shallowly assigns values to all existing entities. Somehow I expected the method to be there, as there also is a removeAll method as well. 

I currently implement it as follows:

```
const updateAll = (state, update) => {
    for (let key in state.entities) {
        Object.assign(state.entities[key], update);
    }
};
```

Is it an idea to implement such a method as part of the EntityAdapter?

**Comment by markerikson** [comment]
Given that it's so trivial to implement this in userland, I don't immediately see a need to have this as a built-in API.  There _was_ a `entityAdapter.map()` function originally when we ported the implementation from NgRX, but we removed that because it relied on a function being passed in.  While that's okay if used as an updating util, it doesn't work if used as a reducer directly because we forbid putting functions into actions.

Appreciate the suggestion, but I think we're going to skip adding this for now.
