### ISSUE TITLE
A bug with createAsyncThunk. Error get automatically transformed in rejected reducer !

### ISSUE THREAD

**Issue by joseDaKing** [reduxjs/redux-toolkit#681]
Hi, have problem with the function createAsyncThunk funtion. When an error is thrown inside payloadCreator it will get transformed afterwards. The error is created in axios response interceptor. And in the reject action the error contains only the message property 
```javaScript

const responseErrorInterceptor = async error => {

    const { response } = error;

    if (response) {

        const { status, statusText, data } = response;

        const message = statusText;

        let errorObject = {
            status,
            message
        };

        if (status === 400) {

            const errors = extractErrors(data);

            errorObject.errors = errors;
        }

        throw errorObject;
    }

    throw error;
} 
```

```javaScript
const signUpAction = createAsyncThunk("sign-up", async input => {

    await signUp(input);

    return null;
});

const signUpSlice = createSlice({
    name: "sign-up",
    initialState: initialSignUpState,
    reducers: {},
    extraReducers: {
        [signUpAction.pending]: state => {
            state.loading = true;
        },
        [signUpAction.fulfilled]: state => {
            state.loading = false;
            state.success = true;
        },
        [signUpAction.rejected]: (state, action) => {
            console.log("rejected action:", action);
            state.loading = false;
            state.failure = true;
        }
    }
});
```

**Comment by msutkowski** [comment]
Hi there! This isn't a bug, but is the designed implementation as [explained here](https://redux-toolkit.js.org/api/createAsyncThunk#return-value) and [here](https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator). These points are relevant to you:

- If there is an error, it should either return a rejected promise containing an Error instance or a plain value such as a descriptive error message or otherwise a resolved promise with a RejectWithValue argument as returned by the `thunkAPI.rejectWithValue` function
- If the promise resolved with a `rejectWithValue(value)` return value, dispatch the rejected action with the value passed into action.payload and 'Rejected' as action.error.message
- If the promise failed and was not handled with `rejectWithValue`, dispatch the rejected action with a serialized version of the error value as `action.error`

I'm going to assume `extractErrors` just pulls `error.response.data` out... given that, you'd want to do this:

```js
const signUpAction = createAsyncThunk("sign-up", async (input, { rejectWithValue }) => {
  try {
    return await signUp(input);
  } catch (err) {
    return rejectWithValue(err.errors); // this will set the errors to `action.payload` in your `rejected` action type
  }
});
```

```js
// ... slice
[signUpAction.rejected]: (state, action) => {
            console.log("rejected action payload:",  action.payload); // being that we used `rejectWithValue`, it will be here
            state.loading = false;
            state.failure = true;
        }
```

**Comment by joseDaKing** [comment]
Thanks for the help
