### ISSUE TITLE
Problem with rejectWithValue() return type

### ISSUE THREAD

**Issue by gunner2k17** [reduxjs/redux-toolkit#717]
When i use rejectWithValue() and use string as return type, in rejected case payload i get **string | undefined** type. Why undefined is added ? For example in fulfilled case payload has only the type i provided in createAsyncThunk.

**Comment by phryneas** [comment]
Because the rejection could still be caused by an uncaught exception, which would be in `action.error`, with an undefined `action.payload`.

**Comment by gunner2k17** [comment]
Because of this **undefined**, If i assign state.error = payload, i get error **Type 'string | undefined' is not assignable to type 'string | null'.** Using  non-null assertion operator solves this problem , but is there a better way ?

**Comment by phryneas** [comment]
Well, TypeScript is absolutely right that it can be either `string` or `undefined`, because, it is possible that this returns `undefined` as action payload.

You can of course use the non-null assertion operator if you are 100% certain that you always catch everything in your thunk, but the safe thing to do were to just
```js
if (action.payload) {
  // ...
} else {
  // probably handle an unexpected error there
}
```

Or you change the type of the variable you want to assign it to - since that is accepting `string|null` anyways, it could as well accept `string|null|undefined` since apparently you'll be handling a "is not set" case there anyways.

**Comment by gunner2k17** [comment]
```
 if (action.payload) {
   state.error = action.payload;
 } else {
   state.error = action.error;
}
```
This variant looks like best option. Thanks for help :)
