### ISSUE TITLE
Unexpected token: keyword «const» [./node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js:1437,0]

### ISSUE THREAD

**Issue by owenyang0** [reduxjs/redux-toolkit#720]
`@reduxjs/toolkit@1.4.0`

While building my project with @reduxjs/toolkit@1.4.0, I got the above errors. It seems like the npm package had not been compiled correctly which threw the error from `UglifyJs`.

That would be awesome if you could republish a new correct version of @reduxjs/toolkit. Thanks

**Comment by phryneas** [comment]
UglifyJS does not support modern JavaScript, (afaik it still only supports ES5). Our ESM build is targeted for modern consumers, as most ESM builds of most libraries are.

You might want to configure your bundler to use our commonJS entry point instead of the ESM entry point - or just use a minfier that supports modern standards. ES6 is around since 2015.

**Comment by owenyang0** [comment]
> UglifyJS does not support modern JavaScript, (afaik it still only supports ES5). Our ESM build is targeted for modern consumers, as most ESM builds of most libraries are.
> 
> You might want to configure your bundler to use our commonJS entry point instead of the ESM entry point - or just use a minfier that supports modern standards. ES6 is around since 2015.
> 
> Our package.json lists both entry points, your bundler seems to pick the wrong one for your setup:
> 
> ```
>   "main": "dist/index.js",
>   "module": "dist/redux-toolkit.esm.js",
> ```

Great, thanks for filling me in.
Webpack 4 has enabled Tree-Shaking which will pick up `module` while compiling. It can be fixed by replacing `UglyfiJs` to other plugins. :)
