### ISSUE TITLE
createSlice reducer cannot properly infer the state type.

### ISSUE THREAD

**Issue by cxc421** [reduxjs/redux-toolkit#735]
I try to define the type of initial state to `createSlice()`, and according to the [document](https://redux-toolkit.js.org/usage/usage-with-typescript#defining-the-initial-state-type):

> The standard approach is to declare an interface or type for your state, create an initial state value that uses that type, and pass the initial state value to createSlice. You can also use the construct initialState: myInitialState as SliceState.

I copied the code snippet to the [CodeSandbox](https://codesandbox.io/s/rtk-ts-test-f492j?file=/src/index.ts), but it seems like the reducer cannot correctly infer the state type.

![image](https://user-images.githubusercontent.com/18439296/93988678-97759a80-fdbb-11ea-875f-3f2964181a03.png)

**Comment by markerikson** [comment]
Looks like it has something to do with the way you've defined the union of the two possible states.

This isn't an RTK-specific issue, so I'm going to close this. The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

**Comment by phryneas** [comment]
This is an unfortunate TypeScript "feature" that is a bit unfortunate:

```ts
function identity<T>(t: T) {return t}


type SliceState = { state: "loading" } | { state: "finished"; data: string };

let initialState: SliceState = { state: "loading" };

// is inferred as  { state: "loading"; }
const derivedValue = identity(initialState)
```

TS actually does some code flow analysis and sometimes "tightens" types that you yourself declared wider.

Doing
```ts
const initialState = { state: "loading" } as SliceState;
```

would work as well here, as it is an implicit cast.

We might need to check our docs for this in a few places.

**Comment by cxc421** [comment]
Got it, thank you!

**Comment by cefn** [comment]
I'm concerned this documentation guides people towards the practice of routinely bypassing the compiler. This will create runtime errors in production since they are bypassing Typescript for no obvious reason. 

Consider the following simplified example which will compile fine, but break in production when following the updated guidance (and you can see it break running in the Typescript playground).

```typescript
interface UsersState {
  error: string | null | undefined;
  entities: Record<string, string>;
}

const initialState = {
  error: null,
  // entities here omitted by mistake
} as UsersState; // tell the compiler to ignore your mistake

console.log(`Number of entities is ${Object.keys(initialState.entities).length}`); // Error: Cannot convert undefined or null to object
```

If cast hints are needed to influence type inference this should be done in a type-safe way, relying on the compiler to check the type before casting it. For example, based on the example in https://github.com/phryneas/redux-toolkit/blob/master/docs/api/createAsyncThunk.mdx this alternate approach is type safe. I believe it should be the documented approach, since the `initialState` is checked by the compiler before it is cast.

```typescript
const initialState: UsersState = {
  entities: {},
  error: null
}

const usersSlice = createSlice({
  name: 'users',
  initialState as UsersState,
  reducers: {},
  extraReducers: builder => {
    // The `builder` callback form is used here because it provides correctly typed reducers from the action creators
    builder.addCase(updateUser.fulfilled, (state, { payload }) => {
      state.entities[payload.id] = payload
    })
    builder.addCase(updateUser.rejected, (state, action) => {
      if (action.payload) {
        // Being that we passed in ValidationErrors to rejectType in `createAsyncThunk`, the payload will be available here.
        state.error = action.payload.errorMessage
      } else {
        state.error = action.error.message
      }
    })
  }
})
```

**Comment by phryneas** [comment]
@cefn Honestly, with `satisfies` just being around the corner I wouldn't want to change our advice twice in a row.

I could however imagine to have a "tip block" somewhere that goes into the details of *why* we have that weird `satisfies SliceState as SliceState` pattern there and that suggests your pattern as an alternative pattern for older TS versions.

Please don't feel in any way forced to do it, but since you already have taken on that topic: would you be willing to prepare a PR to our docs that replaces all `as SliceState` with `satisfies SliceState as SliceState` and adds such a "tip block" at a good point? (should probably go into https://redux-toolkit.js.org/usage/usage-with-typescript#defining-the-initial-state-type)
