### ISSUE TITLE
Help to discover action creators called without dispatch?

### ISSUE THREAD

**Issue by waynebloss** [reduxjs/redux-toolkit#738]
One of our most frustrating issues when using Redux, by far, is when we catch ourselves mistakenly calling action creators and forgetting to dispatch them.

Is there anything that Redux Toolkit can do to help avoid this?

I suppose that if there's no way to catch it before running the code, our best bet would be to pre-bind all of our actions before exporting them to the rest of our code that will call those actions. I wanted to avoid doing that if possible.

**Comment by markerikson** [comment]
Afraid not, no. An action creator has no idea what its result is being passed to - it's just `return {type: "something"}`.

I also don't recommend pre-binding action creators, because then that ties the rest of your app code to a specific store instance and makes it harder to test.

About the only good solution I can think of is a lint rule of some kind that would track imports from known Redux slice files, and ensure that they're only called as positional arguments to `dispatch()`.
