### ISSUE TITLE
Set the meta type for `createAction`

### ISSUE THREAD

**Issue by lioneltay** [reduxjs/redux-toolkit#745]
Is there a way to tell `createAction` what the type of meta should be in advance? Usually this would be known in advance since the meta property would be interpreted by some predefined middleware.

I have had a look at the source and the current typings and I don't think there is a way at the moment. Maybe there is another way to handle this that I am not aware of.

**Example**

```typescript
type MetaType = {
  debounce?: number;
  log?: string;
  persist?: boolean;
  analytics?: {
    type: "add-to-cart";
  };
};

createAction<PayloadType, "A_TYPE", MetaType>(
  "A_TYPE",
  (arg1: string, arg2: number) => ({
    payload: "whatever",
    meta: {
      debounce: 700,
      log: "log something..?",
      persist: true,
      analytics: {
        type: "add-to-cart",
      },
      // This should be an error, not part of MetaType
      notOnMetaType: "errorrrr",
      // anything else...
    },
  })
);
```

Great library by the way, the use of a 'builder' to build the reducer for improved typescript typings is very cool.

**Comment by markerikson** [comment]
Since the only way that a `createAction()`-generated action creator can have a `meta` field is if you provide a "prepare callback", the existence and type of the `meta` field gets inferred based on that prepare callback's return.

Are you looking at having some code attach a `meta` field to the action as it goes through the middleware pipeline, or something else?

**Comment by phryneas** [comment]
Something like this?

If you have a `prepare` argument, you don't really need to prepare a generic on `createAction`, but of course you can type the return value of the `prepare` function

```ts
createAction(
  "A_TYPE",
  (arg1: string, arg2: number): { payload: PayloadType, meta: MetaType} => ({
    payload: "whatever",
    meta: {
      debounce: 700,
      log: "log something..?",
      persist: true,
      analytics: {
        type: "add-to-cart",
      },
      // This should be an error, not part of MetaType
      notOnMetaType: "errorrrr",
      // anything else...
    },
  })
);
```

**Comment by lioneltay** [comment]
@phryneas It seems if you type the return argument you break the return type of `createAction`

EG: `actionCreator` has type any
![image](https://user-images.githubusercontent.com/20704084/94404976-31ba5180-01b3-11eb-8797-17737e17a705.png)

```typescript
const actionCreator = createAction("A_TYPE", (arg1: string, arg2: number): {
  payload: string;
  meta?: { value: number };
} => ({
  payload: "somestring",
  meta: {
    value: 5,
  },
}));
```

I'm trying to wrap `createAction` in my own `wrappedCreateAction` function that will preset the meta property type and leave the other generics as is to be inferred, so that whenever an action creator is created using `wrappedActionCreator` the `prepare` function will automatically validate the meta property without the developer having to manually type it each time.

EG

```typescript
function wrappedCreateAction<GenericToPassAlong, AnotherGeneric>(
  type: string,
  prepareAction: (...args: any[]) => {}
) {
  return createAction<MetaTypePresetSomehow, GenericToPassAlong, AnotherGeneric>(...args);
}

wrappedCreateAction('A_TYPE', () => ({
  // This will be validated and be of type MetaTypePresetSomehow
  payload: { ... },
  meta: {
    ...
  }
}))
```

My use case is that my middleware will accept an `analytics` property and automatically fire off analytics events. But the `analytics` property has to fit the type of the analytics function that will be firing the analytics events. So I want to make sure that when a developer adds a `meta.analytics` property in their action that it matches the `meta.analytics` type.

**Comment by phryneas** [comment]
@lioneltay as you can see from [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoIJJsCAOzgF84AzKCEOAcgAE0ATAVwA8ArAZwHoYIIAGwDWwGLQBQEmAE8wqOAAV0MwRHRMAKnIUBeOFxhRghAOZTZ8uAFlUMdNqv6EEuG-dNUAIwgtCSVAAuOEIWEC9UKAAaV3c3NVNgw2MzGLi3eSguYENgnyEMQjT09EJ0QRl8JC5gl3T3SyCDIxNTYriSGJIpJCJDOHQ8AkIAYTRMaDh9FAwsXHwiAApYgCJsAH1NAE1FAFEV4sX0KFMARiSW1IGTgCYLlNMASlq4MBU1DWDlVXUtHSi4CA7OhgrZ7I5UGRdAA+OCLOruN4-T7XM7tQHA2qxOKeHx+ALBADsAAZiej4hBEqibuTXpFsrk4EYWKhaaVypVgNUsfU3I1gisNEwALT8YVIY4wA7Y9ydGVuHg8OCaAAWOQMKt8giYcAiA2IkSo0RCEHgb1gcAg5BswIh8pNMAA8oQwQ4dALDdAoN7pfVFfrKmqzHBUIIuKgAHRRmVytwkR4SR4AbgkvUI-UGC2I+kzwzGs2gixW5AEBzgKy8xxWCYkqDY8jwEIAPN8Pn95NCjkMiBGkW2E3WGzBm66IZ3cz2gfYaxJyPisyH66hGzom5pOzBAppHgg0DAWFBiDASEA), it works just fine.

Your problem is that you put `Parameters<typeof createAction>[1]` in an input position and not in a generic position. That way it will never work on a specific manifestation of that type, but on the union of all possible types.

**Comment by phryneas** [comment]
You probably want something [like this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoIJJsCAOzgF84AzKCEOAcgAE0ATAVwA8ArAZwHoYIIAGwDWwGLQBQEmAE8wqOAFlUMdABU5CgLyIJcfQaaoARhBaEkqAFxxCLEMdRQANHoP7BEAOY2uMKMCEXq7u+vJQXMB+NqZCGIQhoeiE6IIy+EhcNghuoXCy8r7+gcG5BiSuJFLk5ngExADuUOhg8kwAwmiYOHVEADwACmhg6GgAYsSobFiETFxwABQAdCujXllwyTIA2gC6AJRwWgB8iCMynuhMNlvOcCAq6DbKqhryJMcLbgXWcH4BQUSYGGox6+CINiGqBG40IEkOOX0aBgLCgxBQGCwuHBhAWPzuwOhoOx9X2AG4JFUpEgiH5Nr1iDomi02p1MWD6gtaNgAPpqACaAwAorQ7gs2EUAV5DidFoi4OdLtdEBQBDY2KREg9VNkykZTLVfgB2AAMJsS7k8PjgACIrX9qCoABYlFYAfhtFoM4Ui0XyUBYqC9+mSqXSwEyury+h4PHycggcCdTgUSHQLC4qHmyTgTioUDK7hghVtVyYAFp+OW07BPYXNfXY3BjCx4DAXfMGsBBIJbBB4GmMwoc3noHd0PNUAA3VCNMRO3PTZoKqjhfBZuBiWjzPzdwToOBT1LAJhKR5vVD1wj9gDyhBe6k0Nhto6gb6gdf0VRI+32QA):

```ts
function wrappedCreateAction<PrepareFn extends (...args: any[]) => {payload: any, meta: MetaType}>(
  type: string,
  prepareAction: PrepareFn
) {
  return createAction(type, prepareAction);
}
```

Keep in mind though that extra properties on an object will not cause an error, as that object will still match your `MetaType` interface. But typos or wrong types for specified properties will.
