### ISSUE TITLE
Is there a proper way to use createAsyncThunk without any arguments?

### ISSUE THREAD

**Issue by eddyLazar** [reduxjs/redux-toolkit#747]
I'm using ts in my project and right now I need to call async actions like this `dispatch(asyncActionWithoutArg(undefined))` not to have a type error. Is there some better way for this? Couldn't find anything in docs about it. It seems to me that this is a common use case.

**Comment by phryneas** [comment]
If you don't type the first parameter to the payload creator, it should fall back to `void` as you can see in [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoIIGcCeAdkgCoAWAroQNYC+cAZlBCHAOQACaAJhQB4ArXAHoYECABtqwGGwBQcpBEK54MSjTgBeOCgxY8RUhuoAKAEQNx5gDRxTASm0A+RHLhw0MClEJxzAEboUOZytA4KSipqGthIMMDK2nDqVGYRCorKqikmAEzJepg4BMTkaRZWELb2APp26GDATlquCO6eqN6+-kEhYRlROamEcQnKBToj1HmOQA)

Are you experiencing otherwise?

**Comment by eddyLazar** [comment]
Sure but the problem is with ts typings, so if using the code you provided
```js
const thunk2 = createAsyncThunk("foo", (_, api) => {
  return "bar"
})

const thunAction2 = thunk2()
```

I get this error

```typescript
Expected 1 arguments, but got 0.ts(2554)
typings.d.ts(233, 118): An argument for 'arg' was not provided.
```

**Comment by phryneas** [comment]
The code I provided was a link to the TypeScript playground. It doesn't get any more "TS typings" than that.

What do you get when you hover `thunk2` after copying it into your codebase? 
It should be `const thunk2: () => AsyncThunkAction<string, void, {}>`

The `void` as a second generic parameter is important as it will lead to thunk2 taking 0 parameters

**Comment by phryneas** [comment]
Also, what is your TypeScript version?
Do you have uncommon settings in your `tsconfig.json`? `"strict": false`? `"noImplicitNullChecks": true`?

**Comment by eddyLazar** [comment]
Oh I found what was wrong in my code. I had any typing so that was the problem. Thanks for help.

```typescript
const thunk2 = createAsyncThunk("foo", (_: any, api) => {
  return "bar"
})
```
