### ISSUE TITLE
Revoked proxy in createSelectorCreator

### ISSUE THREAD

**Issue by suyashdeshpande** [reduxjs/redux-toolkit#757]
Sandbox: https://codesandbox.io/s/angry-banach-ugou6?file=/src/features/todos/todosSlice.js:641-672

I am using reselect with redus-toolkit.
In todoSlice, when shallowEqual method executes for the 2nd time, objA is coming as revoked proxy. Any idea?

**Comment by markerikson** [comment]
I'm not seeing any specific errors thrown in that sandbox.  

I'm also confused why you're trying to use a "shallow equal selector" inside of a reducer, and also why you're calling `JSON.stringify()` in the toggle case.  None of that looks necessary.

**Comment by phryneas** [comment]
I think I can explain it: the selector tries to compare the proxy object from the first reducer call with the proxy object from the second reducer call. But after the first reducer is finished, the proxy object is revoked to prevent it from leaking to the outside & causing memory leaks.

Bottom line: you cannot do that. Also, using memoized selectors on proxy objects is generally a bit problematic, since these objects are mutable and referential equality does not mean nothing changed on the object. So the best was of handling this would be to handle draft objects as always non-equal.
Which means:
```js
function isEqual(a,b) {
  return !isDraft(a) && !isDraft(b) && a === b
}
```

**Comment by suyashdeshpande** [comment]
@phryneas, When we use createSelector, it memoizes the previous state value so that it can compare it next time with the new state. But since the previous state will be revoked proxy (as previous reducer call has ended) it will always run the selector. Now, prev state is revoked proxy and curr state is a draft state, their equality comparison will always result in false. How will memoization work then?

**Comment by phryneas** [comment]
It will not. Why do you want to memoize something within the reducer in the first place?
