### ISSUE TITLE
redux-saga with Redux Toolkit - effects do not run

### ISSUE THREAD

**Issue by Sun-2** [reduxjs/redux-toolkit#767]
I've got a CRA setup with `@reduxjs/toolkit` and `redux-saga`.

The main saga does run. However, sub-sagas that are meant to be run on `takeEvery` or `fork`, do not seem to run at all.

**Saga:**
```ts
export function* saga() {
  console.log('main'); //logs

  fork(function* () {
    console.log('fork') //doesn't log
  });
}
```

**Store:**
```ts
const sagaMiddleware = createSagaMiddleware();
const store = configureStore({
  reducer: state => {
  },
  middleware: defaultMiddleware => defaultMiddleware().concat(sagaMiddleware)
});

sagaMiddleware.run(saga);
```
[Repo link.](https://github.com/Sun-2/saga-effects-dont-run) (Nothing but CRA + Toolkit + redux-saga)

[Related SO thread.](https://stackoverflow.com/questions/64445675/redux-saga-with-redux-toolkit-effects-do-not-run)

**Comment by markerikson** [comment]
Since sagas are an entirely separate middleware, the behavior is going to be independent of whether you're using RTK or the Redux core.  `configureStore` doesn't do anything special in that regard.

SO or the saga repo are the right place to ask about this.  Since you've got an SO question open, I'll go ahead and close this.
