### ISSUE TITLE
Strange error handling

### ISSUE THREAD

**Issue by mithrandi** [reduxjs/redux-toolkit#770]
redux-toolkit seems to think errors are supposed to look like `{type: "…", error: new Error(…)}` instead of `{type: "…", error: true, payload: new Error(…)}` but Redux seems to recommend the latter: https://redux.js.org/style-guide/style-guide#write-actions-using-the-flux-standard-action-convention

**Comment by markerikson** [comment]
The error-handling aspect of the FSA convention has always been mostly ignored by the community.  Very few people have ever used the `{error: true}` part, because then you have to do additional branching in the case for the original action type just to see if it's an error.  Almost everyone uses separate action types for the "real data" and "failure" cases.
