### ISSUE TITLE
Allow to dispatch actions with the createAsyncThunk's result

### ISSUE THREAD

**Issue by lourenci** [reduxjs/redux-toolkit#773]
What if we could be able to dispatch actions with the resolved/rejected data from `createAsyncThunk` instead of just change the store through a reducer case?

The motivations behind that:
- We could reuse already defined reducers/actions.
- We don't need to unwrap the payloadCreator's promise just to dispatch other actions.

```js
const update = createAction('update')
const counterReducer = createReducer({}, {
  [update]: (state, action) => { state.user = action.payload }
})

// This is what we have to do today:
{
  [fetchUserById.fulfilled]: (state, action) => {
    state.user = action.payload
  }
}

const fetchUserById = createAsyncThunk(
  'users/fetchByIdStatus',
  async (userId, thunkAPI) => {
    dispatch(someOtherAction())
    const response = await userAPI.fetchById(userId)
    return response.data
  }
)

// I wish we could allow doing something like this
const fetchUserById = createAsyncThunk(
  'users/fetchByIdStatus',
  userAPI.fetchById,
  (dispatch, result) => {
    dispatch(someOtherAction())
    dispatch(update(result))
  }
)
```

**Comment by markerikson** [comment]
You can already do exactly that :)  We pass `dispatch` in the second arg to the payload creator, `thunkAPI`:

https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator

So, your example would work as:

```js
const fetchUserById = createAsyncThunk(
  'users/fetchByIdStatus',
  async (userId, thunkAPI) => {
    const response = await userAPI.fetchById(userId)
    const finalPayload = response.data
    dispatch(someOtherAction())
    return finalPayload; // will dispatch `fulfilled` action
  }
)
```

**Comment by lourenci** [comment]
Thank you for your quick response. Maybe I was not clear about my intentions.

In your example, I've to unwrap/handle my promise and I've to update the store through the `extraReducers` (`fulfilled` action).
I wish I could be able to dispatch the result instead, so I could leverage an already defined reducer to change the store without worrying about the promise itself.

Instead of doing this
```js
const fetchUserById = createAsyncThunk(
  'users/fetchByIdStatus',
  async (userId, thunkAPI) => {
    const response = await userAPI.fetchById(userId) // unwrapping the promise
    const finalPayload = response.data
    dispatch(someOtherAction())
//    return finalPayload; // will dispatch `fulfilled` action
   dispatch(update(finalPayload)) // to leverage another already defined action/reducer
  }
)
```
, do this:
```js
const fetchUserById = createAsyncThunk(
  'users/fetchByIdStatus',
  userAPI.fetchById,
  (dispatch, result) => {
    // I don't need to unwrap the `fetchById` promise
    dispatch(someOtherAction())
    dispatch(update(result)) //  // to leverage another already defined action/reducer
  }
)
```

**Comment by markerikson** [comment]
I'm afraid I don't understand what you're trying to describe here.

The point of `createAsyncThunk` is that it generates new action types for you for this particular call, so that you don't have to write those yourself.

You can _handle_ this action types however you want, with whatever reducer functions you want (including reusing an existing reducer function to listen to the new action type as well).

If you're only dealing with existing action types and reducers, then you probably don't want to use `createAsyncThunk` - write your own thunk, as you always have been able to do.  `createAsyncThunk` isn't trying to solve the use case you seem to be describing.

**Comment by jon64digital** [comment]
I understand what he's trying to do because I'm trying to do the same thing.

I am using createAsyncThunk called "refreshToken" to make an API call and then returning the result. I then return the result and have a "refreshToken.fulfilled" function which does some login then needs to dispatch a call to set the tokens in redux. I already have a reducer to do that but I can't call it from within the "fulfilled" function so I have to duplicate all the code here.

**Comment by phryneas** [comment]
What "then some logic" is it that you cannot just do that within `refreshToken` before returning?

Also, you could still just write a thunk for that:
```js
const refreshAndMore = (arg) => async (dispatch) => {
  const result = await dispatch(refreshToken(arg))
  // do more here, dispatch something else
}

// in your component
dispatch(refreshAndMore("foo"))
```

Or I am really not understanding what you are trying to do, in that case please elaborate more explicitly

**Comment by jon64digital** [comment]
I think I understand, what you're saying is that instead of dispatching my asyncThunk, I create a middle-man function which dispatches, then awaits the result and does more, so the additional stuff I need to do is not in my asyncThunk or in the thunk.fulfilled"  function. 

Makes sense but it would less code if we could just call another reducer from inside createAsyncThunk()

**Comment by phryneas** [comment]
You can dispatch an action from withing `createAsyncThunk` at any time, (using thunkApi.dispatch, as per the documentation) but you have to be aware that it might trigger another rerender of your UI, opposed to just multiple reducer reacting to the same action.

But you do not "call a reducer" anywhere in Redux.

**Comment by bryndyment** [comment]
> You can already do exactly that :) We pass `dispatch` in the second arg to the payload creator, `thunkAPI`:
> 
> https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator
> 
> So, your example would work as:
> 
> ```js
> const fetchUserById = createAsyncThunk(
>   'users/fetchByIdStatus',
>   async (userId, thunkAPI) => {
>     const response = await userAPI.fetchById(userId)
>     const finalPayload = response.data
>     dispatch(someOtherAction())
>     return finalPayload; // will dispatch `fulfilled` action
>   }
> )
> ```

`dispatch(someOtherAction())` should be  `thunkAPI.dispatch(someOtherAction())` here, correct?

**Comment by phryneas** [comment]
@bryndyment yes, good spot.

**Comment by andrewlorenz** [comment]
actually, don't you mean (userId, thunkAPI) should be (userId, dispatch) ?!

**Comment by dagmawig** [comment]
I have a clarifying question on the post right above. I want to use the asyncThunk from a React component as follows:
```
dispatch(fetchUserById(userId)).then( () => {
 // here I want to perform stuff after the the dispatch inside the asyncThunk is completed 
})
```
My intention is to complete dispatch inside the asyncThunk so that it updates the UI then do some other stuff but the dispatch inside the asyncThunk is never dispatched at that point. Any idea how to solve that issue?

**Comment by andrewlorenz** [comment]
crikey @dagmawig sorry but if you think dispatching redux actions and promises go together then you need to go back and read about the principles of the redux paradigm!

You need to do something like my pattern showed - do your async thunk, then dispatch an action which - say - updates your redux store (state) with something that your UI can respond to, via classic React re-rendering.

**Comment by markerikson** [comment]
@andrewlorenz uh... Dispatching thunks and promises most certainly do go together :) and we specifically show that pattern in our docs :

- https://redux.js.org/tutorials/essentials/part-5-async-logic#checking-thunk-results-in-components
- https://redux.js.org/tutorials/fundamentals/part-7-standard-patterns#thunks-and-promises

I'm actually kind of confused by the previous comment, because it looks valid at first glance.

**Comment by andrewlorenz** [comment]
good shout @markerikson, I actually confused myself by referring to actions dispatch and promises rather than thunks,   doh.
And I've come across the unwrapResult feature in the toolkit before, so maybe I can simplify my own patterns in use with this. I'll keep it in mind the next time I have my code open - it may be I just haven't come across the need to get the result of a thunk directly inside a component, instead keeping things more pure (?) by letting thunks lead to state changes lead to component updates. In my head this pattern sounds neater, but maybe not and maybe its a very practical way to proceed.  Either way, thanks for the pointer for me (and for other readers)

**Comment by dagmawig** [comment]
@markerikson my intention is not to know the result after the action is dispatched. All I want to do is make sure the dispatch function has updated the states before I do some more stuff. This is why I wanted to do asyncThunk. Please look at the code I am working on and let me know what I need to add or modify. The examples in the articles explain doing an async stuff (like getting data from a server) then using the result to dispatch but I want the dispatching of action itself to be asynchronous so that I can do more stuff after the state update. I don't see such an example there.

I am working on a card game and the first dispatch deals a single card. Then I want that card to show up in the UI as a result of state update before I do more stuff. My code looks something like below.

`// this is my reducer function
const stateSlice = createSlice({
    name: 'black',
    {hand: []},
    reducers: {
        updateHand: (state, action) => {
            state.hand = action.payload;
        }
    }
});
// I am getting the hand state inside a React component as follows
let hand = stateSelector.hand;
// Then I dispatch a card to add it to the hand state as follows. Then do more stuff right after that dispatch is completed.
dispatch(updateHand(card)
// Do stuff here after the hand variable above is updated as a result of state change. How do I do that?
`
Thanks.

**Comment by markerikson** [comment]
@dagmawig that's what I'm saying.  When you do `dispatch(someAsyncThunk()).then()`, by the time the `.then` callback runs:

- the `pending `action was dispatched immediately
- either the `fulfilled` or `rejected` action was dispatched right before the returned promise was resolved

So the state has been updated before the `.then` callback executes.

I'm having some trouble following what else you're trying to do here, and this thread isn't really a good place to answer additional questions. If there's something further that isn't specifically about changing how `createAsyncThunk` works, I'd appreciate it if you could post the rest of your question on either StackOverflow or in Reactiflux so we can provide more direct assistance there.

**Comment by dagmawig** [comment]
@markerikson I got one last comment. Let me know if you see anything I am missing..

 I have actually tried doing like you said with the code below. But the hand state I am logging to the console is not updated. 

```
// My asyncThunk is as follows
export const asyncHand = createAsyncThunk(
    'black/asyncHand',
    async (load, thunkAPI) => {
        thunkAPI.dispatch(updateHand(load));
    }
)
// Then in React component I log the supposedly updated hand into the console as follows but what I get is not the updated hand.
dispatch(asyncHand(card)).then(() => {
            console.log(hand); // This is not logging the updated.
        })
```

What could I be missing?

**Comment by markerikson** [comment]
@dagmawig the `.then` arrow function callback was defined _during the rendering process_.  Therefore, it can _only_ ever refer to the variables that were in scope _at that time_.  Even though the Redux store state has been updated by the time this callback runs, _that render happened a long time ago_ - long before the store was updated, and _none_ of the variables in scope during that render can ever change.

Note that this isn't specific to Redux - the exact same thing would be true if you were doing async logic and referring to React component state as well.

I'd recommend reading Dan's post [A Complete Guide to `useEffect`](https://overreacted.io/a-complete-guide-to-useeffect/) to better understand closures, rendering, and "stale values".  

If you really need access to the updated Redux state just as soon as it's done, you'll need to put that logic into another thunk, which has access to `getState`.

**Comment by dagmawig** [comment]
Thanks. I appreciate the feedback.

**Comment by andrewlorenz** [comment]
Just in case this helps @dagmawig, dispatched actions actually run **synchronously**.  Take this example:
```
export const increaseMessageLimit = createAction('data/increaseMessageLimit');

export const loadEarlierMessages = createAsyncThunk('data/loadEarlierMessages', async({}, { getState, dispatch }) => {
  const { messageLimit: prevLimit } = getState();
  dispatch(increaseMessageLimit());
  const { messageLimit: newLimit } = getState();
  console.log("prev", prevLimit, "new", newLimit);
});
```
in this thunk, I dispatch the increaseMessageLimit action - which runs synchronously - so when the next line uses getState it retrieves the updated value of "messageLimit" from the store.  The console.log will show something like
```
prev 5 new 10
```
This might help you in your specific use case.

Also, it may be that you just need your UI to subscribe to the store data, which will get updated via your actions/thunks as and when.  e.g. your UI needs to know when there is either no card chosen or a card has been chosen and show a different UI block accordingly.  Why not just have your component subscribe (via "useSelector" hook) to the appropriate store state values, and get re-rendered when (some other) user interaction or code has updated it ?

**Comment by dagmawig** [comment]
@andrewlorenz thanks for the comment. My intention was not quite that. I wanted a dispatcher that returns a callback function so that I can do subsequent stuff right after state is updated as per the dispatched action... Not really include the subsequent stuff inside the action creator itself. Anyway when I thought about it at the moment I didn't even need to complicate the state update so I used setState function to manage the state of the app. I found it way easier because it gives you a callback function like below.

```
this.setState((state,props)=> ({...state, name: "dag"}), 
()=> {/* do stuff here after name update.*/})
```

**Comment by andrewlorenz** [comment]
hhmm I'm not sure I follow you, I would be concerned that you are not using state appropriately.  If the state is definitely local to a component (and any sub-components) then useState/setState is fine. Redux provides global state (as in available to any component in the tree) and may be the better pattern i.e. better than prop-drilling. I believe its better to manage all state in redux that applies globally, even if it isn't used anywhere other than a single component.  e.g. in your app - a card game - the fact that a card hasn't been dealt / 1 card has been dealt / >1 cards have been dealt is state that applies to the whole game not just 1 component in the app (and not even if only that 1 component references it).  In this case I believe your pattern should be:

1. call async thunk to deal a card
2. the thunk reads current state via getState and decides whether its dealing the first card or nth card
3. the thunk issues an action to update the store state accordingly
4. your UI component subscribes to that state (useSelector hook or equivalent as I suspect you are using React.Component)
5. that UI component has a useEffect hook or shouldComponentUpdate method that matches the state change and does the necessary additional processing that the component requires (which may include calling other thunks or dispatches, though I doubt that and again would sound like an anti-pattern to me)

hope this helps, we are totally off-topic here compared to OP !

**Comment by dagmawig** [comment]
This helps. I understand using redux for my application is overdoing it but I just wanted to learn how to use redux toolkit. I would need to read up a bit on useEffect to make sure each state update refreshes the affected part of the UI so that anything I do right after would be executed after the UI update is completed.

**Comment by AntoineC-dev** [comment]
> I have a clarifying question on the post right above. I want to use the asyncThunk from a React component as follows:
> ```
> dispatch(fetchUserById(userId)).then( () => {
>  // here I want to perform stuff after the dispatch inside the asyncThunk is completed 
> })
> ```
> My intention is to complete dispatch inside the asyncThunk so that it updates the UI then do some other stuff but the action inside the asyncThunk is never dispatched at that point. Any idea how to solve that issue?

You need to add .unwrap() like so

> dispatch(fetchUserById(userId)).unwrap().then( () => {
>  // here I want to perform stuff after the dispatch inside the asyncThunk is completed 
> })

**Comment by phryneas** [comment]
Neither in Redux Toolkit nor in Vanilla Redux you are ever allowed to dispatch in a reducer.

You can however always dispatch actions within your `createAsyncThunk` call - like it was already shown in this issue:

```js
// My asyncThunk is as follows
export const myThunk = createAsyncThunk(
    'myThunk',
    async (args, thunkAPI) => {
        try {
          // other logic
          return someResult          
        } catch (e) {
          thunkAPI.dispatch(errorAlert("error"));
          throw e
        }
    }
)
```

You could also look into using the [Action Listener Middleware](https://github.com/reduxjs/redux-toolkit/discussions/1648) to add a listener for your rejected action and do extra side effects there.

**Comment by NicholusMuwonge** [comment]
> Neither in Redux Toolkit nor in Vanilla Redux you are ever allowed to dispatch in a reducer.
> 
> You can however always dispatch actions within your `createAsyncThunk` call - like it was already shown in this issue:
> 
> ```js
> // My asyncThunk is as follows
> export const myThunk = createAsyncThunk(
>     'myThunk',
>     async (args, thunkAPI) => {
>         try {
>           // other logic
>           return someResult          
>         } catch (e) {
>           thunkAPI.dispatch(errorAlert("error"));
>           throw e
>         }
>     }
> )
> ```
> 
> You could also look into using the [Action Listener Middleware](https://github.com/reduxjs/redux-toolkit/discussions/1648) to add a listener for your rejected action and do extra side effects there.

Thanks, @phryneas, this makes sense now. Let me take a look at Action Listeners and see that alternative as well.
