### ISSUE TITLE
how large is redux/toolkit with Immer

### ISSUE THREAD

**Issue by Vince-vegas** [reduxjs/redux-toolkit#786]
I heard that redux/toolkit has Immer on it.
How large is the bundle of this library including Immer?

**Comment by markerikson** [comment]
You can see the size using the Bundlephobia tool:

https://bundlephobia.com/result?p=@reduxjs/toolkit@1.4.0

In addition, RTK _should_ correctly tree-shake, so that your bundle only includes the RTK functions you actually import and use.  So, if you don't use `createEntityAdapter`, that shouldn't get included in the final app bundle.

You can also get a sense of how big the code is by looking at the published package contents:

https://unpkg.com/browse/@reduxjs/toolkit@1.4.0/dist/redux-toolkit.esm.js

For example, here's the published source of `createAction`:

```js
function createAction(type, prepareAction) {
  function actionCreator() {
    if (prepareAction) {
      var prepared = prepareAction.apply(void 0, arguments);

      if (!prepared) {
        throw new Error('prepareAction did not return an object');
      }

      return _extends({
        type: type,
        payload: prepared.payload
      }, 'meta' in prepared && {
        meta: prepared.meta
      }, {}, 'error' in prepared && {
        error: prepared.error
      });
    }

    return {
      type: type,
      payload: arguments.length <= 0 ? undefined : arguments[0]
    };
  }

  actionCreator.toString = function () {
    return "" + type;
  };

  actionCreator.type = type;

  actionCreator.match = function (action) {
    return action.type === type;
  };

  return actionCreator;
}
```

Not a lot of actual code there :)

Finally, part of the point of RTK is that it will drastically simplify the same kinds of Redux logic you were already writing.  It's very likely that RTK will shorten your app code enough that using it will be a net _decrease_ in the final bundle size, because the rest of your code becomes a lot shorter.
