### ISSUE TITLE
Error when draft of state is null

### ISSUE THREAD

**Issue by tpetillot** [reduxjs/redux-toolkit#791]
For an union state containing `null` (not `undefined`), CaseReducer will failed with `void` signature.
I guess that a `null` draft is somehow convert into `undefined`.

```
builder.addCase(action.type, (state) => {
 // ...
});
```

**Comment by phryneas** [comment]
Could you please provide a somewhat more complete example or even a codesandbox that showcases this?

**Comment by phryneas** [comment]
I just tried to reproduce this:
```ts
{
  type InitialState = { foo: string } | null
  const action = createAction('test')
  const slice = createSlice({
    initialState: {} as InitialState,
    name: 'foo',
    reducers: {},
    extraReducers(builder) {
      builder.addCase(action, (state, action) => {
        // @ts-expect-error
        expectType<{foo: string}>(state)
        // @ts-expect-error
        expectType<null>(state)
        expectType<{foo: string} | null>(state)
      })
    }
  })
}
```
Everything seems to work as expected. [See TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoIJJsCAOwBo4UMsBlAG2CVQF84AzKCEOAcgAE0ATAK4APAFYBnAPQwIEagGtgMTgCg+qJNXRoWAwngKE4qIWHUwAKgE9TAHnMA+ABQwAXOYCULuOYDcy5QjKcHAw1qhwAJKEisDo1JQwmOEAvIgsMl5iMFDAhADmcEwAPnCEAtTUQWREWXDo+kRwqeRJuPhEjpxYWZzuVUg18GK09E1kaEk0dKiOgcHBuTFxCUleCEzoYpHR+MuJWMRVwYToIKhenMwynIfzcPwC9FBiawy388bZ6ABKqIJPYkcACMBMBqGooO5EEd5iCwRCAHToPh8ADCmxm9XaJDgjiySVIWIMUOS9mhdzuEgkcG4MDEAFpjKY8IyoGwoDC7kyzFZbAgrhBMtlcnkGE58Vg+hT5lSaXTGSYzKz2ZyPoq8LzUDYyhVxftUFLpUZ1RYwjZ+Rk4FkcvliqVytQ9UlDXcGC7ClU3coGEA)
Can you please clarify the problem? Otherwise I'll have to close this.

**Comment by tpetillot** [comment]
I didn't have time to think about it again.

I don't know how you configured the toolkit on the playground, so I cannot provide a reproducer directly.

But, the problem was happening at runtime, when the action was reduce on the extra reducer, using void signature based on `Draft<InititalState>` update being a `Draft<null>`.

Yelling that undefined was not a valid state value (without any update).

```
import {createAction, createSlice} from '@reduxjs/toolkit'

{
  type InitialState = { foo: string } | null

  const action = createAction('test')
  const slice  = createSlice({
    initialState: null as InitialState,
    name: 'foo',
    reducers: {},
    extraReducers(builder) {
      builder.addCase(action, (state: Draft<InitialState>) => {
        // state is null, no update needed on draft
      })
    }
  })
}
```

**Comment by tpetillot** [comment]
I guess I fall into this pit somehow: https://github.com/reduxjs/redux-toolkit/blob/7fda27adc0d91bdd285a2d89b7a004b9ca1d3cd1/src/createReducer.ts#L236

Can't remember how, I'll close this until I can reproduce.

**Comment by msutkowski** [comment]
@tpetillot Make sure you're on the latest rtk release. There was a bug in a minor version a while ago that could've caused that... so if you re-ran yarn during your process it could've resolved itself 😆

**Comment by phryneas** [comment]
Actually, *that* is in master, but has not been released yet :sweat_smile: 

But this started out as a TypeScript error, that line you pointed out there can only cause a runtime error, so it seems to be a different thing.
