### ISSUE TITLE
Advanced Tutorial code errors

### ISSUE THREAD

**Issue by iakovosvo** [reduxjs/redux-toolkit#800]
There are several errors in the codesandbox of this tutorial. Starting with `Cannot read property 'replace' of null`  in `/src/utils/stringUtils.ts:10:23`

**Comment by markerikson** [comment]
Long-term, this ties into the need to rewrite the tutorials over in #371 , but that's very low on my priority list atm.

Unfortunately, this isn't just a simple easy fix.  The sandboxes currently point to very specific commits, and redoing them means:

- cloning the tutorial repo
- resetting the tutorial branch back to wherever the problem started
- fixing up the problem commit
- cherry-picking all existing commits
- Updating the entire tutorial (sandboxes and commit links) to point to the newly generated commit IDs

I don't have time to do that right now.

If this only affects the tail end of the tutorial, the short-term fix might be to file a PR to fix up the the example repo, and update the embed link on the (hopefully just one?) sandbox that's showing this error.

If someone else would like to tackle this, please do so.

**Comment by leosuncin** [comment]
I can give it a try

**Comment by markerikson** [comment]
Please do, thanks!  Let me know if you have any issues/questions with trying to fix things up.

Frankly, it would be a very good thing if we could at least update the tutorial text and sandbox embeds to point to _tags_, instead of commit IDs.  That would simplify the process if we ever need to tweak this again.

You can see how I did that with the new "Essentials/Fundamentals" tutorials over in the Redux core docs.

**Comment by markerikson** [comment]
Obsolete due to #905 .
