### ISSUE TITLE
createAsyncThunk - finally

### ISSUE THREAD

**Issue by ywarezk** [reduxjs/redux-toolkit#801]
Might be useful to add a finally action as well to `createAsyncThunk`.
Could prevent repeated code between **fullfilled** and **rejected**

```
const fetchTask = createAsyncThunk("todo/fetchTodoTask", async () => {
  const res = await fetch(url);
  const task = await res.json();
  return task;
});

const todo = createSlice({
  name: "todo",
  initialState: {
    task: null,
    loading: false,
    err: null
  },
  extraReducers: {
    [fetchTask.fulfilled]: (state, action) => {
      state.task = action.payload;

      // instead of doing this
      state.loading = false;
    },
    [fetchTask.pending]: (state) => {
      state.loading = true;
    },
    [fetchTask.rejected]: (state, action) => {
      state.err = action.error;

      // instead of doing this
      state.loading = false;
    },

    // might be better if we could do this
    [fetchTask.finally]: (state) => {      
      state.loading = false;
    },
  }
});
```

**Comment by markerikson** [comment]
@ywarezk FWIW, you can use the `builder.addMatcher` syntax to do that, and the next release of RTK will have some utils to help specify "match any of these action creators".  See #788 .

**Comment by ywarezk** [comment]
> @ywarezk FWIW, you can use the `builder.addMatcher` syntax to do that, and the next release of RTK will have some utils to help specify "match any of these action creators". See #788 .

Yes you are right.
Thanks a lot.

I still think it's a good idea to add the finally api as well.
Also I don't think it's going to be too hard to implement.

**Comment by phryneas** [comment]
The problem is that this adds a lot of action noise.

Right now, we are having pending/fulfilled/rejected. We could have added cancelled/condition extra actions, but we deliberately chose not to do that as not to add another action - now those are special cases of the rejected action.

Adding another action on top has *really* got to be worth it, and personally I don't really see that with a `finally` - you're the first person to ever see enough use in that to actually suggest it.
