### ISSUE TITLE
TypeScript error when trying to recreate Slice example from doc (defining-the-initial-state-type)

### ISSUE THREAD

**Issue by paulintrognon** [reduxjs/redux-toolkit#826]
I tried to recreate [this example](https://redux-toolkit.js.org/usage/usage-with-typescript#defining-the-initial-state-type)

The reducers are not shown in the example. So I wanted to try by myself, but I keep getting TypeScript errors in my `loadData` reducer:
```ts
import { createSlice, PayloadAction } from '@reduxjs/toolkit'

type SliceState = { state: 'loading' } | { state: 'finished'; data: string }

const initialState: SliceState = { state: 'loading' }

createSlice({
  name: 'test1',
  initialState,
  reducers: {
    // TS Error: "Type '"finished"' is not assignable to type '"loading"'"
    loadData: (state, action: PayloadAction<string>) => ({
      ...state,
      state: 'finished',
      data: action.payload,
    }),
  },
})
```

How can I get this kind of SliceState type to work? Is it possible to include an example of a working reducer in the documentation?

Cheers

**Comment by phryneas** [comment]
Yeah, this is unfortunately a problem in newer TS versions as TS will do a code flow analysis and decide on it's own that `initialState` will always be of type `{ state: 'loading' }`, because it never gets reassigned.

You can do `const initialState = { state: 'loading' } as SliceState` instead, as it's more expicit & TS will honor that.

Thank you for pointing that out - I'll fix up the docs.
