### ISSUE TITLE
access state in reducer?

### ISSUE THREAD

**Issue by stoplion** [reduxjs/redux-toolkit#859]
How do you access state in reducer? Maybe I am missing it in the docs, but I can't find the solution to this simple use case.

```
.addCase(actions.rmTxsPending, (state, action) => {
      const newState = state.filter((pendingTx) => {
        return pendingTx.hash === action.hash;
      });

      state = newState;
    })
```

`State` is a proxy so this fails.

How do you accomplish something like this with Redux?

**Comment by markerikson** [comment]
Not sure I understand the question.  `state` is your actual data, wrapped in a Proxy.  All the access logic works correctly.

The wrong line here is `state = newState` . That doesn't do anything useful, regardless of whether or not you're using Immer.  It just points the local variable `state` to a new reference.  But, Immer doesn't work that way - it relies on either _mutating_ the existing data, or _returning_ a new value you created yourself.

You need to `return newState` here, since you've constructed a new array reference.

**Comment by stoplion** [comment]
Sorry
