### ISSUE TITLE
Performance query !!

### ISSUE THREAD

**Issue by suyashdeshpande** [reduxjs/redux-toolkit#866]
Let's say we have 10k objects in state and we update only one object in the slice. Since immer freezes the data, will it become a performance issue?

**Comment by phryneas** [comment]
Unlikely, since 9999 of these objects will already been frozen. (and 10k is not a big number for computers)
But you can always just freeze the returned object shallowly before returning to prevent immer from doing so recursively, if you come to the point where you would need that performance optimization.

But as with every premature optimization: you'll need to measure that with actual data when you get to the point, doing anything beforehand will most likely be detrimental for performance and just overcomplicate your code.

**Comment by suyashdeshpande** [comment]
@phryneas "since 9999 of these objects will already be frozen" Do you mean to say, if we change an object out of 10k objects, then the rest 9999 will remain frozen and immer will only create a deep copy of the mutated object and freeze it?

**Comment by phryneas** [comment]
Most likely yes. `immer` tracks the changes you make and only applies that "changeset" to a shallow copy of the original object. So if you don't touch a "property branch" of an object, that will stay the same over multiple iterations.

**Comment by suyashdeshpande** [comment]
Ohh Thanks for the help
