### ISSUE TITLE
unexpected rerenders with selectById

### ISSUE THREAD

**Issue by lukesmurray** [reduxjs/redux-toolkit#884]
I have a hook which does a simple selectByID from the store.

// store
```ts
export const useTypedSelector = createSelectorHook<RootState>();
```

// hook
```ts
useCurrentStatus = (statusId: string) => {
  return useTypedSelector((state) =>
    apiStatusSelectors.selectById(state, statusId)
  );
}
```

Now for some reason when I render a component for the first time, all the components which have the same status id render as well.

I looked in the react profiler and it said these components were rendering because of hook changes.

So I manually diffed the hooks and found that one of the subhooks of `selectById` appears to be triggering the render.

```json
    {
      "name": "SelectorWithStoreAndSubscription",
      "subHooks": [
        {
          "name": "Reducer",
          "value": 3,
          "subHooks": []
        },
```

Specifically the value on `"SelectorWithStoreAndSubscription"` increments whenever I render a new component.

Any ideas where `"SelectorWithStoreAndSubscription"` is coming from and why those values would be changing across components?

**Comment by markerikson** [comment]
Sorry, I'm a bit confused.  `selectById` is a selector - it doesn't have any "hooks" or "subhooks".  Are you referring to `useSelector` itself there? That counter looks like the internal value that `useSelector` uses to force a re-render.  However, it only does that if the reference returned by your selector changes from the last time.

`selectById` is memoized, but ultimately comes down to a straight lookup: `return state.entities[id]`, effectively.  On the one hand, using the same `selectById` instance across multiple components will never memoize correctly, but because it's a lookup, it shouldn't actually matter on a per-component basis.

Can you put together a CodeSandbox that shows this issue?

**Comment by lukesmurray** [comment]
ok that actually solves the issue for me! Basically the same code which renders this hook also initializes the value which is being selected here so the reference is changing unintentionally. Thank you!

**Comment by markerikson** [comment]
Just outta curiosity, can you show the relevant code so I know what's going on?

**Comment by lukesmurray** [comment]
Sure I can pseudo code it.
The actual code is a little bit too much to just copy paste here.

Essentially I have some code which queries an api.

```tsx
const apiQuery = useQuery(...)
```

Then based on the results of that api call I update the api status in my store.

```tsx
useEffect(() => {

  dispatch(apiStatusUpdated(apiQuery.status)

}, [apiQuery.status])
```

Then later I have some code which handles some effects based on the current api status.

```tsx
cont apiStatus = useCurrentStatus(apiQuery.id)

useEffect(() => {
//...
}, [apiStatus])
```

Every time this branch of code runs the api status is updated and all of the selectors re render as expected.

Now the reason I was struggling to debug it is because the api status is actually shallow equal most of the time so I didn't see any values changing.
Also this code is spread out across a couple different hooks so it wasn't quite as obvious as it seems here.
The fix was to check if the api status is shallow equal in the `apiStatusUpdated` action and if it is I don't update the state.
That fix makes the selectors stop firing and everything is resolved.

**Comment by markerikson** [comment]
ah, gotcha!
