### ISSUE TITLE
Export redux-thunk for redux-mock-store

### ISSUE THREAD

**Issue by binarykitchen** [reduxjs/redux-toolkit#892]
To use the redux-mock-store library, I need the toolkit to offer an export of redux-thunk. Don't want to install redux-thunk unneccessarily.

For example

```
import configureMockStore from 'redux-mock-store'
import thunk from 'redux-thunk'

const middlewares = [thunk]
const mockStore = configureMockStore(middlewares)
```

this would be better

```
import configureMockStore from 'redux-mock-store'
import { thunk } from '@reduxjs/toolkit' <--- this!

const middlewares = [thunk]
const mockStore = configureMockStore(middlewares)
```

How else can I use redux-mock-store in conjunction with your toolkit?

**Comment by msutkowski** [comment]
Hey @binarykitchen! Is there a specific reason that you're using `redux-mock-store` to begin with? In most cases, you should just use your normal store. If you're just checking your actions, you can do the same thing with `jest.spyOn(store, 'dispatch')`.

In regards to RTK exporting `thunk` -- this has come up a couple of times and I think the consensus has been that it's not going to happen, but I could be wrong.

**Comment by markerikson** [comment]
Yeah, I'm not seeing a real need to do this.

From my own perspective, the use case for `redux-mock-store` is mostly gone.  Redux-related tests should construct a real store and interact with rendered components, rather than checking if specific actions were dispatched.

As you showed, you can always add a specific dependency on `redux-thunk` and import it yourself.  Note that since RTK depends on `redux-thunk`, no additional packages will be installed - it's already there.  You're just telling the package manager "no, really, I want to use this too".

**Comment by binarykitchen** [comment]
thanks guys will follow your suggestions
