### ISSUE TITLE
Turn reselect into a peer dependency

### ISSUE THREAD

**Issue by binarykitchen** [reduxjs/redux-toolkit#896]
It's me again. Using the `re-reselect` library and seeing that classic warning upon running yarn install:

```
warning " > re-reselect@4.0.0" has unmet peer dependency "reselect@>1.0.0".
```

Don't want to install reselect twice, as a dependency and within your package. If it were a peer dependency in RTK, then this warning is gone. What do you think?

**Comment by markerikson** [comment]
Can't do that, because we do directly depend on Reselect and use it in `createEntityAdapter` as of 1.3.  Prior to that, we still had it as a direct dep just to force that it was installed and then re-exported, but the `adapter.getSelectors()` method does now actually directly call `createSelector()`.

In theory, you can ignore this warning because you know that `reselect` will be installed, and both NPM and Yarn should hoist it to the root of `node_modules` anyway.  That said, if you add it as a specific dependency, you should still only have one copy of `reselect` installed.
