### ISSUE TITLE
createAsyncThunk type with correct dispatch not working

### ISSUE THREAD

**Issue by Golyo88** [reduxjs/redux-toolkit#912]
I found multiple errors regarding this, but everyone's solution was that they used the dispatch function from react-redux. I'm using the one from my store, but I still get the 
```Argument of type 'AsyncThunkAction<...>  is not assignable to parameter of type 'AnyAction'. Property 'type' is missing in type```

I am calling the createAsyncThunk function

```export const connectToDevice = createAsyncThunk('name', async () => {async stuff being done here and returning a promise})```

then i'm calling the `createSlice` and adding all 3 states under the `extraReducers` key of the `connectToDevice` action;
```
const s = createSlice({
name: '...',
initialState: initialState,
reducers: {},
extraReducers: (builder) => {
builder.addCase(connectToDevice.pending, (state: State, action) => {
      ...
    });
...
}
});

export default s.reducer;
```

and then in my store:

```
const store = configureStore({
  reducer: {
    s: s,
  },
});

export default store;
export type AppDispatch = typeof store.dispatch;
```

and then:
```
import {useDispatch} from 'react-redux';

import {AppDispatch, RootState} from '.';

export const useAppDispatch = () => useDispatch<AppDispatch>();
```

I'm new to react, redux  but i guess after this point the `useAppDispatch()` should know about the thunk middleware...

so in my component:
```
const dispatch: AppDispatch = useAppDispatch();
dispatch(connectToDevice());
```

Still... I've got the error. What am I doing wrong?

**Comment by markerikson** [comment]
Hmm. That _looks_ like it should be correct.  Can you put up a CodeSandbox that reproduces this issue?

**Comment by msutkowski** [comment]
I know this is just a partial example, but I'd recommend removing all of your extra types. For example:

- `const dispatch: AppDispatch = useAppDispatch();` is redundant, and you can drop the `:AppDispatch`. 
- `builder.addCase(connectToDevice.pending, (state: State, action) => {` - the `: State` cast can be removed there. 

Is the code you showed above your full `configureStore`? If not, are you possibly overriding the middleware types in your actual code?

**Comment by Golyo88** [comment]
> Hmm. That _looks_ like it should be correct. Can you put up a CodeSandbox that reproduces this issue?

Something like this: https://codesandbox.io/s/headless-wildflower-e7pu9?file=/src/Connected.tsx

**Comment by Golyo88** [comment]
> const dispatch: AppDispatch = useAppDispatch(); is redundant, and you can drop the :AppDispatch.
I'm comingfrom a strongly typed world. I prefer remembering the variables by their type instead of their name. So if I look into disptach I can see it that it is an AppDispatch instead of I have to go into `useAppDispatch` return value to see what it's type. I think i should not affect anything.

> builder.addCase(connectToDevice.pending, (state: State, action) => { - the : State cast can be removed there.
It's a type hint isn't it? It's not a cast. It makes the compiler? think that it is an any type so the point of the types are gone...

**Comment by phryneas** [comment]
> I'm coming from a strongly typed world. I prefer remembering the variables by their type instead of their name. So if I look onto `disptach` I can see it that it is an `AppDispatch` instead of I have to go into `useAppDispatch`'s return value to see what it's type. It think i should not affect anything.

Exactly this is your problem though. By specifying a type by hand, you are actively erasing additional type information.

You do `const store: EnhancedStore = configureStore({` in your code. Without that assignment, `store` is of the type
```ts
const store: EnhancedStore<{
    app: {
        connected: boolean;
    };
}, AnyAction, [ThunkMiddleware<{
    app: {
        connected: boolean;
    };
}, AnyAction, null> | ThunkMiddleware<{
    app: {
        connected: boolean;
    };
}, AnyAction, undefined>]>
```

So `export type AppDispatch = typeof store.dispatch;`  actually knows about the presence of the `ThunkMiddleware` because the type of `store` refers to that.

After you do that `const store: EnhancedStore = configureStore(...`, `store` is just *any `EnhancedStore` without any details*. So you actively erase type information by manually specifying a type. And as a consequence, `AppDispatch` is missing the details about `thunk` being present.

If you want that type information, I suggest you do not type it out in your code, but you just get a decent IDE like VSCode and just hover over the variable - that will always tell you which type it is anywas, no need to go through your code and search the point where you declared it.

**Comment by Golyo88** [comment]
You are right @phryneas! Thanks a lot!
