### ISSUE TITLE
TypeScript: createAsyncThunk does not return a 'real' redux Action

### ISSUE THREAD

**Issue by briunsilo** [reduxjs/redux-toolkit#914]
Trying to use createAsyncThunk + redux-observable with TypeScript.

But I'm having issues with type annotations of the thunks created by createAsyncThunk, as it returns an `AsyncThunk` instead of something which implements the interface `Action<T = any> { type: T }` as defined by redux.

This leads to TypeScript warnings about a missing 'type' property.

Am I missing something?

Example:
```
///////////// THUNK ////////////////

const fetchTodos = createAsyncThunk<Todo[]>(
    "todos/fetch",
    async () => {
        const response = await fetch(`https://jsonplaceholder.typicode.com/todos`);
        return await response.json() as Todo[];
    }
);

///////////// SLICE ////////////////

type TodosState = {
    status: string
    list: Todo[];
};

const initialState = {
    list: [],
    status: 'INITIAL',
} as TodosState;

const todosSlice = createSlice({
    name: "todos",
    initialState,
    reducers: {
        fetch(state, action){},
    },
    extraReducers: (builder) => {
        builder.addCase(fetchTodos.pending, (state) => {
            state.status = 'LOADING';
        });
        builder.addCase(fetchTodos.fulfilled,
            (state, {payload}) => {
                state.list.push(...payload);
                state.status = 'DONE';
            });
        builder.addCase(fetchTodos.rejected,
            (state, {payload}) => {
                state.status = 'ERROR';
            });
    },
});

///////////// OBSERVABLE ////////////////

// This works if `fetchTodos` is replaced with another action from the slice.

const Actions = {...todosSlice.actions, fetchTodos};

type ActionTypes =
    | ReturnType<typeof todosSlice.actions.fetch>
    | ReturnType<typeof fetchTodos>

// TS2344: Type 'ActionTypes' does not satisfy the constraint 'Action<any>'. Property 'type' is missing in type 'AsyncThunkAction<Todo[], void, {}>' but required in type 'Action<any>'.
const fetchEpic$: Epic<ActionTypes, ActionTypes, TodosState> = (actions$, state$) =>
    actions$.pipe(
        filter<ActionTypes, ReturnType<typeof Actions.fetch>>(Actions.fetch.match),
        // More operators ...
        map(Actions.fetchTodos),
    );
```

**Comment by phryneas** [comment]
Thunks never have a `type` property, because they are functions that are dispatched to be handled by the `thunk` middleware, not objects.
So you can also not filter for them in an epic. You could probably dispatch them if the redux-observable middleware knew about thunks, but I don't know if it does. At least from the typings it doesn't seem like it.

I have to ask though: why are you combining redux-observable and redux-thunk here? They already do the same job.
Why filter for `Actions.fetch` and then dispatch `Actions.fetchTodos` instead of directly dispatching `Actions.fetchTodos`? That seems like a lot of unneccessary indirection.

**Comment by briunsilo** [comment]
It's just a simplified example. The real-world usage combines a lot of RxJs operators for handling debounce, distinct input etc.

My problem is that I cannot end up dispatching a "thunk action" from redux-observable, only slice actions.

**Comment by phryneas** [comment]
We cannot do a lot about that though. I mean, you can try if it works with a `@ts-ignore` annotation and in that case, only the rxjs-observable types would need a change.
Either way, this is something that would need a change at the rxjs-observable side, we cannot really do anything about it.

The only way around it would be to pipe it into a custom function of your own in the end and dispatch the thunk manually there.

**Comment by briunsilo** [comment]
Thanks 👍

**Comment by mtsdalmolin** [comment]
I'll recycle this issue to ask my question:

I'm trying to dispatch an action using the object syntax:
`dispatch({ type: 'actions/myAction', payload: { ...someData } })`

Is there a way to dispatch a thunk action like this?

Or thunks are only allowed to be used in the `dispatch(myAction({ ...someData }))` syntax because they don't have a `type` key, like @phryneas mentioned?

**Comment by markerikson** [comment]
@mtsdalmolin really not sure what you're asking here. 

the `dispatch(myAction())` syntax is "just" an action creator. Action creators normally return action objects, like `{types: 'actions/myAction'}`.  However, we also normally write thunks wrapped in an action creator as well. Ultimately, all the action creator is doing is generating the thing that we pass to `dispatch`, and it's irrelevant to the process of _actually_ dispatching.

So, yes, you can write a thunk function by itself, without an action creator, and pass it to `dispatch`, because that's all that the action creator is actually doing.  Per my example gist at https://gist.github.com/markerikson/6c7608eee5d2421966d3df5edbb8f05c :

```js
// approach 1: define action object in the component
this.props.dispatch({
    type : "EDIT_ITEM_ATTRIBUTES", 
    payload : {
        item : {itemID, itemType},
        newAttributes : newValue,
    }
});

// approach 2: use an action creator function
const actionObject = editItemAttributes(itemID, itemType, newAttributes);
this.props.dispatch(actionObject);

// approach 3: directly pass result of action creator to dispatch
this.props.dispatch(editItemAttributes(itemID, itemType, newAttributes));

// approach 4: pre-bind action creator to automatically call dispatch
const boundEditItemAttributes = bindActionCreators(editItemAttributes, dispatch);
boundEditItemAttributes(itemID, itemType, newAttributes);

// parallel approach 1: dispatching a thunk function
const innerThunkFunction1 = (dispatch, getState) => {
    // do useful stuff with dispatch and getState        
};
this.props.dispatch(innerThunkFunction1);

// parallel approach 2: use a thunk action creator to define the function        
const innerThunkFunction = someThunkActionCreator(a, b, c);
this.props.dispatch(innerThunkFunction);

// parallel approach 3: dispatch thunk directly without temp variable        
this.props.dispatch(someThunkActionCreator(a, b, c));

// parallel approach 4: pre-bind thunk action creator to automatically call dispatch
const boundSomeThunkActionCreator = bindActionCreators(someThunkActionCreator, dispatch);
boundSomeThunkActionCreator(a, b, c);
```

**Comment by mtsdalmolin** [comment]
Thanks for the response @markerikson . I thought i had it, but now I'm a little more confused. lol

I made a minimalist reproduction of the way I'm using it in my application in this [codesandbox](https://codesandbox.io/s/redux-toolkit-actions-478vm?file=/src/App.js).

Why the action is not being executed if i try to dispatch using the 1st approach?

**Comment by phryneas** [comment]
@mtsdalmolin because your reducer is reacting to `myAction.fulfilled`, which is `'actions/myAction/fulfilled'`.

Also that thunk dispatches `'actions/myAction/pending'` and `'actions/myAction/rejected'`, but I would take all of those as an implementation detail and not dispatch those strings by hand. What if we decide to change how those strings are built in a 2.0 release? (We won't, but what if?)

**Comment by mtsdalmolin** [comment]
Thanks for the clarification, @phryneas .I kinda figured it out when i published the comment.

I am refactoring my application, that was using `redux-sagas` to create actions and aggregate them in a combined-actions object, to start using `redux-toolkit`. In it, i have this modal component that receives the action type and dispatches the specificied action using that approach to avoid excessive actions imports in my component.

I must have confused myself in this refactoring and changing the way things are working in my application.

Now that i have a better understanding of it, makes sense not to dispatch using this approach for this scenario.

Anyway, thanks everybody for answering and helping me out understanding it! :)
